import kotlinx.io.*
import kotlinx.io.bytestring.ByteString

fun sourceSurface(source: Source, buffer: Buffer, bytes: ByteArray, pattern: ByteString) {
    source.readTo(bytes)
    source.readTo(bytes, 1, bytes.size)
    source.readAtMostTo(bytes)
    source.readAtMostTo(bytes, 1)
    source.readAtMostTo(bytes, endIndex = 2)
    source.readAtMostTo(bytes, 0, bytes.size)
    source.readByteArray()
    source.readByteArray(2)
    source.readDecimalLong()
    source.readHexadecimalUnsignedLong()
    source.readShortLe()
    source.readIntLe()
    source.readLongLe()
    source.readUByte()
    source.readUShort()
    source.readUInt()
    source.readULong()
    source.readUShortLe()
    source.readUIntLe()
    source.readULongLe()
    source.readFloat()
    source.readDouble()
    source.readFloatLe()
    source.readDoubleLe()
    source.startsWith(1)
    source.indexOf(1)
    source.indexOf(1, 2L, 3L)
    source.indexOf(pattern)
    source.indexOf(pattern, 1L)
    source.readByteString()
    source.readByteString(2)
    buffer.readTo(bytes)
    buffer.readAtMostTo(bytes)
    buffer.indexOf(pattern)
    buffer.indexOf(pattern, 1L)
}
