package golden.sema

fun maxOfComparable2(a: String, b: String): String = maxOf(a, b)
fun maxOfComparableVararg(a: String, b: String, c: String, d: String): String = maxOf(a, b, c, d)
fun maxOfByteVararg(a: Byte, b: Byte, c: Byte, d: Byte): Byte = maxOf(a, b, c, d)
fun maxOfDoubleVararg(a: Double, b: Double, c: Double, d: Double): Double = maxOf(a, b, c, d)
fun maxOfFloatVararg(a: Float, b: Float, c: Float, d: Float): Float = maxOf(a, b, c, d)
fun maxOfIntVararg(a: Int, b: Int, c: Int, d: Int): Int = maxOf(a, b, c, d)
fun maxOfLongVararg(a: Long, b: Long, c: Long, d: Long): Long = maxOf(a, b, c, d)
fun maxOfShortVararg(a: Short, b: Short, c: Short, d: Short): Short = maxOf(a, b, c, d)
fun maxOfUByteVararg(a: UByte, b: UByte, c: UByte, d: UByte): UByte = maxOf(a, b, c, d)
fun maxOfUIntVararg(a: UInt, b: UInt, c: UInt, d: UInt): UInt = maxOf(a, b, c, d)
fun maxOfULongVararg(a: ULong, b: ULong, c: ULong, d: ULong): ULong = maxOf(a, b, c, d)
fun maxOfUShortVararg(a: UShort, b: UShort, c: UShort, d: UShort): UShort = maxOf(a, b, c, d)
fun maxOfByte2(a: Byte, b: Byte): Byte = maxOf(a, b)
fun maxOfShort2(a: Short, b: Short): Short = maxOf(a, b)
fun maxOfComparator2(a: String, b: String, comparator: Comparator<Any>): String = maxOf(a, b, comparator)
fun maxOfComparatorVararg(a: String, b: String, c: String, d: String, comparator: Comparator<Any>): String = maxOf(a, b, c, d, comparator = comparator)
fun maxOfComparable3(a: String, b: String, c: String): String = maxOf(a, b, c)
fun maxOfByte3(a: Byte, b: Byte, c: Byte): Byte = maxOf(a, b, c)
fun maxOfShort3(a: Short, b: Short, c: Short): Short = maxOf(a, b, c)
fun maxOfComparator3(a: String, b: String, c: String, comparator: Comparator<Any>): String = maxOf(a, b, c, comparator)
