// KUU-1327: Annotation Any methods compare members, including array contents.
package annotationmethods

annotation class B1(val i: Int)
annotation class B4(val s: String)
annotation class B2(val a: IntArray)
annotation class Empty
data class Data(val a: IntArray)
annotation class Mixed(val z: String = "default", val a: Int = 7)
annotation class Nested(val b: B1, val names: Array<String>)
annotation class Numbers(val f: Float, val d: Double, val b: Boolean, val c: Char, val l: Long)
annotation class Arrays(val b: BooleanArray, val c: CharArray, val d: DoubleArray)

fun main() {
    println(B1(1) == B1(1))
    println(B1(1) == B1(2))
    println(B4("x") == B4("x"))
    println(B4("x") == B4("y"))
    println(B4("x").toString())
    println(B2(intArrayOf(1, 2)) == B2(intArrayOf(1, 2)))
    println(B2(intArrayOf(1, 2)) == B2(intArrayOf(2, 1)))
    println(B2(intArrayOf(1)) == B2(intArrayOf(1, 2)))
    println(B1(1).hashCode() == B1(1).hashCode())
    println(B1(1).hashCode())
    println(B2(intArrayOf(1, 2)).hashCode())
    println(B2(intArrayOf(1, 2)))
    val left: Any = B1(1)
    val right: Any = B1(1)
    println(left == right)
    println(left.equals(right))
    println(left == B4("1"))
    println(left.equals(null))
    println(left.toString())
    println("annotation=$left")
    println(listOf(left).contains(right))
    println(left.hashCode() == right.hashCode())
    println(Empty() == Empty())
    println(Empty().equals(null))
    println(Empty().equals(B1(1)))
    println(Empty())
    println(Empty().hashCode())
    println(Mixed())
    println(Mixed() == Mixed("default", 7))
    println(Mixed().hashCode())
    println(Nested(B1(3), arrayOf("x", "y")) == Nested(B1(3), arrayOf("x", "y")))
    println(Nested(B1(3), arrayOf("x")) == Nested(B1(4), arrayOf("x")))
    println(Nested(B1(3), arrayOf("x", "y")))
    println(Nested(B1(3), arrayOf("x", "y")).hashCode())
    println(Numbers(Float.NaN, Double.NaN, true, 'a', 42L) == Numbers(Float.NaN, Double.NaN, true, 'a', 42L))
    println(Numbers(0.0f, 0.0, true, 'a', 42L) == Numbers(-0.0f, 0.0, true, 'a', 42L))
    val canonical = Numbers(Float.NaN, Double.NaN, true, 'a', 42L)
    val payloadNaN = Numbers(Float.fromBits(2143289345), Double.fromBits(9221120237041090561L), true, 'a', 42L)
    println(canonical == payloadNaN)
    println(canonical.hashCode() == payloadNaN.hashCode())
    println(Numbers(-0.0f, -0.0, false, 'z', Long.MIN_VALUE).hashCode())
    println(Numbers(-1.0f, -2.0, false, 'z', 42L).hashCode())
    println(Numbers(1.0f, 2.0, true, 'a', 42L))
    println(Numbers(1.0f, 2.0, true, 'a', 42L).hashCode())
    println(Arrays(booleanArrayOf(true, false), charArrayOf('a', 'b'), doubleArrayOf(1.0, 2.0)))
    println(Arrays(booleanArrayOf(true), charArrayOf('a'), doubleArrayOf(Double.NaN)) == Arrays(booleanArrayOf(true), charArrayOf('a'), doubleArrayOf(Double.NaN)))
    // Data-class array members retain reference equality.
    val values = intArrayOf(1, 2)
    println(Data(values) == Data(values))
    println(Data(intArrayOf(1, 2)) == Data(intArrayOf(1, 2)))
}
