fun main() {
    val words: Array<out String> = arrayOf("b", "a", "c")
    val ascending: List<String> = words.sorted()
    println(ascending)
    println(words.sortedDescending())
    println(words.reversed())
    println(words.toList())
    words.sortDescending()
    println(words.toList())
    val range: Array<out String> = arrayOf("z", "c", "a", "b", "y")
    range.sort(1, 4)
    println(range.toList())
    range.sort(toIndex = 2)
    println(range.toList())
    range.sort(fromIndex = 3)
    println(range.toList())
    range.sort(2, 2)
    println(range.toList())
    val mutable = arrayOf("b", "a", "c")
    mutable.reverse()
    println(mutable.toList())
    println(arrayOf("bb", "a", "cc", "d").sortedBy { it.length })
    println(arrayOf("bb", "a", "cc", "d").sortedBy { if (it.length == 1) null else it.length })
    println(arrayOf("bb", "a", "cc", "d").sortedWith(compareBy { it.length }))
    println(arrayOf(3, 1, 2).sortedWith(compareBy { -it }))
    println(emptyArray<String>().sorted())
    println(emptyArray<String>().reversed())
    val singleton = arrayOf("x")
    singleton.reverse()
    singleton.sortDescending()
    println(singleton.toList())
    try { range.sort(3, 2) } catch (e: IllegalArgumentException) { println("invalid range") }
    try { range.sort(-1, 2) } catch (e: IndexOutOfBoundsException) { println("negative index") }
    try { range.sort(0, 6) } catch (e: IndexOutOfBoundsException) { println("large index") }
    val ints = intArrayOf(3, 1, 2)
    val intsReversed: List<Int> = ints.reversed()
    println(intsReversed)
    println(ints.toList())
    val intsSorted: List<Int> = ints.sortedDescending()
    println(intsSorted)
    ints.reverse()
    println(ints.toList())
    val longs = longArrayOf(3L, 1L, 2L)
    val longsReversed: List<Long> = longs.reversed()
    println(longsReversed)
    println(longs.toList())
    val longsSorted: List<Long> = longs.sortedDescending()
    println(longsSorted)
    longs.reverse()
    println(longs.toList())
    val shorts = shortArrayOf(3, 1, 2)
    val shortsReversed: List<Short> = shorts.reversed()
    println(shortsReversed)
    println(shorts.toList())
    val shortsSorted: List<Short> = shorts.sortedDescending()
    println(shortsSorted)
    shorts.reverse()
    println(shorts.toList())
    val bytes = byteArrayOf(3, 1, 2)
    val bytesReversed: List<Byte> = bytes.reversed()
    println(bytesReversed)
    println(bytes.toList())
    val bytesSorted: List<Byte> = bytes.sortedDescending()
    println(bytesSorted)
    bytes.reverse()
    println(bytes.toList())
    val chars = charArrayOf('c', 'a', 'b')
    val charsReversed: List<Char> = chars.reversed()
    println(charsReversed)
    println(chars.toList())
    val charsSorted: List<Char> = chars.sortedDescending()
    println(charsSorted)
    chars.reverse()
    println(chars.toList())
    val doubles = doubleArrayOf(3.0, 1.0, 2.0)
    val doublesReversed: List<Double> = doubles.reversed()
    println(doublesReversed)
    println(doubles.toList())
    val doublesSorted: List<Double> = doubles.sortedDescending()
    println(doublesSorted)
    doubles.reverse()
    println(doubles.toList())
    val floats = floatArrayOf(3.0f, 1.0f, 2.0f)
    val floatsReversed: List<Float> = floats.reversed()
    println(floatsReversed)
    println(floats.toList())
    val floatsSorted: List<Float> = floats.sortedDescending()
    println(floatsSorted)
    floats.reverse()
    println(floats.toList())
    val booleans = booleanArrayOf(true, false, false)
    val booleansReversed: List<Boolean> = booleans.reversed()
    println(booleansReversed)
    println(booleans.toList())
    booleans.reverse()
    println(booleans.toList())
    val ubytes = ubyteArrayOf(3u, 1u, 2u)
    val ubytesReversed: List<UByte> = ubytes.reversed()
    println(ubytesReversed)
    println(ubytes.toList())
    val ubytesSorted: List<UByte> = ubytes.sortedDescending()
    println(ubytesSorted)
    ubytes.reverse()
    println(ubytes.toList())
    val ushorts = ushortArrayOf(3u, 1u, 2u)
    val ushortsReversed: List<UShort> = ushorts.reversed()
    println(ushortsReversed)
    println(ushorts.toList())
    val ushortsSorted: List<UShort> = ushorts.sortedDescending()
    println(ushortsSorted)
    ushorts.reverse()
    println(ushorts.toList())
    val uints = uintArrayOf(3u, 1u, 2u)
    val uintsReversed: List<UInt> = uints.reversed()
    println(uintsReversed)
    println(uints.toList())
    val uintsSorted: List<UInt> = uints.sortedDescending()
    println(uintsSorted)
    uints.reverse()
    println(uints.toList())
    val ulongs = ulongArrayOf(3uL, 1uL, 2uL)
    val ulongsReversed: List<ULong> = ulongs.reversed()
    println(ulongsReversed)
    println(ulongs.toList())
    val ulongsSorted: List<ULong> = ulongs.sortedDescending()
    println(ulongsSorted)
    ulongs.reverse()
    println(ulongs.toList())
    val empty = intArrayOf()
    empty.reverse()
    println(empty.reversed())
    println(empty.sortedDescending())
    val one = booleanArrayOf(true)
    one.reverse()
    println(one.reversed())
}
