fun main() {
    val values: Array<out String> = arrayOf("a", "bb", "a")
    println(values.associate { it to it.length })
    println(values.associateBy { it.length })
    println(values.associateBy({ it.length }, { it + "!" }))
    println(values.associateWith { it.length })
    println(values.associateTo(mutableMapOf()) { it to it.length })
    println(values.associateByTo(mutableMapOf()) { it.length })
    println(values.associateByTo(mutableMapOf(), { it.length }, { it + "!" }))
    println(values.associateWithTo(mutableMapOf()) { it.length })
    val destination = mutableMapOf<Any?, Any?>("seed" to -1)
    println(values.associateTo(destination) { it to it.length } === destination)
    println(values.associateByTo(destination) { it.length } === destination)
    println(values.associateWithTo(destination) { it.length } === destination)
    println(destination)
    println(arrayOf("a", "bb").associateWith { if (it == "a") null else it.length })
    println(emptyArray<String>().associate { it to it })
    println(emptyArray<String>().associateBy { it })
    println(emptyArray<String>().associateWith { it })
}
