fun checkIterable(values: Iterable<Int>) {
    println(values.associate { it to it * 10 })
    println(values.associateBy { it % 2 })
    println(values.associateBy({ it % 2 }, { it * 10 }))
    println(values.associateWith { it * 10 })
    println(values.associateTo(mutableMapOf()) { it to it * 10 })
    println(values.associateByTo(mutableMapOf()) { it % 2 })
    println(values.associateByTo(mutableMapOf(), { it % 2 }, { it * 10 }))
    println(values.associateWithTo(mutableMapOf()) { it * 10 })
}

fun main() {
    println(setOf(1, 2, 3).associate { it to it })
    println(setOf(1, 2, 3).associateBy { it % 2 })
    println(setOf(1, 2, 3).associateBy({ it % 2 }, { it * 10 }))
    println(setOf(1, 2, 3).associateWith { it * 10 })
    println(setOf(1, 2, 3).associateTo(mutableMapOf()) { it to it })
    println(setOf(1, 2, 3).associateByTo(mutableMapOf()) { it % 2 })
    println(setOf(1, 2, 3).associateByTo(mutableMapOf(), { it % 2 }, { it * 10 }))
    println(setOf(1, 2, 3).associateWithTo(mutableMapOf()) { it * 10 })
    checkIterable(setOf(1, 2, 3))
    checkIterable(mutableSetOf(1, 2, 3))
    val iterable: Iterable<Int> = listOf(1, 2, 3, 1)
    checkIterable(iterable)
    val collection: Collection<Int> = listOf(1, 2, 3, 1)
    println(collection.associateBy { it })
    println(listOf(1, 2, 3).asIterable().associate { it to it })
    println(mapOf("a" to 1, "b" to 2).entries.associate { it.key to it.value })
    println(mapOf("a" to 1, "b" to 2).keys.associateWith { it.length })
    val destination = mutableMapOf<Any?, Any?>(0 to "seed")
    println(setOf(1, 2, 3).associateByTo(destination) { it } === destination)
    println(setOf(1, 2, 3).associateWithTo(destination) { it * 10 } === destination)
    println(setOf(1, 2, 3).associateTo(destination) { it to it * 100 } === destination)
    println(destination)
    println(setOf(1, 2).associateWith { if (it == 1) null else "two" })
    checkIterable(emptySet())
    println(listOf(1, 2, 3).associate { it to it })
    println(sequenceOf(1, 2, 3).associate { it to it })
}
