fun main() {
    val values = listOf(1, 2, 2, 3)
    parameterOps(values, listOf(3, 4))
    println(values + 4)
    println(values + listOf(4, 5))
    println(values - 2)
    println(values - listOf(2, 3))
    println(values intersect listOf(2, 4))
    println(values union listOf(3, 4))
    println(values subtract listOf(2))
    println(values.distinct())
    println(values.distinctBy { it % 2 })
    println(values.sum())
    println(values.sumOf { it * 2 })
    println(values.sumBy { it + 1 })
    println(values.sumByDouble { it.toDouble() / 2.0 })
    println(values.average())
    println(values.reversed())
    println(values.asReversed())
}

fun parameterOps(values: List<Int>, other: List<Int>) {
    println(values + 4)
    println(values + other)
    println(values - 2)
    println(values - other)
    println(values intersect other)
    println(values union other)
    println(values subtract other)
    println(values.distinct())
    println(values.distinctBy { it % 2 })
    println(values.sum())
    println(values.sumOf { it * 2 })
    println(values.sumBy { it + 1 })
    println(values.sumByDouble { it.toDouble() / 2.0 })
    println(values.average())
    println(values.reversed())
    println(values.asReversed())
}
