// KUU-1105: primitive-array extension matrix and edge contracts.
private fun indexedReturn(): Int {
    intArrayOf(7).forEachIndexed { _, value -> return value }
    return 0
}

private class MutatingPrimitiveIterable(private val array: IntArray) : Iterable<Int> {
    var pulls = 0
    override fun iterator(): Iterator<Int> = object : Iterator<Int> {
        private var index = 0
        override fun hasNext(): Boolean = index < 2
        override fun next(): Int {
            pulls++
            array[0] = 9
            return ++index
        }
    }
}

fun main() {
    println(indexedReturn())
    val zipLive = intArrayOf(1)
    val zipOther = MutatingPrimitiveIterable(zipLive)
    println(zipLive.zip(zipOther))
    println(zipOther.pulls)
    val zipTransformLive = intArrayOf(1)
    val zipTransformOther = MutatingPrimitiveIterable(zipTransformLive)
    println(zipTransformLive.zip(zipTransformOther) { left, right -> left + right })
    println(zipTransformOther.pulls)
    val zipEmpty = MutatingPrimitiveIterable(intArrayOf(1))
    println(intArrayOf().zip(zipEmpty))
    println(zipEmpty.pulls)
    run {
        println("Int")
        val a = intArrayOf(3, 1, 2, 1)
        println(a.drop(1))
        println(a.dropLast(1))
        println(a.take(2))
        println(a.takeLast(2))
        println(a.slice(1..2))
        println(a.slice(listOf(2, 0, 2)))
        println(a.elementAtOrNull(9))
        println(a.elementAtOrNull(1))
        println(a.getOrElse(-1) { a[0] })
        println(a.foldRight("end") { v, acc -> "$v:$acc" })
        println(a.reduceRight { v, acc -> v })
        println(a.mapTo(mutableListOf<String>("seed")) { it.toString() })
        println(a.filterTo(mutableListOf()) { it == a[0] })
        println(a.toCollection(mutableListOf()))
        println(a.toHashSet().size)
        println(a.toMutableSet())
        println(a.sortedBy { if (it == a[0]) null else it })
        println(a.sortedWith(compareBy { it.toString() }))
        println(a.partition { it == a[0] })
        println(a.groupBy { it == a[0] })
        println(a.groupBy({ it == a[0] }, { it.toString() }))
        println(a.associate { it.toString() to it })
        println(a.associateBy { it.toString() })
        println(a.associateBy({ it.toString() }, { it == a[0] }))
        println(a.zip(a))
        println(a.zip(arrayOf("x", "y")))
        println(a.zip(listOf("x", "y")))
        println(a.zip(a) { x, y -> "$x:$y" })
        println(a.zip(arrayOf("x", "y")) { x, y -> "$x:$y" })
        println(a.zip(listOf("x", "y")) { x, y -> "$x:$y" })
        println(a.indexOf(a[1]))
        println(a.lastIndexOf(a[1]))
        println(a.max())
        println(a.min())
        println(a.maxOrNull())
        println(a.minOrNull())
        println(a.copyOf(0).minOrNull())
        println(a.copyOf(0).maxOrNull())
        println(a.average())
        println(a.copyOf(0).average().isNaN())
        a.forEachIndexed { i, v -> println("$i:$v") }
        a.fill(a[1], 1, 3)
        println(a.toList())
        a.fill(a[0], fromIndex = 0, toIndex = 0)
        a.fill(a[1])
        println(a.toList())
    }
    run {
        println("Long")
        val a = longArrayOf(3L, 1L, 2L, 1L)
        println(a.drop(1))
        println(a.dropLast(1))
        println(a.take(2))
        println(a.takeLast(2))
        println(a.slice(1..2))
        println(a.slice(listOf(2, 0, 2)))
        println(a.elementAtOrNull(9))
        println(a.elementAtOrNull(1))
        println(a.getOrElse(-1) { a[0] })
        println(a.foldRight("end") { v, acc -> "$v:$acc" })
        println(a.reduceRight { v, acc -> v })
        println(a.mapTo(mutableListOf<String>("seed")) { it.toString() })
        println(a.filterTo(mutableListOf()) { it == a[0] })
        println(a.toCollection(mutableListOf()))
        println(a.toHashSet().size)
        println(a.toMutableSet())
        println(a.sortedBy { if (it == a[0]) null else it })
        println(a.sortedWith(compareBy { it.toString() }))
        println(a.partition { it == a[0] })
        println(a.groupBy { it == a[0] })
        println(a.groupBy({ it == a[0] }, { it.toString() }))
        println(a.associate { it.toString() to it })
        println(a.associateBy { it.toString() })
        println(a.associateBy({ it.toString() }, { it == a[0] }))
        println(a.zip(a))
        println(a.zip(arrayOf("x", "y")))
        println(a.zip(listOf("x", "y")))
        println(a.zip(a) { x, y -> "$x:$y" })
        println(a.zip(arrayOf("x", "y")) { x, y -> "$x:$y" })
        println(a.zip(listOf("x", "y")) { x, y -> "$x:$y" })
        println(a.indexOf(a[1]))
        println(a.lastIndexOf(a[1]))
        println(a.max())
        println(a.min())
        println(a.maxOrNull())
        println(a.minOrNull())
        println(a.copyOf(0).minOrNull())
        println(a.copyOf(0).maxOrNull())
        println(a.average())
        println(a.copyOf(0).average().isNaN())
        a.forEachIndexed { i, v -> println("$i:$v") }
        a.fill(a[1], 1, 3)
        println(a.toList())
        a.fill(a[0], fromIndex = 0, toIndex = 0)
        a.fill(a[1])
        println(a.toList())
    }
    run {
        println("Byte")
        val a = byteArrayOf(3, 1, 2, 1)
        println(a.drop(1))
        println(a.dropLast(1))
        println(a.take(2))
        println(a.takeLast(2))
        println(a.slice(1..2))
        println(a.slice(listOf(2, 0, 2)))
        println(a.elementAtOrNull(9))
        println(a.elementAtOrNull(1))
        println(a.getOrElse(-1) { a[0] })
        println(a.foldRight("end") { v, acc -> "$v:$acc" })
        println(a.reduceRight { v, acc -> v })
        println(a.mapTo(mutableListOf<String>("seed")) { it.toString() })
        println(a.filterTo(mutableListOf()) { it == a[0] })
        println(a.toCollection(mutableListOf()))
        println(a.toHashSet().size)
        println(a.toMutableSet())
        println(a.sortedBy { if (it == a[0]) null else it })
        println(a.sortedWith(compareBy { it.toString() }))
        println(a.partition { it == a[0] })
        println(a.groupBy { it == a[0] })
        println(a.groupBy({ it == a[0] }, { it.toString() }))
        println(a.associate { it.toString() to it })
        println(a.associateBy { it.toString() })
        println(a.associateBy({ it.toString() }, { it == a[0] }))
        println(a.zip(a))
        println(a.zip(arrayOf("x", "y")))
        println(a.zip(listOf("x", "y")))
        println(a.zip(a) { x, y -> "$x:$y" })
        println(a.zip(arrayOf("x", "y")) { x, y -> "$x:$y" })
        println(a.zip(listOf("x", "y")) { x, y -> "$x:$y" })
        println(a.indexOf(a[1]))
        println(a.lastIndexOf(a[1]))
        println(a.max())
        println(a.min())
        println(a.maxOrNull())
        println(a.minOrNull())
        println(a.copyOf(0).minOrNull())
        println(a.copyOf(0).maxOrNull())
        println(a.average())
        println(a.copyOf(0).average().isNaN())
        a.forEachIndexed { i, v -> println("$i:$v") }
        a.fill(a[1], 1, 3)
        println(a.toList())
        a.fill(a[0], fromIndex = 0, toIndex = 0)
        a.fill(a[1])
        println(a.toList())
    }
    run {
        println("Short")
        val a = shortArrayOf(3, 1, 2, 1)
        println(a.drop(1))
        println(a.dropLast(1))
        println(a.take(2))
        println(a.takeLast(2))
        println(a.slice(1..2))
        println(a.slice(listOf(2, 0, 2)))
        println(a.elementAtOrNull(9))
        println(a.elementAtOrNull(1))
        println(a.getOrElse(-1) { a[0] })
        println(a.foldRight("end") { v, acc -> "$v:$acc" })
        println(a.reduceRight { v, acc -> v })
        println(a.mapTo(mutableListOf<String>("seed")) { it.toString() })
        println(a.filterTo(mutableListOf()) { it == a[0] })
        println(a.toCollection(mutableListOf()))
        println(a.toHashSet().size)
        println(a.toMutableSet())
        println(a.sortedBy { if (it == a[0]) null else it })
        println(a.sortedWith(compareBy { it.toString() }))
        println(a.partition { it == a[0] })
        println(a.groupBy { it == a[0] })
        println(a.groupBy({ it == a[0] }, { it.toString() }))
        println(a.associate { it.toString() to it })
        println(a.associateBy { it.toString() })
        println(a.associateBy({ it.toString() }, { it == a[0] }))
        println(a.zip(a))
        println(a.zip(arrayOf("x", "y")))
        println(a.zip(listOf("x", "y")))
        println(a.zip(a) { x, y -> "$x:$y" })
        println(a.zip(arrayOf("x", "y")) { x, y -> "$x:$y" })
        println(a.zip(listOf("x", "y")) { x, y -> "$x:$y" })
        println(a.indexOf(a[1]))
        println(a.lastIndexOf(a[1]))
        println(a.max())
        println(a.min())
        println(a.maxOrNull())
        println(a.minOrNull())
        println(a.copyOf(0).minOrNull())
        println(a.copyOf(0).maxOrNull())
        println(a.average())
        println(a.copyOf(0).average().isNaN())
        a.forEachIndexed { i, v -> println("$i:$v") }
        a.fill(a[1], 1, 3)
        println(a.toList())
        a.fill(a[0], fromIndex = 0, toIndex = 0)
        a.fill(a[1])
        println(a.toList())
    }
    run {
        println("Char")
        val a = charArrayOf('c', 'a', 'b', 'a')
        println(a.drop(1))
        println(a.dropLast(1))
        println(a.take(2))
        println(a.takeLast(2))
        println(a.slice(1..2))
        println(a.slice(listOf(2, 0, 2)))
        println(a.elementAtOrNull(9))
        println(a.elementAtOrNull(1))
        println(a.getOrElse(-1) { a[0] })
        println(a.foldRight("end") { v, acc -> "$v:$acc" })
        println(a.reduceRight { v, acc -> v })
        println(a.mapTo(mutableListOf<String>("seed")) { it.toString() })
        println(a.filterTo(mutableListOf()) { it == a[0] })
        println(a.toCollection(mutableListOf()))
        println(a.toHashSet().size)
        println(a.toMutableSet())
        println(a.sortedBy { if (it == a[0]) null else it })
        println(a.sortedWith(compareBy { it.toString() }))
        println(a.partition { it == a[0] })
        println(a.groupBy { it == a[0] })
        println(a.groupBy({ it == a[0] }, { it.toString() }))
        println(a.associate { it.toString() to it })
        println(a.associateBy { it.toString() })
        println(a.associateBy({ it.toString() }, { it == a[0] }))
        println(a.zip(a))
        println(a.zip(arrayOf("x", "y")))
        println(a.zip(listOf("x", "y")))
        println(a.zip(a) { x, y -> "$x:$y" })
        println(a.zip(arrayOf("x", "y")) { x, y -> "$x:$y" })
        println(a.zip(listOf("x", "y")) { x, y -> "$x:$y" })
        println(a.indexOf(a[1]))
        println(a.lastIndexOf(a[1]))
        println(a.max())
        println(a.min())
        println(a.maxOrNull())
        println(a.minOrNull())
        println(a.copyOf(0).minOrNull())
        println(a.copyOf(0).maxOrNull())
        a.forEachIndexed { i, v -> println("$i:$v") }
        a.fill(a[1], 1, 3)
        println(a.toList())
        a.fill(a[0], fromIndex = 0, toIndex = 0)
        a.fill(a[1])
        println(a.toList())
    }
    run {
        println("Boolean")
        val a = booleanArrayOf(true, false, true, false)
        println(a.drop(1))
        println(a.dropLast(1))
        println(a.take(2))
        println(a.takeLast(2))
        println(a.slice(1..2))
        println(a.slice(listOf(2, 0, 2)))
        println(a.elementAtOrNull(9))
        println(a.elementAtOrNull(1))
        println(a.getOrElse(-1) { a[0] })
        println(a.foldRight("end") { v, acc -> "$v:$acc" })
        println(a.reduceRight { v, acc -> v })
        println(a.mapTo(mutableListOf<String>("seed")) { it.toString() })
        println(a.filterTo(mutableListOf()) { it == a[0] })
        println(a.toCollection(mutableListOf()))
        println(a.toHashSet().size)
        println(a.toMutableSet())
        println(a.sortedBy { if (it == a[0]) null else it })
        println(a.sortedWith(compareBy { it.toString() }))
        println(a.partition { it == a[0] })
        println(a.groupBy { it == a[0] })
        println(a.groupBy({ it == a[0] }, { it.toString() }))
        println(a.associate { it.toString() to it })
        println(a.associateBy { it.toString() })
        println(a.associateBy({ it.toString() }, { it == a[0] }))
        println(a.zip(a))
        println(a.zip(arrayOf("x", "y")))
        println(a.zip(listOf("x", "y")))
        println(a.zip(a) { x, y -> "$x:$y" })
        println(a.zip(arrayOf("x", "y")) { x, y -> "$x:$y" })
        println(a.zip(listOf("x", "y")) { x, y -> "$x:$y" })
        println(a.indexOf(a[1]))
        println(a.lastIndexOf(a[1]))
        a.forEachIndexed { i, v -> println("$i:$v") }
        a.fill(a[1], 1, 3)
        println(a.toList())
        a.fill(a[0], fromIndex = 0, toIndex = 0)
        a.fill(a[1])
        println(a.toList())
    }
    run {
        println("Float")
        val a = floatArrayOf(3.0f, 1.0f, 2.0f, 1.0f)
        println(a.drop(1))
        println(a.dropLast(1))
        println(a.take(2))
        println(a.takeLast(2))
        println(a.slice(1..2))
        println(a.slice(listOf(2, 0, 2)))
        println(a.elementAtOrNull(9))
        println(a.elementAtOrNull(1))
        println(a.getOrElse(-1) { a[0] })
        println(a.foldRight("end") { v, acc -> "$v:$acc" })
        println(a.reduceRight { v, acc -> v })
        println(a.mapTo(mutableListOf<String>("seed")) { it.toString() })
        println(a.filterTo(mutableListOf()) { it == a[0] })
        println(a.toCollection(mutableListOf()))
        println(a.toHashSet().size)
        println(a.toMutableSet())
        println(a.sortedBy { if (it == a[0]) null else it })
        println(a.sortedWith(compareBy { it.toString() }))
        println(a.partition { it == a[0] })
        println(a.groupBy { it == a[0] })
        println(a.groupBy({ it == a[0] }, { it.toString() }))
        println(a.associate { it.toString() to it })
        println(a.associateBy { it.toString() })
        println(a.associateBy({ it.toString() }, { it == a[0] }))
        println(a.zip(a))
        println(a.zip(arrayOf("x", "y")))
        println(a.zip(listOf("x", "y")))
        println(a.zip(a) { x, y -> "$x:$y" })
        println(a.zip(arrayOf("x", "y")) { x, y -> "$x:$y" })
        println(a.zip(listOf("x", "y")) { x, y -> "$x:$y" })
        println(a.max())
        println(a.min())
        println(a.maxOrNull())
        println(a.minOrNull())
        println(a.copyOf(0).minOrNull())
        println(a.copyOf(0).maxOrNull())
        println(a.average())
        println(a.copyOf(0).average().isNaN())
        a.forEachIndexed { i, v -> println("$i:$v") }
        a.fill(a[1], 1, 3)
        println(a.toList())
        a.fill(a[0], fromIndex = 0, toIndex = 0)
        a.fill(a[1])
        println(a.toList())
    }
    run {
        println("Double")
        val a = doubleArrayOf(3.0, 1.0, 2.0, 1.0)
        println(a.drop(1))
        println(a.dropLast(1))
        println(a.take(2))
        println(a.takeLast(2))
        println(a.slice(1..2))
        println(a.slice(listOf(2, 0, 2)))
        println(a.elementAtOrNull(9))
        println(a.elementAtOrNull(1))
        println(a.getOrElse(-1) { a[0] })
        println(a.foldRight("end") { v, acc -> "$v:$acc" })
        println(a.reduceRight { v, acc -> v })
        println(a.mapTo(mutableListOf<String>("seed")) { it.toString() })
        println(a.filterTo(mutableListOf()) { it == a[0] })
        println(a.toCollection(mutableListOf()))
        println(a.toHashSet().size)
        println(a.toMutableSet())
        println(a.sortedBy { if (it == a[0]) null else it })
        println(a.sortedWith(compareBy { it.toString() }))
        println(a.partition { it == a[0] })
        println(a.groupBy { it == a[0] })
        println(a.groupBy({ it == a[0] }, { it.toString() }))
        println(a.associate { it.toString() to it })
        println(a.associateBy { it.toString() })
        println(a.associateBy({ it.toString() }, { it == a[0] }))
        println(a.zip(a))
        println(a.zip(arrayOf("x", "y")))
        println(a.zip(listOf("x", "y")))
        println(a.zip(a) { x, y -> "$x:$y" })
        println(a.zip(arrayOf("x", "y")) { x, y -> "$x:$y" })
        println(a.zip(listOf("x", "y")) { x, y -> "$x:$y" })
        println(a.max())
        println(a.min())
        println(a.maxOrNull())
        println(a.minOrNull())
        println(a.copyOf(0).minOrNull())
        println(a.copyOf(0).maxOrNull())
        println(a.average())
        println(a.copyOf(0).average().isNaN())
        a.forEachIndexed { i, v -> println("$i:$v") }
        a.fill(a[1], 1, 3)
        println(a.toList())
        a.fill(a[0], fromIndex = 0, toIndex = 0)
        a.fill(a[1])
        println(a.toList())
    }
    val empty = intArrayOf()
    println(empty.take(3))
    println(empty.drop(3))
    println(empty.slice(2..1))
    try { empty.reduceRight { x, y -> x + y } } catch (e: UnsupportedOperationException) { println("empty reduce") }
    try { empty.min() } catch (e: NoSuchElementException) { println("empty min") }
    try { empty.max() } catch (e: NoSuchElementException) { println("empty max") }
    try { empty.take(-1) } catch (e: IllegalArgumentException) { println("negative take") }
    try { empty.drop(-1) } catch (e: IllegalArgumentException) { println("negative drop") }
    try { empty.fill(1, 1, 0) } catch (e: IllegalArgumentException) { println("fill order") }
    try { empty.fill(1, -1, 0) } catch (e: ArrayIndexOutOfBoundsException) { println("fill lower:${e.message}") }
    try { empty.fill(1, 0, 1) } catch (e: ArrayIndexOutOfBoundsException) { println("fill upper:${e.message}") }
    println(intArrayOf(1, 2, 3).reduceRight { x, y -> x - y })
    val live = intArrayOf(1, 2)
    println(live.mapTo(mutableListOf<Int>()) { live[1] = 9; it })
    val destination = mutableListOf<Any>("seed")
    println(intArrayOf(1, 2).toCollection(destination) === destination)
    println(destination)
    println(doubleArrayOf(1.0, Double.NaN, 2.0).min().isNaN())
    println(doubleArrayOf(1.0, Double.NaN, 2.0).maxOrNull()!!.isNaN())
    println(1.0 / doubleArrayOf(0.0, -0.0).min())
    println(1.0 / doubleArrayOf(-0.0, 0.0).max())
    println(floatArrayOf(1.0f, Float.NaN, 2.0f).minOrNull()!!.isNaN())
    println(floatArrayOf(1.0f, Float.NaN, 2.0f).max().isNaN())
    println(1.0f / floatArrayOf(0.0f, -0.0f).min())
    println(1.0f / floatArrayOf(-0.0f, 0.0f).max())
    val (left, right) = intArrayOf(1, 2).zip(listOf("a", "b")).unzip()
    println(left)
    println(right)
}
