fun main() {
    val s = setOf(3, 1, 4, 1, 5)
    val t = setOf(4, 5, 6)
    println(s.map { it * 2 })
    println(s.filter { it > 2 })
    println(s.filterNot { it > 2 })
    println(s.mapNotNull { if (it > 2) it else null })
    println(s.flatMap { listOf(it, it) })
    s.forEach { print("$it ") }
    println()
    println(s.count { it > 2 })
    println(s.any { it > 4 })
    println(s.all { it > 0 })
    println(s.none { it > 9 })
    println(s.any())
    println(s.none())
    println(setOf<Int>().any())
    println(setOf<Int>().none())
    println(s.first())
    println(s.firstOrNull())
    println(s.last())
    println(s.lastOrNull())
    println(s.singleOrNull())
    println(setOf(9).singleOrNull())
    println(s.containsAll(listOf(1, 3)))
    println(s.isEmpty())
    println(s.intersect(t))
    println(s.union(t))
    println(s.subtract(t))
    println(s.sorted())
    println(s.sortedDescending())
    println(s.maxOrNull())
    println(s.minOrNull())
    println(s.toList())
    println(s.toMutableList())
    println(s.toSet())
    println(s.toMutableSet())
    println(s.size)
    println(s.contains(4))
    println(s.toString())
}
