// KUU-542: Set/Collection receivers must resolve the bundled Iterable<T>
// extrema and sorting declarations. Before the fix, Sema left them unbound
// and CallLowerer emitted spec-only kk_list_* bridges that failed at link
// time with `Undefined symbols: _kk_list_maxByOrNull` (and ~19 more names).
fun main() {
    val s = setOf(3, 1, 4, 1, 5)
    println(s.max())
    println(s.min())
    println(s.maxOrNull())
    println(s.minOrNull())
    println(s.maxBy { it })
    println(s.minBy { it })
    println(s.maxByOrNull { it })
    println(s.minByOrNull { it })
    println(s.maxOf { it * 2 })
    println(s.minOf { it * 2 })
    println(s.maxOfOrNull { it * 2 })
    println(s.minOfOrNull { it * 2 })
    println(s.minOfOrNull { it * 1.5 })
    println(s.maxOfOrNull { it * 1.5 })
    println(s.maxWith(naturalOrder()))
    println(s.minWith(naturalOrder()))
    println(s.maxWithOrNull(naturalOrder()))
    println(s.minWithOrNull(naturalOrder()))
    println(s.maxOfWith(naturalOrder()) { it })
    println(s.minOfWith(naturalOrder()) { it })
    println(s.maxOfWithOrNull(naturalOrder()) { it })
    println(s.minOfWithOrNull(naturalOrder()) { it })
    println(s.sortedBy { -it })
    println(s.sortedByDescending { it })
    println(s.sortedWith(naturalOrder()))
    println(s.sortedWith { a, b -> a - b })

    val doubles = setOf(1.5, 3.5, 0.5)
    println(doubles.min())
    println(doubles.max())
    println(doubles.minOrNull())
    println(doubles.maxOrNull())

    val c: Collection<Int> = s
    println(c.min())
    println(c.minOrNull())
    println(c.minBy { it })
    println(c.minByOrNull { it })
    println(c.minOf { it })
    println(c.minOfOrNull { it })
    println(c.minWith(naturalOrder()))
    println(c.minWithOrNull(naturalOrder()))
    println(c.minOfWith(naturalOrder()) { it })
    println(c.minOfWithOrNull(naturalOrder()) { it })
    println(c.max())
    println(c.maxByOrNull { it })
    println(c.sortedByDescending { it })
    println(c.sortedWith(naturalOrder()))

    val ms: MutableSet<Int> = mutableSetOf(3, 1, 2)
    println(ms.maxByOrNull { it })
    println(ms.minByOrNull { it })
    println(ms.min())
    println(ms.sortedByDescending { it })
}
