fun main() {
    val map = HashMap<String, Int?>()
    println(map.isEmpty())
    println(map.size)
    println(map.put("a", 1))
    println(map.put("b", null))
    println(map.size)
    println(map.containsKey("b"))
    println(map.containsValue(null))
    println(map.containsValue(1))
    println(map["a"])
    println(map.remove("a"))
    println(map.remove("missing"))
    map.put("n", 1)
    println(map.keys.toList().joinToString(","))
    println(map.values.toList().joinToString(","))
    println(map.entries.toList().joinToString(";") { "${it.key}=${it.value}" })

    val copy = HashMap(map)
    println(map == copy)
    println(copy == map)
    println(map.hashCode() == copy.hashCode())
    println(map is Map<*, *>)
    println(map is MutableMap<*, *>)
    println(map.toString())

    val additional = HashMap<String, Int?>()
    additional.put("c", 3)
    map.putAll(additional)
    println(map.size)
    map.clear()
    println(map.isEmpty())
}
