fun main() {
    println("  hello  ".trim())
    println("1,2,3".split(","))
    println("42".toInt())

    println("banana".replace("na", "NA"))
    println(if ("Kotlin".startsWith("Ko")) "true" else "false")
    println(if ("Kotlin".endsWith("in")) "true" else "false")
    println(if ("Kotlin".contains("otl")) "true" else "false")

    println(" 3.14 ".toDouble())
    println("%s:%d".format("age", 7))
    println("%.2f".format(3.5))
    println("progress=100%%".format())
    println("hello".substring(1))
    println("hello".substring(1, 3))
    println("Hello".lowercase())
    println("Hello".uppercase())
    println("123".toIntOrNull())
    println("abc".toIntOrNull())
    println(" 3.14 ".toDoubleOrNull())
    println("abc".toDoubleOrNull())
    println("abcabc".indexOf("bc"))
    println("abcabc".lastIndexOf("bc"))
    println("abc".reversed())
    println("abc".toList())
    println("abc".toCharArray()[0])
    println("abcde".take(3))
    println("abcde".drop(2))
    println("abcde".takeLast(2))
    println("abcde".dropLast(2))
    println("42".padStart(5, '0'))
    println("42".padEnd(5, '0'))
    println("ab".repeat(3))

    // Edge cases for the same APIs
    println("".trim())
    println("   ".trim())
    println("hello world".startsWith("hello"))
    println("hello world".endsWith("world"))
    println("hello world".startsWith("world"))
    println("hello world".endsWith("hello"))
    println("hello world".contains("lo wo"))
    println("hello world".contains("xyz"))
    println("hello world".contains(""))
    println("hello world".replace("world", "kotlin"))
    println("aaa".replace("a", "bb"))
    println("ababa".replace("aba", "x"))
    println("-123".toInt())
    println("0".toInt())
    println("-0.5".toDouble())
    println("42.0".toDouble())
}
