fun main() {
    // KUU-1065: explicit capacity and ensureCapacity must reserve real storage.
    println(StringBuilder(100).capacity())
    val reserved = StringBuilder()
    reserved.ensureCapacity(200)
    println(reserved.capacity())
    println(reserved.length)

    println(StringBuilder().capacity())
    println(StringBuilder(0).capacity())
    println(StringBuilder(1).capacity())
    println(StringBuilder("abc").capacity())
    println(StringBuilder("a😀b").capacity())
    val sequence: CharSequence = StringBuilder("a😀b")
    println(StringBuilder(sequence).capacity())

    try {
        StringBuilder(-1)
        println("negative-missed")
    } catch (_: NegativeArraySizeException) {
        println("negative-caught")
    }

    reserved.append("abc")
    reserved.ensureCapacity(-1)
    reserved.ensureCapacity(0)
    reserved.ensureCapacity(100)
    reserved.ensureCapacity(200)
    println(reserved.capacity())
    println(reserved.toString())
    reserved.clear()
    println(reserved.capacity())
    println(reserved.length)

    val grown = StringBuilder()
    grown.ensureCapacity(17)
    println(grown.capacity())
    grown.append("abcdefghijklmnopqrst")
    println(grown.capacity())
    grown.delete(0, 19)
    println(grown.capacity())
    grown.trimToSize()
    println(grown.capacity())
    println(grown.toString())
    grown.append('x')
    println(grown.capacity())
    grown.clear()
    grown.trimToSize()
    println(grown.capacity())
    grown.append('a')
    println(grown.capacity())

    val appended = StringBuilder()
    appended.append("abcdefghijklmnopqrst")
    println(appended.capacity())

    val chars = StringBuilder(1)
    chars.append(charArrayOf('a', 'b', 'c'))
    println(chars.capacity())
    chars.insert(1, charArrayOf('x', 'y', 'z'))
    println(chars.capacity())
    println(chars.toString())

    val ranged = StringBuilder(0)
    ranged.appendRange("abcdef", 1, 5)
    println(ranged.capacity())
    ranged.insert(2, "12345")
    println(ranged.capacity())
    println(ranged.toString())

    val self = StringBuilder(2).append("ab")
    self.insert(1, self)
    println(self.capacity())
    println(self.toString())

    val resized = StringBuilder(2).append("ab")
    resized.setLength(20)
    println(resized.capacity())
    println(resized.length)
    resized.setLength(1)
    println(resized.capacity())
    println(resized.toString())
    resized.trimToSize()
    println(resized.capacity())

    val replaced = StringBuilder(4).append("abcd")
    replaced.replace(1, 3, "0123456789")
    println(replaced.capacity())
    println(replaced.toString())
    replaced.deleteCharAt(0)
    replaced.reverse()
    println(replaced.capacity())
    println(replaced.toString())

    println(buildString(100) {
        println(capacity())
        ensureCapacity(200)
        println(capacity())
        append("ok")
    })
}
