/*
 * Copyright 2010-2021 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Licensed under the Apache License, Version 2.0.
 * Derived from JetBrains/kotlin revision 150f34458460c5d688ba80e13f269ca6715f32b4.
 * Stable APIs follow Kotlin 2.3.10; experimental lazy messages retain their 2.4 version marker.
 */
@file:Suppress("INVISIBLE_MEMBER", "INVISIBLE_REFERENCE")
@file:OptIn(kotlin.contracts.ExperimentalContracts::class, kotlin.ExperimentalUnsignedTypes::class)
package kotlin.test



/** Asserts that the difference between the [actual] and the [expected] is within an [absoluteTolerance], with an optional [message]. */
@SinceKotlin("1.5")
public fun assertEquals(expected: Double, actual: Double, absoluteTolerance: Double, message: String? = null) {
    checkDoublesAreEqual(expected, actual, absoluteTolerance, message)
}

/**
 * Asserts that the difference between the [actual] and the [expected] is within an [absoluteTolerance],
 * with an error message generated by the [lazyMessage] lambda otherwise.
 */
@SinceKotlin("2.4")
@ExperimentalKotlinTestApi
public fun assertEquals(expected: Double, actual: Double, absoluteTolerance: Double, lazyMessage: () -> String) {
    checkDoublesAreEqual(expected, actual, absoluteTolerance, lazyMessage)
}

/** Asserts that the difference between the [actual] and the [expected] is within an [absoluteTolerance], with an optional [message]. */
@SinceKotlin("1.5")
public fun assertEquals(expected: Float, actual: Float, absoluteTolerance: Float, message: String? = null) {
    checkFloatsAreEqual(expected, actual, absoluteTolerance, message)
}

/**
 * Asserts that the difference between the [actual] and the [expected] is within an [absoluteTolerance],
 * with an error message generated by the [lazyMessage] lambda otherwise.
 */
@SinceKotlin("2.4")
@ExperimentalKotlinTestApi
public fun assertEquals(expected: Float, actual: Float, absoluteTolerance: Float, lazyMessage: () -> String) {
    checkFloatsAreEqual(expected, actual, absoluteTolerance, lazyMessage)
}


/** Asserts that the difference between the [actual] and the [illegal] is not within an [absoluteTolerance], with an optional [message]. */
@SinceKotlin("1.5")
public fun assertNotEquals(illegal: Double, actual: Double, absoluteTolerance: Double, message: String? = null) {
    checkDoublesAreEqual(illegal, actual, absoluteTolerance, message, shouldFail = true)
}

/**
 * Asserts that the difference between the [actual] and the [illegal] is not within an [absoluteTolerance],
 * with an error message generated by the [lazyMessage] lambda otherwise.
 */
@SinceKotlin("2.4")
@ExperimentalKotlinTestApi
public fun assertNotEquals(illegal: Double, actual: Double, absoluteTolerance: Double, lazyMessage: () -> String) {
    checkDoublesAreEqual(illegal, actual, absoluteTolerance, lazyMessage, shouldFail = true)
}

/** Asserts that the difference between the [actual] and the [illegal] is not within an [absoluteTolerance], with an optional [message]. */
@SinceKotlin("1.5")
public fun assertNotEquals(illegal: Float, actual: Float, absoluteTolerance: Float, message: String? = null) {
    checkFloatsAreEqual(illegal, actual, absoluteTolerance, message, shouldFail = true)
}

/**
 * Asserts that the difference between the [actual] and the [illegal] is not within an [absoluteTolerance],
 * with an error message generated by the [lazyMessage] lambda otherwise.
 */
@SinceKotlin("2.4")
@ExperimentalKotlinTestApi
public fun assertNotEquals(illegal: Float, actual: Float, absoluteTolerance: Float, lazyMessage: () -> String) {
    checkFloatsAreEqual(illegal, actual, absoluteTolerance, lazyMessage, shouldFail = true)
}
