/*
 * Copyright 2010-2021 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Licensed under the Apache License, Version 2.0.
 * Derived from JetBrains/kotlin revision 150f34458460c5d688ba80e13f269ca6715f32b4.
 * Stable APIs follow Kotlin 2.3.10; experimental lazy messages retain their 2.4 version marker.
 */
@file:Suppress("INVISIBLE_MEMBER", "INVISIBLE_REFERENCE")
@file:OptIn(kotlin.contracts.ExperimentalContracts::class, kotlin.ExperimentalUnsignedTypes::class)
package kotlin.test

import kotlin.internal.OnlyInputTypes

/** Asserts that the [iterable] contains the specified [element], with an optional [message]. */
@SinceKotlin("1.5")
public fun <@OnlyInputTypes T> assertContains(iterable: Iterable<T>, element: T, message: String? = null) {
    assertContainsImpl(iterable, element) { message }
}

/**
 * Asserts that the [iterable] contains the specified [element],
 * with an error message generated by the [lazyMessage] lambda otherwise.
 */
@SinceKotlin("2.4")
@ExperimentalKotlinTestApi
public fun <@OnlyInputTypes T> assertContains(iterable: Iterable<T>, element: T, lazyMessage: () -> String) {
    assertContainsImpl(iterable, element, lazyMessage)
}

private fun <@OnlyInputTypes T> assertContainsImpl(iterable: Iterable<T>, element: T, lazyMessage: () -> String?) {
    asserter.assertTrue(
        { messagePrefix(lazyMessage()) + "Expected the collection to contain the element.\nCollection <$iterable>, element <$element>." },
        iterable.contains(element)
    )
}

/** Asserts that the [sequence] contains the specified [element], with an optional [message]. */
@SinceKotlin("1.5")
public fun <@OnlyInputTypes T> assertContains(sequence: Sequence<T>, element: T, message: String? = null) {
    assertContainsImpl(sequence, element) { message }
}

/**
 * Asserts that the [sequence] contains the specified [element],
 * with an error message generated by the [lazyMessage] lambda otherwise.
 */
@SinceKotlin("2.4")
@ExperimentalKotlinTestApi
public fun <@OnlyInputTypes T> assertContains(sequence: Sequence<T>, element: T, lazyMessage: () -> String) {
    assertContainsImpl(sequence, element, lazyMessage)
}

private fun <@OnlyInputTypes T> assertContainsImpl(sequence: Sequence<T>, element: T, lazyMessage: () -> String?) {
    asserter.assertTrue(
        { messagePrefix(lazyMessage()) + "Expected the sequence to contain the element.\nSequence <$sequence>, element <$element>." },
        sequence.contains(element)
    )
}

/** Asserts that the [array] contains the specified [element], with an optional [message]. */
@SinceKotlin("1.5")
public fun <@OnlyInputTypes T> assertContains(array: Array<T>, element: T, message: String? = null) {
    assertArrayContains(array, element, { message }, Array<T>::contains, Array<T>::contentToString)
}

/**
 * Asserts that the [array] contains the specified [element],
 * with an error message generated by the [lazyMessage] lambda otherwise.
 */
@SinceKotlin("2.4")
@ExperimentalKotlinTestApi
public fun <@OnlyInputTypes T> assertContains(array: Array<T>, element: T, lazyMessage: () -> String) {
    assertArrayContains(array, element, lazyMessage, Array<T>::contains, Array<T>::contentToString)
}

/** Asserts that the [array] contains the specified [element], with an optional [message]. */
@SinceKotlin("1.5")
public fun assertContains(array: ByteArray, element: Byte, message: String? = null) {
    assertArrayContains(array, element, { message }, ByteArray::contains, ByteArray::contentToString)
}

/**
 * Asserts that the [array] contains the specified [element],
 * with an error message generated by the [lazyMessage] lambda otherwise.
 */
@SinceKotlin("2.4")
@ExperimentalKotlinTestApi
public fun assertContains(array: ByteArray, element: Byte, lazyMessage: () -> String) {
    assertArrayContains(array, element, lazyMessage, ByteArray::contains, ByteArray::contentToString)
}

/** Asserts that the [array] contains the specified [element], with an optional [message]. */
@SinceKotlin("1.5")
public fun assertContains(array: ShortArray, element: Short, message: String? = null) {
    assertArrayContains(array, element, { message }, ShortArray::contains, ShortArray::contentToString)
}

/**
 * Asserts that the [array] contains the specified [element],
 * with an error message generated by the [lazyMessage] lambda otherwise.
 */
@SinceKotlin("2.4")
@ExperimentalKotlinTestApi
public fun assertContains(array: ShortArray, element: Short, lazyMessage: () -> String) {
    assertArrayContains(array, element, lazyMessage, ShortArray::contains, ShortArray::contentToString)
}


/** Asserts that the [array] contains the specified [element], with an optional [message]. */
@SinceKotlin("1.5")
public fun assertContains(array: IntArray, element: Int, message: String? = null) {
    assertArrayContains(array, element, { message }, IntArray::contains, IntArray::contentToString)
}

/**
 * Asserts that the [array] contains the specified [element],
 * with an error message generated by the [lazyMessage] lambda otherwise.
 */
@SinceKotlin("2.4")
@ExperimentalKotlinTestApi
public fun assertContains(array: IntArray, element: Int, lazyMessage: () -> String) {
    assertArrayContains(array, element, lazyMessage, IntArray::contains, IntArray::contentToString)
}

/** Asserts that the [array] contains the specified [element], with an optional [message]. */
@SinceKotlin("1.5")
public fun assertContains(array: LongArray, element: Long, message: String? = null) {
    assertArrayContains(array, element, { message }, LongArray::contains, LongArray::contentToString)
}

/**
 * Asserts that the [array] contains the specified [element],
 * with an error message generated by the [lazyMessage] lambda otherwise.
 */
@SinceKotlin("2.4")
@ExperimentalKotlinTestApi
public fun assertContains(array: LongArray, element: Long, lazyMessage: () -> String) {
    assertArrayContains(array, element, lazyMessage, LongArray::contains, LongArray::contentToString)
}


/** Asserts that the [array] contains the specified [element], with an optional [message]. */
@SinceKotlin("1.5")
public fun assertContains(array: BooleanArray, element: Boolean, message: String? = null) {
    assertArrayContains(array, element, { message }, BooleanArray::contains, BooleanArray::contentToString)
}

/**
 * Asserts that the [array] contains the specified [element],
 * with an error message generated by the [lazyMessage] lambda otherwise.
 */
@SinceKotlin("2.4")
@ExperimentalKotlinTestApi
public fun assertContains(array: BooleanArray, element: Boolean, lazyMessage: () -> String) {
    assertArrayContains(array, element, lazyMessage, BooleanArray::contains, BooleanArray::contentToString)
}


/** Asserts that the [array] contains the specified [element], with an optional [message]. */
@SinceKotlin("1.5")
public fun assertContains(array: CharArray, element: Char, message: String? = null) {
    assertArrayContains(array, element, { message }, CharArray::contains, CharArray::contentToString)
}

/**
 * Asserts that the [array] contains the specified [element],
 * with an error message generated by the [lazyMessage] lambda otherwise.
 */
@SinceKotlin("2.4")
@ExperimentalKotlinTestApi
public fun assertContains(array: CharArray, element: Char, lazyMessage: () -> String) {
    assertArrayContains(array, element, lazyMessage, CharArray::contains, CharArray::contentToString)
}


/** Asserts that the [array] contains the specified [element], with an optional [message]. */
@SinceKotlin("1.5")
@OptIn(ExperimentalUnsignedTypes::class)
public fun assertContains(array: UByteArray, element: UByte, message: String? = null) {
    assertArrayContains(array, element, { message }, UByteArray::contains, UByteArray::contentToString)
}

/**
 * Asserts that the [array] contains the specified [element],
 * with an error message generated by the [lazyMessage] lambda otherwise.
 */
@SinceKotlin("2.4")
@ExperimentalKotlinTestApi
@OptIn(ExperimentalUnsignedTypes::class)
public fun assertContains(array: UByteArray, element: UByte, lazyMessage: () -> String) {
    assertArrayContains(array, element, lazyMessage, UByteArray::contains, UByteArray::contentToString)
}

/** Asserts that the [array] contains the specified [element], with an optional [message]. */
@SinceKotlin("1.5")
@OptIn(ExperimentalUnsignedTypes::class)
public fun assertContains(array: UShortArray, element: UShort, message: String? = null) {
    assertArrayContains(array, element, { message }, UShortArray::contains, UShortArray::contentToString)
}

/**
 * Asserts that the [array] contains the specified [element],
 * with an error message generated by the [lazyMessage] lambda otherwise.
 */
@SinceKotlin("2.4")
@ExperimentalKotlinTestApi
@OptIn(ExperimentalUnsignedTypes::class)
public fun assertContains(array: UShortArray, element: UShort, lazyMessage: () -> String) {
    assertArrayContains(array, element, lazyMessage, UShortArray::contains, UShortArray::contentToString)
}

/** Asserts that the [array] contains the specified [element], with an optional [message]. */
@SinceKotlin("1.5")
@OptIn(ExperimentalUnsignedTypes::class)
public fun assertContains(array: UIntArray, element: UInt, message: String? = null) {
    assertArrayContains(array, element, { message }, UIntArray::contains, UIntArray::contentToString)
}

/**
 * Asserts that the [array] contains the specified [element],
 * with an error message generated by the [lazyMessage] lambda otherwise.
 */
@SinceKotlin("2.4")
@ExperimentalKotlinTestApi
@OptIn(ExperimentalUnsignedTypes::class)
public fun assertContains(array: UIntArray, element: UInt, lazyMessage: () -> String) {
    assertArrayContains(array, element, lazyMessage, UIntArray::contains, UIntArray::contentToString)
}

/** Asserts that the [array] contains the specified [element], with an optional [message]. */
@SinceKotlin("1.5")
@OptIn(ExperimentalUnsignedTypes::class)
public fun assertContains(array: ULongArray, element: ULong, message: String? = null) {
    assertArrayContains(array, element, { message }, ULongArray::contains, ULongArray::contentToString)
}

/**
 * Asserts that the [array] contains the specified [element],
 * with an error message generated by the [lazyMessage] lambda otherwise.
 */
@SinceKotlin("2.4")
@ExperimentalKotlinTestApi
@OptIn(ExperimentalUnsignedTypes::class)
public fun assertContains(array: ULongArray, element: ULong, lazyMessage: () -> String) {
    assertArrayContains(array, element, lazyMessage, ULongArray::contains, ULongArray::contentToString)
}

@kotlin.internal.InlineOnly
private inline fun <@OnlyInputTypes A, E> assertArrayContains(
    array: A,
    element: E,
    crossinline lazyMessage: () -> String?,
    contains: A.(E) -> Boolean,
    crossinline contentToString: A.() -> String
) {
    asserter.assertTrue(
        { messagePrefix(lazyMessage()) + "Expected the array to contain the element.\nArray <${array.contentToString()}>, element <${element.toString()}>." }, // Explicitly call toString(): KT-45684
        array.contains(element)
    )
}

/** Asserts that the [range] contains the specified [value], with an optional [message]. */
@SinceKotlin("1.5")
public fun assertContains(range: IntRange, value: Int, message: String? = null) {
    assertRangeContains(range, value, { message }, IntRange::contains)
}

/**
 * Asserts that the [range] contains the specified [value],
 * with an error message generated by the [lazyMessage] lambda otherwise.
 */
@SinceKotlin("2.4")
@ExperimentalKotlinTestApi
public fun assertContains(range: IntRange, value: Int, lazyMessage: () -> String) {
    assertRangeContains(range, value, lazyMessage, IntRange::contains)
}


/** Asserts that the [range] contains the specified [value], with an optional [message]. */
@SinceKotlin("1.5")
public fun assertContains(range: LongRange, value: Long, message: String? = null) {
    assertRangeContains(range, value, { message }, LongRange::contains)
}

/**
 * Asserts that the [range] contains the specified [value],
 * with an error message generated by the [lazyMessage] lambda otherwise.
 */
@SinceKotlin("2.4")
@ExperimentalKotlinTestApi
public fun assertContains(range: LongRange, value: Long, lazyMessage: () -> String) {
    assertRangeContains(range, value, lazyMessage, LongRange::contains)
}

/** Asserts that the [range] contains the specified [value], with an optional [message]. */
@SinceKotlin("1.5")
public fun <T : Comparable<T>> assertContains(range: ClosedRange<T>, value: T, message: String? = null) {
    assertRangeContains(range, value, { message }, ClosedRange<T>::contains)
}

/**
 * Asserts that the [range] contains the specified [value],
 * with an error message generated by the [lazyMessage] lambda otherwise.
 */
@SinceKotlin("2.4")
@ExperimentalKotlinTestApi
public fun <T : Comparable<T>> assertContains(range: ClosedRange<T>, value: T, lazyMessage: () -> String) {
    assertRangeContains(range, value, lazyMessage, ClosedRange<T>::contains)
}


/** Asserts that the [range] contains the specified [value], with an optional [message]. */
@SinceKotlin("2.2")
@WasExperimental(ExperimentalStdlibApi::class)
public fun <T : Comparable<T>> assertContains(range: OpenEndRange<T>, value: T, message: String? = null) {
    assertRangeContains(range, value, { message }, OpenEndRange<T>::contains)
}

/**
 * Asserts that the [range] contains the specified [value],
 * with an error message generated by the [lazyMessage] lambda otherwise.
 */
@SinceKotlin("2.4")
@ExperimentalKotlinTestApi
public fun <T : Comparable<T>> assertContains(range: OpenEndRange<T>, value: T, lazyMessage: () -> String) {
    assertRangeContains(range, value, lazyMessage, OpenEndRange<T>::contains)
}


/** Asserts that the [range] contains the specified [value], with an optional [message]. */
@SinceKotlin("1.5")
public fun assertContains(range: CharRange, value: Char, message: String? = null) {
    assertRangeContains(range, value, { message }, CharRange::contains)
}

/**
 * Asserts that the [range] contains the specified [value],
 * with an error message generated by the [lazyMessage] lambda otherwise.
 */
@SinceKotlin("2.4")
@ExperimentalKotlinTestApi
public fun assertContains(range: CharRange, value: Char, lazyMessage: () -> String) {
    assertRangeContains(range, value, lazyMessage, CharRange::contains)
}

/** Asserts that the [range] contains the specified [value], with an optional [message]. */
@SinceKotlin("1.5")
public fun assertContains(range: UIntRange, value: UInt, message: String? = null) {
    assertRangeContains(range, value, { message }, UIntRange::contains)
}

/**
 * Asserts that the [range] contains the specified [value],
 * with an error message generated by the [lazyMessage] lambda otherwise.
 */
@SinceKotlin("2.4")
@ExperimentalKotlinTestApi
public fun assertContains(range: UIntRange, value: UInt, lazyMessage: () -> String) {
    assertRangeContains(range, value, lazyMessage, UIntRange::contains)
}

/** Asserts that the [range] contains the specified [value], with an optional [message]. */
@SinceKotlin("1.5")
public fun assertContains(range: ULongRange, value: ULong, message: String? = null) {
    assertRangeContains(range, value, { message }, ULongRange::contains)
}

/**
 * Asserts that the [range] contains the specified [value],
 * with an error message generated by the [lazyMessage] lambda otherwise.
 */
@SinceKotlin("2.4")
@ExperimentalKotlinTestApi
public fun assertContains(range: ULongRange, value: ULong, lazyMessage: () -> String) {
    assertRangeContains(range, value, lazyMessage, ULongRange::contains)
}

@kotlin.internal.InlineOnly
private inline fun <R, V> assertRangeContains(range: R, value: V, crossinline lazyMessage: () -> String?, contains: R.(V) -> Boolean) {
    asserter.assertTrue(
        { messagePrefix(lazyMessage()) + "Expected the range <$range> to contain the value <${value.toString()}>." }, // Explicitly call toString(): KT-45684
        range.contains(value)
    )
}

/** Asserts that the [map] contains the specified [key], with an optional [message]. */
@SinceKotlin("1.5")
public fun <@OnlyInputTypes K, V> assertContains(map: Map<K, V>, key: K, message: String? = null) {
    assertContainsImpl(map, key) { message }
}

/**
 * Asserts that the [map] contains the specified [key],
 * with an error message generated by the [lazyMessage] lambda otherwise.
 */
@SinceKotlin("2.4")
@ExperimentalKotlinTestApi
public fun <@OnlyInputTypes K, V> assertContains(map: Map<K, V>, key: K, lazyMessage: () -> String) {
    assertContainsImpl(map, key, lazyMessage)
}

private fun <@OnlyInputTypes K, V> assertContainsImpl(map: Map<K, V>, key: K, lazyMessage: () -> String?) {
    asserter.assertTrue({ messagePrefix(lazyMessage()) + "Expected the map to contain the key.\nMap <$map>, key <$key>." }, map.containsKey(key))
}

/**
 * Asserts that the [charSequence] contains the specified [char], with an optional [message].
 *
 * @param ignoreCase `true` to ignore character case when comparing characters. By default `false`.
 */
@SinceKotlin("1.5")
public fun assertContains(charSequence: CharSequence, char: Char, ignoreCase: Boolean = false, message: String? = null) {
    assertContainsImpl(charSequence, char, ignoreCase) { message }
}

/**
 * Asserts that the [charSequence] contains the specified [char],
 * with an error message generated by the [lazyMessage] lambda otherwise.
 *
 * @param ignoreCase `true` to ignore character case when comparing characters. By default `false`.
 */
@SinceKotlin("2.4")
@ExperimentalKotlinTestApi
public fun assertContains(charSequence: CharSequence, char: Char, ignoreCase: Boolean = false, lazyMessage: () -> String) {
    assertContainsImpl(charSequence, char, ignoreCase, lazyMessage)
}

private fun assertContainsImpl(charSequence: CharSequence, char: Char, ignoreCase: Boolean = false, lazyMessage: () -> String?) {
    asserter.assertTrue(
        { messagePrefix(lazyMessage()) + "Expected the char sequence to contain the char.\nCharSequence <$charSequence>, char <$char>, ignoreCase <$ignoreCase>." },
        charSequence.contains(char, ignoreCase)
    )
}

/**
 * Asserts that the [charSequence] contains the specified [other] char sequence as a substring, with an optional [message].
 *
 * @param ignoreCase `true` to ignore character case when comparing strings. By default `false`.
 */
@SinceKotlin("1.5")
public fun assertContains(charSequence: CharSequence, other: CharSequence, ignoreCase: Boolean = false, message: String? = null) {
    assertContainsImpl(charSequence, other, ignoreCase) { message }
}

/**
 * Asserts that the [charSequence] contains the specified [other] char sequence as a substring,
 * with an error message generated by the [lazyMessage] lambda otherwise.
 *
 * @param ignoreCase `true` to ignore character case when comparing strings. By default `false`.
 */
@SinceKotlin("2.4")
@ExperimentalKotlinTestApi
public fun assertContains(charSequence: CharSequence, other: CharSequence, ignoreCase: Boolean = false, lazyMessage: () -> String) {
    assertContainsImpl(charSequence, other, ignoreCase, lazyMessage)
}

private fun assertContainsImpl(charSequence: CharSequence, other: CharSequence, ignoreCase: Boolean = false, lazyMessage: () -> String?) {
    asserter.assertTrue(
        { messagePrefix(lazyMessage()) + "Expected the char sequence to contain the substring.\nCharSequence <$charSequence>, substring <$other>, ignoreCase <$ignoreCase>." },
        charSequence.contains(other, ignoreCase)
    )
}

/** Asserts that the [charSequence] contains at least one match of the specified regular expression [regex], with an optional [message]. */
@SinceKotlin("1.5")
public fun assertContains(charSequence: CharSequence, regex: Regex, message: String? = null) {
   assertContainsImpl(charSequence, regex) { message }
}

/**
 * Asserts that the [charSequence] contains at least one match of the specified regular expression [regex],
 * with an error message generated by the [lazyMessage] lambda otherwise.
 */
@SinceKotlin("2.4")
@ExperimentalKotlinTestApi
public fun assertContains(charSequence: CharSequence, regex: Regex, lazyMessage: () -> String) {
    assertContainsImpl(charSequence, regex, lazyMessage)
}

private fun assertContainsImpl(charSequence: CharSequence, regex: Regex, lazyMessage: () -> String?) {
    asserter.assertTrue(
        { messagePrefix(lazyMessage()) + "Expected the char sequence to contain the regular expression.\nCharSequence <$charSequence>, regex <$regex>." },
        charSequence.contains(regex)
    )
}
