// MARK: - Sequence higher-order function surface
//
// Split from `StdlibSurfaceSpec.swift` so that parallel branches adding
// `kotlin.sequences.Sequence` member entries do not collide on the same
// central array. New `sequence(...)` entries go here.

extension StdlibSurfaceSpec {
    static let sequenceHOFMembers: [StdlibSurfaceSpec] = [
        sequence("map", 1, "kk_sequence_map", returnStrategy: .sequence, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .any)),
        sequence("filter", 1, "kk_sequence_filter", returnStrategy: .sequence, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .boolean)),
        sequence("filterNot", 1, "kk_sequence_filterNot", returnStrategy: .sequence, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .boolean)),
        sequence("mapNotNull", 1, "kk_sequence_mapNotNull", returnStrategy: .sequence, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .nullableAny)),
        sequence("flatMap", 1, "kk_sequence_flatMap", returnStrategy: .sequence, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .any)),
        sequence("flatMapIndexed", 1, "kk_sequence_flatMapIndexed", returnStrategy: .sequence, lambdaExpectation: .indexedReceiverElement(argumentIndex: 0, returnStrategy: .any)),
        sequence("forEach", 1, "kk_sequence_forEach", returnStrategy: .unit, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .unit)),
        sequence("groupBy", 1, "kk_sequence_groupBy", returnStrategy: .map, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .any)),
        sequence("associate", 1, "kk_sequence_associate", returnStrategy: .map, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .any)),
        sequence("associateBy", 1, "kk_sequence_associateBy", returnStrategy: .map, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .any)),
        sequence("associateWith", 1, "kk_sequence_associateWith", returnStrategy: .map, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .any)),
        sequence("partition", 1, "kk_sequence_partition", returnStrategy: .any, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .boolean)),
        sequence("plus", 1, "kk_sequence_plus", returnStrategy: .sequence, lambdaExpectation: .none),
        sequence("random", 0, "kk_sequence_random", returnStrategy: .receiverElement, lambdaExpectation: .none),
        sequence("randomOrNull", 0, "kk_sequence_randomOrNull", returnStrategy: .nullableReceiverElement, lambdaExpectation: .none),
        sequence("plusElement", 1, "kk_sequence_plus_element", returnStrategy: .sequence, lambdaExpectation: .none),
        sequence("chunked", 1, "kk_sequence_chunked", returnStrategy: .sequence, lambdaExpectation: .none),
        sequence("contains", 1, "kk_sequence_contains", returnStrategy: .boolean, lambdaExpectation: .none),
        sequence("drop", 1, "kk_sequence_drop", returnStrategy: .sequence, lambdaExpectation: .none),
        sequence("dropWhile", 1, "kk_sequence_dropWhile", returnStrategy: .sequence, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .boolean)),
        sequence("averageOf", 1, "kk_sequence_averageOf", returnStrategy: .double, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .int)),
        sequence("constrainOnce", 0, "kk_sequence_constrainOnce", returnStrategy: .sequence, lambdaExpectation: .none),
        sequence("count", 0, "kk_sequence_count", returnStrategy: .int, lambdaExpectation: .none),
        sequence("distinctBy", 1, "kk_sequence_distinctBy", returnStrategy: .sequence, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .any)),
        sequence("elementAt", 1, "kk_sequence_elementAt", returnStrategy: .receiver, lambdaExpectation: .none),
        sequence("elementAtOrElse", 2, "kk_sequence_elementAtOrElse", returnStrategy: .receiver, lambdaExpectation: .none),
        sequence("shuffled", 0, "kk_sequence_shuffled", returnStrategy: .sequence, lambdaExpectation: .none),
        sequence("shuffled", 1, "kk_sequence_shuffled_random", returnStrategy: .sequence, lambdaExpectation: .none),
        sequence("elementAtOrNull", 1, "kk_sequence_elementAtOrNull", returnStrategy: .nullableAny, lambdaExpectation: .none),
        sequence("sumOf", 1, "kk_sequence_sumOf", returnStrategy: .int, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .int)),
        sequence("sumBy", 1, "kk_sequence_sumBy", returnStrategy: .int, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .int)),
        sequence("sumByDouble", 1, "kk_sequence_sumByDouble", returnStrategy: .double, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .double)),
        sequence("minOf", 1, "kk_sequence_minOf", returnStrategy: .any, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .any)),
        sequence("maxWith", 1, "kk_sequence_maxWith", returnStrategy: .any, lambdaExpectation: .none),
        sequence("maxOf", 1, "kk_sequence_maxOf", returnStrategy: .any, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .any)),
        sequence("max", 0, "kk_sequence_max", returnStrategy: .receiverElement, lambdaExpectation: .none),
        sequence("minOfOrNull", 1, "kk_sequence_minOfOrNull", returnStrategy: .nullableAny, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .any)),
        sequence("maxOfOrNull", 1, "kk_sequence_maxOfOrNull", returnStrategy: .nullableAny, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .any)),
        sequence("maxOrNull", 0, "kk_sequence_maxOrNull", returnStrategy: .nullableAny, lambdaExpectation: .none),
        sequence("maxWithOrNull", 1, "kk_sequence_maxWithOrNull", returnStrategy: .nullableAny, lambdaExpectation: .none),
        sequence("minOrNull", 0, "kk_sequence_minOrNull", returnStrategy: .nullableAny, lambdaExpectation: .none),
        sequence("none", 0, "kk_sequence_none", returnStrategy: .boolean, lambdaExpectation: .none),
        sequence("none", 1, "kk_sequence_none", returnStrategy: .boolean, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .boolean)),
        sequence("minWithOrNull", 1, "kk_sequence_minWithOrNull", returnStrategy: .nullableReceiverElement, lambdaExpectation: .none),
        sequence("first", 0, "kk_sequence_first", returnStrategy: .receiverElement, lambdaExpectation: .none),
        sequence("firstOrNull", 0, "kk_sequence_firstOrNull", returnStrategy: .nullableReceiverElement, lambdaExpectation: .none),
        sequence("maxBy", 1, "kk_sequence_maxBy", returnStrategy: .receiverElement, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .any)),
        sequence("minWith", 1, "kk_sequence_minWith", returnStrategy: .receiverElement, lambdaExpectation: .none),
        sequence("maxByOrNull", 1, "kk_sequence_maxByOrNull", returnStrategy: .nullableReceiverElement, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .any)),
        sequence("firstNotNullOf", 1, "kk_sequence_firstNotNullOf", returnStrategy: .any, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .nullableAny)),
        sequence("firstNotNullOfOrNull", 1, "kk_sequence_firstNotNullOfOrNull", returnStrategy: .nullableAny, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .nullableAny)),
        sequence("indexOfLast", 1, "kk_sequence_indexOfLast", returnStrategy: .int, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .boolean)),
        sequence("intersect", 1, "kk_sequence_intersect", returnStrategy: .set, lambdaExpectation: .none),
        sequence("fold", 2, "kk_sequence_fold", returnStrategy: .any, lambdaExpectation: .receiverElement(argumentIndex: 1, returnStrategy: .any)),
        sequence("foldIndexed", 2, "kk_sequence_foldIndexed", returnStrategy: .any, lambdaExpectation: .indexedReceiverElement(argumentIndex: 1, returnStrategy: .any)),
        sequence("indexOfFirst", 1, "kk_sequence_indexOfFirst", returnStrategy: .int, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .boolean)),
        sequence("minByOrNull", 1, "kk_sequence_minByOrNull", returnStrategy: .nullableReceiverElement, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .any)),
        sequence("minBy", 1, "kk_sequence_minBy", returnStrategy: .receiverElement, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .any)),
        sequence("min", 0, "kk_sequence_min", returnStrategy: .any, lambdaExpectation: .none),
        sequence("forEachIndexed", 1, "kk_sequence_forEachIndexed", returnStrategy: .unit, lambdaExpectation: .indexedReceiverElement(argumentIndex: 0, returnStrategy: .unit)),
        sequence("onEach", 1, "kk_sequence_onEach", returnStrategy: .sequence, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .unit)),
        sequence("onEachIndexed", 1, "kk_sequence_onEachIndexed", returnStrategy: .sequence, lambdaExpectation: .indexedReceiverElement(argumentIndex: 0, returnStrategy: .unit)),
        sequence("takeWhile", 1, "kk_sequence_takeWhile", returnStrategy: .sequence, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .boolean)),
        sequence("mapIndexed", 1, "kk_sequence_mapIndexed", returnStrategy: .sequence, lambdaExpectation: .indexedReceiverElement(argumentIndex: 0, returnStrategy: .any)),
        sequence("mapIndexedNotNull", 1, "kk_sequence_mapIndexedNotNull", returnStrategy: .sequence, lambdaExpectation: .indexedReceiverElement(argumentIndex: 0, returnStrategy: .nullableAny)),
        sequence("reversed", 0, "kk_sequence_reversed", returnStrategy: .sequence, lambdaExpectation: .none),
        sequence("filterIndexed", 1, "kk_sequence_filterIndexed", returnStrategy: .sequence, lambdaExpectation: .indexedReceiverElement(argumentIndex: 0, returnStrategy: .boolean)),
        sequence("runningFold", 2, "kk_sequence_runningFold", returnStrategy: .sequence, lambdaExpectation: .none),
        sequence("runningReduceIndexed", 1, "kk_sequence_runningReduceIndexed", returnStrategy: .sequence, lambdaExpectation: .none),
        sequence("scanIndexed", 2, "kk_sequence_scanIndexed", returnStrategy: .sequence, lambdaExpectation: .none),
        sequence("runningFoldIndexed", 2, "kk_sequence_runningFoldIndexed", returnStrategy: .sequence, lambdaExpectation: .none),
        sequence("scan", 2, "kk_sequence_scan", returnStrategy: .sequence, lambdaExpectation: .none),
        sequence("filterTo", 2, "kk_sequence_filterTo", returnStrategy: .destinationArgument, lambdaExpectation: .destinationElement(argumentIndex: 1, returnStrategy: .boolean)),
        sequence("filterNotTo", 2, "kk_sequence_filterNotTo", returnStrategy: .destinationArgument, lambdaExpectation: .destinationElement(argumentIndex: 1, returnStrategy: .boolean)),
        sequence("mapTo", 2, "kk_sequence_mapTo", returnStrategy: .destinationArgument, lambdaExpectation: .destinationElement(argumentIndex: 1, returnStrategy: .destinationElement)),
        sequence("mapNotNullTo", 2, "kk_sequence_mapNotNullTo", returnStrategy: .destinationArgument, lambdaExpectation: .destinationElement(argumentIndex: 1, returnStrategy: .nullableAny)),
        sequence("mapIndexedTo", 2, "kk_sequence_mapIndexedTo", returnStrategy: .destinationArgument, lambdaExpectation: .indexedDestinationElement(argumentIndex: 1, returnStrategy: .destinationElement)),
        sequence("flatMapTo", 2, "kk_sequence_flatMapTo", returnStrategy: .destinationArgument, lambdaExpectation: .destinationElement(argumentIndex: 1, returnStrategy: .collectionOfDestinationElement)),
        sequence("mapIndexedNotNullTo", 2, "kk_sequence_mapIndexedNotNullTo", returnStrategy: .destinationArgument, lambdaExpectation: .indexedDestinationElement(argumentIndex: 1, returnStrategy: .nullableAny)),
        sequence("filterIndexedTo", 2, "kk_sequence_filterIndexedTo", returnStrategy: .destinationArgument, lambdaExpectation: .indexedDestinationElement(argumentIndex: 1, returnStrategy: .boolean)),
        sequence("flatMapIndexedTo", 2, "kk_sequence_flatMapIndexedTo", returnStrategy: .destinationArgument, lambdaExpectation: .indexedDestinationElement(argumentIndex: 1, returnStrategy: .collectionOfDestinationElement)),
        sequence("filterNotNull", 0, "kk_sequence_filterNotNull", returnStrategy: .sequence, lambdaExpectation: .none),
        sequence("filterNotNullTo", 1, "kk_sequence_filterNotNullTo", returnStrategy: .destinationArgument, lambdaExpectation: .none),
        sequence("filterIsInstance", 0, "kk_sequence_filterIsInstance", returnStrategy: .sequence, lambdaExpectation: .none),
        sequence("filterIsInstanceTo", 1, "kk_sequence_filterIsInstanceTo", returnStrategy: .destinationArgument, lambdaExpectation: .none),
        sequence("reduceRightIndexed", 1, "kk_sequence_reduceRightIndexed", returnStrategy: .receiverElement, lambdaExpectation: .indexedReceiverElement(argumentIndex: 0, returnStrategy: .any)),
        sequence("reduceRightOrNull", 1, "kk_sequence_reduceRightOrNull", returnStrategy: .nullableReceiverElement, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .any)),
        sequence("requireNoNulls", 0, "kk_sequence_requireNoNulls", returnStrategy: .sequence, lambdaExpectation: .none),
        sequence("minus", 1, "kk_sequence_minus", returnStrategy: .sequence, lambdaExpectation: .none),
        sequence("associateTo", 2, "kk_sequence_associateTo", returnStrategy: .destinationArgument, lambdaExpectation: .destinationElement(argumentIndex: 1, returnStrategy: .pairOfDestinationKeyValue)),
        sequence("associateByTo", 2, "kk_sequence_associateByTo", returnStrategy: .destinationArgument, lambdaExpectation: .destinationElement(argumentIndex: 1, returnStrategy: .any)),
        sequence("associateWithTo", 2, "kk_sequence_associateWithTo", returnStrategy: .destinationArgument, lambdaExpectation: .destinationElement(argumentIndex: 1, returnStrategy: .any)),
        sequence("groupByTo", 2, "kk_sequence_groupByTo", returnStrategy: .destinationArgument, lambdaExpectation: .destinationElement(argumentIndex: 1, returnStrategy: .any)),
        sequence("reduce", 1, "kk_sequence_reduce", returnStrategy: .receiverElement, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .any)),
        sequence("reduceOrNull", 1, "kk_sequence_reduceOrNull", returnStrategy: .nullableReceiverElement, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .any)),
        sequence("reduceRight", 1, "kk_sequence_reduceRight", returnStrategy: .receiverElement, lambdaExpectation: .receiverElement(argumentIndex: 0, returnStrategy: .any)),
        sequence("reduceIndexed", 1, "kk_sequence_reduceIndexed", returnStrategy: .receiverElement, lambdaExpectation: .indexedReceiverElement(argumentIndex: 0, returnStrategy: .any)),
    ]
}
