extension ABILoweringPass {
    /// I/O non-throwing callees: print/read, StringBuilder, BufferedReader, File, URI, HTTP.
    static func nonThrowingIOCallees(_ interner: StringInterner) -> [InternedString] {
        [
            interner.intern("kk_print_any"),
            interner.intern("kk_print_noarg"),
            interner.intern("kk_println_any"),
            interner.intern("kk_println_newline"),
            interner.intern("kk_readline"),
            interner.intern("kk_readlnOrNull"),
            // StringBuilder (STDLIB-255/256/257)
            interner.intern("kk_string_builder_new"),
            interner.intern("kk_string_builder_new_from_string"),
            // StringBuilder enhancements (STDLIB-311) — buildString DSL helpers
            interner.intern("kk_string_builder_append"),
            interner.intern("kk_string_builder_append_line"),
            interner.intern("kk_string_builder_append_line_noarg"),
            // buildString DSL insert/delete clamp out-of-range indices instead of throwing.
            interner.intern("kk_string_builder_insert"),
            interner.intern("kk_string_builder_delete"),
            interner.intern("kk_string_builder_length"),
            interner.intern("kk_string_builder_append_range"),
            interner.intern("kk_string_builder_append_obj"),
            interner.intern("kk_string_builder_toString"),
            interner.intern("kk_string_builder_length_prop"),
            interner.intern("kk_string_builder_append_line_obj"),
            interner.intern("kk_string_builder_append_line_noarg_obj"),
            // Bounds-checking StringBuilder members throw via outThrown (DEBT-RT-001).
            interner.intern("kk_string_builder_clear"),
            interner.intern("kk_string_builder_reverse"),
            interner.intern("kk_string_builder_appendRange_obj"),
            // BufferedReader non-throwing operations (no outThrown in ABI spec)
            // kk_buffered_reader_useLines and kk_buffered_reader_forEachLine are
            // intentionally excluded — they accept a lambda and an outThrown parameter.
            interner.intern("kk_buffered_reader_readLine"),
            interner.intern("kk_buffered_reader_readLines"),
            interner.intern("kk_buffered_reader_close"),
            interner.intern("kk_buffered_reader_read"),
            interner.intern("kk_buffered_reader_ready"),
            interner.intern("kk_buffered_reader_iterator"),
            // File I/O (STDLIB-320/321/323/IO-087) — non-throwing file operations
            interner.intern("kk_file_new"),
            interner.intern("kk_file_new_parent_child"),
            interner.intern("kk_file_exists"),
            interner.intern("kk_file_isFile"),
            interner.intern("kk_file_isDirectory"),
            interner.intern("kk_file_name"),
            interner.intern("kk_file_nameWithoutExtension"),
            interner.intern("kk_file_path"),
            interner.intern("kk_file_extension"),               // STDLIB-IO-PROP-002
            interner.intern("kk_file_invariantSeparatorsPath"), // STDLIB-IO-PROP-003
            interner.intern("kk_classloader_getSystemClassLoader"),
            interner.intern("kk_classloader_getResource"),
            interner.intern("kk_classloader_getResourceAsStream"),
            interner.intern("kk_resource_exists"),
            interner.intern("kk_resource_stream_read"),
            interner.intern("kk_resource_stream_close"),
            interner.intern("kk_file_absolutePath"),
            interner.intern("kk_file_canonicalPath"),
            interner.intern("kk_file_parent"),
            interner.intern("kk_file_length"),
            interner.intern("kk_file_lastModified"),
            interner.intern("kk_file_createNewFile"),
            interner.intern("kk_file_canRead"),
            interner.intern("kk_file_canWrite"),
            interner.intern("kk_file_canExecute"),
            interner.intern("kk_file_resolveSibling_file"),
            interner.intern("kk_file_resolveSibling_string"),
            interner.intern("kk_file_startsWith_file"),
            interner.intern("kk_file_startsWith_string"),
            interner.intern("kk_file_normalize"),
            interner.intern("kk_file_delete"),
            interner.intern("kk_file_mkdirs"),
            interner.intern("kk_file_listFiles"),
            interner.intern("kk_file_walk"),
            // STDLIB-IO-TYPE-004: FileTreeWalk factory and builder methods are non-throwing
            interner.intern("kk_file_walkTopDown"),
            interner.intern("kk_file_walkBottomUp"),
            interner.intern("kk_file_walk_with_direction"),
            interner.intern("kk_file_tree_walk_create"),
            interner.intern("kk_file_tree_walk_to_list"),
            interner.intern("kk_file_tree_walk_max_depth"),
            interner.intern("kk_file_tree_walk_filter"),
            interner.intern("kk_file_tree_walk_onEnter"),
            interner.intern("kk_file_tree_walk_onLeave"),
            interner.intern("kk_file_tree_walk_onFail"),
            // Files utility (STDLIB-IO-090) — non-throwing subset
            interner.intern("kk_files_isRegularFile"),
            interner.intern("kk_files_isDirectory"),
            interner.intern("kk_files_exists"),
            interner.intern("kk_fileTime_toMillis"),
            interner.intern("kk_uri_toString"),
            interner.intern("kk_uri_scheme"),
            interner.intern("kk_uri_authority"),
            interner.intern("kk_uri_path"),
            interner.intern("kk_uri_query"),
            interner.intern("kk_uri_fragment"),
            interner.intern("kk_uri_normalize"),
            interner.intern("kk_uri_relativize"),
            interner.intern("kk_http_client_newHttpClient"),
            interner.intern("kk_http_request_newBuilder"),
            interner.intern("kk_http_request_newBuilder_uri"),
            interner.intern("kk_http_request_builder_uri"),
            interner.intern("kk_http_request_builder_header"),
            interner.intern("kk_http_request_builder_GET"),
            interner.intern("kk_http_request_builder_POST"),
            interner.intern("kk_http_body_publishers_noBody"),
            interner.intern("kk_http_body_publishers_ofString"),
            interner.intern("kk_http_body_handlers_ofString"),
            interner.intern("kk_http_response_statusCode"),
            interner.intern("kk_http_response_body"),
            interner.intern("kk_http_response_headers"),
            interner.intern("kk_http_headers_map"),
            interner.intern("kk_http_headers_firstValue"),
            interner.intern("kk_string_orEmpty"),
        ]
    }
}
