import RuntimeABI

extension ABILoweringPass {
    /// Miscellaneous stdlib non-throwing callees that do not fit a specific domain category.
    static func nonThrowingStdlibCallees(_ interner: StringInterner) -> [InternedString] {
        [
            // kk_property_access removed — PropertyLowering now emits direct accessor
            // calls with synthetic symbols; canThrow is handled via symbol check below.
            interner.intern("kk_lambda_invoke"),
            interner.intern("kk_object_new"),
            interner.intern("kk_object_type_id"),
            interner.intern("kk_object_register_itable_method"),
            interner.intern("kk_vararg_spread_concat"),
            interner.intern("kk_type_register_super"),
            interner.intern("kk_type_register_iface"),
            interner.intern("kk_any_to_string"),
            interner.intern("kk_any_hashCode"),
            interner.intern("kk_any_equals"),
            interner.intern("kk_any_member_to_string"),
            interner.intern("kk_any_member_hashCode"),
            interner.intern("kk_any_member_equals"),
            interner.intern("kk_throwable_new_with_cause"),
            interner.intern("kk_throwable_new_cause"),
            interner.intern("kk_throwable_is_cancellation"),
            interner.intern("kk_throwable_message"),
            interner.intern("kk_throwable_cause"),
            interner.intern("kk_throwable_stackTraceToString"),
            interner.intern("kk_throwable_printStackTrace"),
            interner.intern("kk_throwable_initCause"),
            interner.intern("kk_throwable_addSuppressed"),
            interner.intern("kk_throwable_getSuppressed"),
            interner.intern("kk_throwable_suppressedExceptions"),
            interner.intern("kk_no_when_branch_matched_exception_new"),
            interner.intern("kk_no_when_branch_matched_exception_new_message"),
            interner.intern("kk_no_when_branch_matched_exception_new_message_cause"),
            interner.intern("kk_no_when_branch_matched_exception_new_cause"),
            interner.intern("kk_concurrent_modification_exception_new"),
            interner.intern("kk_concurrent_modification_exception_new_message"),
            interner.intern("kk_concurrent_modification_exception_new_message_cause"),
            interner.intern("kk_concurrent_modification_exception_new_cause"),
            interner.intern("kk_abort_unreachable"),
            interner.intern("kk_op_elvis"),
            interner.intern("kk_lazy_create"),
            interner.intern("kk_lazy_of"),
            interner.intern("kk_lazy_get_value"),
            interner.intern("kk_lazy_is_initialized"),
            interner.intern("kk_observable_create"),
            interner.intern("kk_observable_get_value"),
            interner.intern("kk_observable_set_value"),
            interner.intern("kk_vetoable_create"),
            interner.intern("kk_vetoable_get_value"),
            interner.intern("kk_vetoable_set_value"),
            interner.intern("kk_notNull_create"),
            interner.intern("kk_notNull_set_value"),
            interner.intern("kk_custom_delegate_create"),
            interner.intern("kk_custom_delegate_get_value"),
            interner.intern("kk_custom_delegate_set_value"),
            interner.intern("kk_system_exitProcess"),
            interner.intern("kk_system_currentTimeMillis"),
            interner.intern("kk_system_nanoTime"),
            interner.intern("kk_system_getTimeMicros"),
            interner.intern("kk_system_getTimeMillis"),
            interner.intern("kk_system_getTimeNanos"),
            interner.intern("kk_system_process_start_nanos"),
            interner.intern("kk_system_gc"),
            interner.intern("kk_platform_canAccessUnaligned"),
            interner.intern("kk_platform_isLittleEndian"),
            interner.intern("kk_platform_osFamily"),
            interner.intern("kk_platform_cpuArchitecture"),
            interner.intern("kk_platform_getAvailableProcessors"),
            interner.intern("kk_platform_memoryModel"),
            interner.intern("kk_native_identityHashCode"),
            interner.intern("kk_native_getStackTraceAddresses"),
            interner.intern("kk_native_getUnhandledExceptionHook"),
            interner.intern("kk_native_setUnhandledExceptionHook"),
            interner.intern("kk_native_terminateWithUnhandledException"),
            interner.intern("kk_native_byteArray_getByteAt"),
            interner.intern("kk_native_byteArray_getShortAt"),
            interner.intern("kk_native_byteArray_getIntAt"),
            interner.intern("kk_native_byteArray_getLongAt"),
            interner.intern("kk_native_byteArray_setByteAt"),
            interner.intern("kk_native_byteArray_setShortAt"),
            interner.intern("kk_native_byteArray_setIntAt"),
            interner.intern("kk_native_byteArray_setLongAt"),
            interner.intern("kk_native_byteArray_getUByteAt"),
            interner.intern("kk_native_byteArray_getUShortAt"),
            interner.intern("kk_native_byteArray_getUIntAt"),
            interner.intern("kk_native_byteArray_getULongAt"),
            interner.intern("kk_native_byteArray_setUByteAt"),
            interner.intern("kk_native_byteArray_setUShortAt"),
            interner.intern("kk_native_byteArray_setUIntAt"),
            interner.intern("kk_native_byteArray_setULongAt"),
            interner.intern("kk_native_byteArray_getCharAt"),
            interner.intern("kk_native_byteArray_getFloatAt"),
            interner.intern("kk_native_byteArray_getDoubleAt"),
            interner.intern("kk_native_byteArray_setCharAt"),
            interner.intern("kk_native_byteArray_setFloatAt"),
            interner.intern("kk_native_byteArray_setDoubleAt"),
            interner.intern("kk_runtime_getRuntime"),
            interner.intern("kk_runtime_totalMemory"),
            interner.intern("kk_runtime_freeMemory"),
            interner.intern("kk_runtime_maxMemory"),
            // Instant / Clock (STDLIB-TIME-083/086)
            interner.intern("kk_instant_now"),
            interner.intern("kk_clock_system_now"),
            interner.intern("kk_clock_now"),
            interner.intern("kk_instant_from_epoch_millis"),
            interner.intern("kk_instant_epoch_seconds"),
            interner.intern("kk_instant_nano_of_second"),
            interner.intern("kk_instant_plus_duration"),
            interner.intern("kk_instant_minus_duration"),
            interner.intern("kk_instant_compare"),
            interner.intern("kk_instant_until"),
            interner.intern("kk_instant_elapsed"),
            interner.intern("kk_instant_is_distant_past"),
            interner.intern("kk_instant_is_distant_future"),
            interner.intern("kk_time_source_as_clock"),
            interner.intern("kk_time_source_mark_now"),
            interner.intern("kk_time_source_monotonic_mark_now"),
            interner.intern("kk_time_mark_elapsed_now"),
            interner.intern("kk_time_mark_has_passed_now"),
            interner.intern("kk_time_mark_has_not_passed_now"),
            interner.intern("kk_time_mark_plus_duration"),
            interner.intern("kk_time_mark_minus_duration"),
            interner.intern("kk_time_mark_minus_mark"),
            interner.intern("kk_time_mark_compare"),
            interner.intern("kk_test_time_source_new"),
            interner.intern("kk_test_time_source_plus_assign"),
            interner.intern("kk_test_time_source_mark_now"),
            interner.intern("kk_test_time_source_read"),
            interner.intern("kk_uuid_random"),
            interner.intern("kk_uuid_nil"),
            interner.intern("kk_uuid_lexicalOrder"),
            interner.intern("kk_uuid_parseOrNull"),
            interner.intern("kk_uuid_parseHexOrNull"),
            interner.intern("kk_uuid_parseHexDashOrNull"),
            interner.intern("kk_uuid_toString"),
            interner.intern("kk_uuid_toHexString"),
            interner.intern("kk_uuid_toLongs"),
            interner.intern("kk_uuid_toByteArray"),
            interner.intern("kk_uuid_version"),
            interner.intern("kk_uuid_variant"),
            interner.intern("kk_uuid_mostSignificantBits"),
            interner.intern("kk_uuid_leastSignificantBits"),
            interner.intern("kk_uuid_nameUUIDFromBytes"),
            interner.intern("kk_uuid_fromLongs"),
            interner.intern("kk_uuid_toKotlinUuid"),
            // Regex (STDLIB-100/101/102/103)
            interner.intern("kk_regex_create"),
            interner.intern("kk_string_matches_regex_flat"),
            interner.intern("kk_string_contains_regex"),
            interner.intern("kk_regex_find"),
            interner.intern("kk_regex_findAll"),
            interner.intern("kk_string_replace_regex"),
            interner.intern("kk_string_split_regex"),
            interner.intern("kk_regex_matchEntire"),
            interner.intern("kk_string_toRegex"),
            interner.intern("kk_string_toRegex_with_option"),
            interner.intern("kk_string_toRegex_with_options"),
            interner.intern("kk_regex_pattern"),
            interner.intern("kk_regex_options"),
            interner.intern("kk_match_result_value"),
            interner.intern("kk_match_result_groupValues"),
            // Regex (STDLIB-480)
            interner.intern("kk_regex_create_with_option"),
            interner.intern("kk_regex_create_with_options"),
            interner.intern("kk_regex_containsMatchIn"),
            // MatchResult.groups / MatchGroupCollection / MatchGroup
            interner.intern("kk_match_result_groups"),
            interner.intern("kk_match_group_collection_get"),
            interner.intern("kk_match_group_collection_get_at"),
            interner.intern("kk_match_group_collection_size"),
            interner.intern("kk_match_group_value"),
            interner.intern("kk_match_group_range"),
            // STDLIB-REGEX-095: MatchResult complete implementation
            interner.intern("kk_match_result_range"),
            interner.intern("kk_match_result_component1"),
            interner.intern("kk_match_result_component2"),
            interner.intern("kk_match_result_next"),
            // STDLIB-REGEX-097: Regex.groupNames
            interner.intern("kk_regex_group_names"),
            // Result non-throwing functions (STDLIB-281/282)
            interner.intern("kk_result_isSuccess"),
            interner.intern("kk_result_isFailure"),
            interner.intern("kk_result_getOrNull"),
            interner.intern("kk_result_getOrDefault"),
            interner.intern("kk_result_exceptionOrNull"),
            // KotlinVersion component surface.
            interner.intern("kk_kotlin_version_new"),
            interner.intern("kk_kotlin_version_new_patch"),
            interner.intern("kk_kotlin_version_current"),
            interner.intern("kk_kotlin_version_major"),
            interner.intern("kk_kotlin_version_minor"),
            interner.intern("kk_kotlin_version_patch"),
            interner.intern("kk_kotlin_version_compareTo"),
            interner.intern("kk_kotlin_version_isAtLeast"),
            interner.intern("kk_kotlin_version_isAtLeast_patch"),
            // BigInteger non-throwing operations (STDLIB-NUM-129, STDLIB-GAP-PH1)
            // divide, pow, fromString, modInverse, modPow are intentionally excluded — they
            // use outThrown and are marked .throwingFunction in the sema stubs.
            interner.intern("kk_biginteger_valueOf"),
            interner.intern("kk_biginteger_add"),
            interner.intern("kk_biginteger_subtract"),
            interner.intern("kk_biginteger_multiply"),
            interner.intern("kk_biginteger_gcd"),
            interner.intern("kk_biginteger_abs"),
            interner.intern("kk_biginteger_toInt"),
            interner.intern("kk_biginteger_toLong"),
            interner.intern("kk_biginteger_toString"),
            interner.intern("kk_biginteger_and"),
            interner.intern("kk_biginteger_or"),
            interner.intern("kk_biginteger_xor"),
            interner.intern("kk_biginteger_not"),
            interner.intern("kk_biginteger_shiftLeft"),
            interner.intern("kk_biginteger_shiftRight"),
            interner.intern("kk_biginteger_toByteArray"),
            // JSON Serialization (STDLIB-SER-132) — no outThrown parameter
            interner.intern("kk_json_encodeToString"),
            interner.intern("kk_json_encodeMapToString"),
            interner.intern("kk_json_default"),
            // Security constructors (STDLIB-SEC-144) — no outThrown parameter
            // Kotlin/Native reference helpers — no outThrown parameter
            interner.intern("kk_weak_ref_create"),
            interner.intern("kk_weak_ref_get"),
            interner.intern("kk_weak_ref_clear"),
            interner.intern("kk_cleaner_create"),
            interner.intern("kk_cleaner_dispose"),
            interner.intern("kk_gc_collect"),
            interner.intern("kk_gc_schedule"),
            interner.intern("kk_gc_target_heap_bytes"),
            interner.intern("kk_gc_target_heap_utilization"),
            interner.intern("kk_gc_max_heap_bytes"),
            interner.intern("kk_debugging_is_thread_state_runnable"),
            interner.intern("kk_debugging_gc_suspend_count"),
            interner.intern("kk_debugging_thread_count"),
            interner.intern("kk_debugging_global_object_count"),
        ]
    }

    /// Runtime callees that omit the `outThrown` ABI lowering path.
    ///
    /// Derived from `RuntimeABISpec.nonThrowingRuntimeCalleeNames` so throwing
    /// metadata is maintained in a single place (DEBT-KIR-003).
    func nonThrowingCallees(interner: StringInterner) -> Set<InternedString> {
        var result = Set(RuntimeABISpec.nonThrowingRuntimeCalleeNames.map { interner.intern($0) })
        result.formUnion(Self.nonThrowingRangeCallees(interner))
        result.formUnion(Self.nonThrowingConcurrencyCallees(interner))
        result.formUnion(Self.nonThrowingCollectionCallees(interner))
        result.formUnion(Self.nonThrowingSequenceCallees(interner))
        result.formUnion(Self.nonThrowingIOCallees(interner))
        result.formUnion(Self.nonThrowingPrimitiveCallees(interner))
        result.formUnion(Self.nonThrowingReflectionCallees(interner))
        result.formUnion(Self.nonThrowingStdlibCallees(interner))
        result.formUnion(Self.kPropertyStubCallees(interner))
        return result
    }
}
