extension ABILoweringPass {
    /// Range-related non-throwing callees: IntRange, UIntRange, LongRange, CharRange, ULongRange.
    static func nonThrowingRangeCallees(_ interner: StringInterner) -> [InternedString] {
        [
            interner.intern("kk_for_lowered"),
            interner.intern("kk_range_iterator"),
            interner.intern("kk_range_hasNext"),
            interner.intern("kk_range_next"),
            interner.intern("kk_op_rangeTo"),
            interner.intern("kk_op_rangeUntil"),
            interner.intern("kk_op_ulong_rangeUntil"),
            interner.intern("kk_op_downTo"),
            // kk_op_step is intentionally NOT in this list — it throws
            // IllegalArgumentException for step<=0 (STDLIB-022).
            interner.intern("kk_range_contains"),
            interner.intern("kk_range_first"),
            interner.intern("kk_range_last"),
            interner.intern("kk_range_endExclusive"),
            interner.intern("kk_range_count"),
            interner.intern("kk_range_isEmpty"),
            interner.intern("kk_range_sum"),
            interner.intern("kk_range_take"),
            interner.intern("kk_range_drop"),
            interner.intern("kk_range_average"),
            interner.intern("kk_range_sorted"),
            interner.intern("kk_range_toList"),
            interner.intern("kk_range_toIntArray"),
            interner.intern("kk_ulong_range_toList"),
            interner.intern("kk_ulong_range_count"),
            interner.intern("kk_ulong_range_iterator"),
            interner.intern("kk_ulong_range_hasNext"),
            interner.intern("kk_ulong_range_next"),
            interner.intern("kk_range_step"),
            interner.intern("kk_range_reversed"),
            interner.intern("kk_char_range_isEmpty"),
            interner.intern("kk_char_range_toList"),
            // UIntRange properties and HOFs (STDLIB-RANGE-036)
            interner.intern("kk_uint_range_contains"),
            interner.intern("kk_uint_range_isEmpty"),
            interner.intern("kk_uint_range_first"),
            interner.intern("kk_uint_range_last"),
            interner.intern("kk_uint_range_step"),
            interner.intern("kk_uint_range_count"),
            interner.intern("kk_uint_range_sum"),
            interner.intern("kk_uint_range_toUIntArray"),
            interner.intern("kk_uint_range_iterator"),
            interner.intern("kk_uint_range_hasNext"),
            interner.intern("kk_uint_range_next"),
            interner.intern("kk_uint_range_reversed"),
            interner.intern("kk_uint_range_toList"),
            interner.intern("kk_uint_range_take"),
            interner.intern("kk_uint_range_drop"),
            interner.intern("kk_uint_range_average"),
            interner.intern("kk_uint_range_sorted"),
            interner.intern("kk_ulong_range_toULongArray"),
            interner.intern("kk_ulong_range_take"),
            interner.intern("kk_ulong_range_drop"),
            interner.intern("kk_ulong_range_average"),
            interner.intern("kk_ulong_range_sorted"),
            // LongRange properties and methods (STDLIB-RANGE-035)
            interner.intern("kk_long_rangeTo"),
            interner.intern("kk_long_range_contains"),
            interner.intern("kk_long_range_isEmpty"),
            interner.intern("kk_long_range_first"),
            interner.intern("kk_long_range_last"),
            interner.intern("kk_long_range_step"),
            interner.intern("kk_long_range_count"),
            interner.intern("kk_long_range_toLongArray"),
            interner.intern("kk_long_range_reversed"),
            interner.intern("kk_long_range_toList"),
            interner.intern("kk_long_range_iterator"),
            interner.intern("kk_long_range_take"),
            interner.intern("kk_long_range_drop"),
            interner.intern("kk_long_range_average"),
            interner.intern("kk_long_range_sorted"),
            interner.intern("kk_long_range_firstOrNull"),
            interner.intern("kk_long_range_lastOrNull"),
            // CharRange take/drop/sorted (STDLIB-RANGE-TDS)
            interner.intern("kk_char_range_take"),
            interner.intern("kk_char_range_drop"),
            interner.intern("kk_char_range_sorted"),
        ]
    }
}
