import RuntimeABI

/// Common lookup names for `CollectionLiteralLookupTables`.
///
/// Split out from `CollectionLiteralLoweringPass+LookupTables.swift`.
struct CommonLookupNames {
    // Member names (STDLIB-637)
    let sumName: InternedString
    let sizeName: InternedString
    let getName: InternedString
    let containsName: InternedString
    let containsAllName: InternedString
    let containsKeyName: InternedString
    let containsValueName: InternedString
    let isEmptyName: InternedString
    let countName: InternedString
    let addName: InternedString
    let removeName: InternedString
    let firstName: InternedString
    let lastName: InternedString
    let startName: InternedString
    let endInclusiveName: InternedString
    let endExclusiveName: InternedString
    let stepName: InternedString
    let iteratorName: InternedString
    // Higher-order collection member names (FUNC-003)
    let mapName: InternedString
    let filterName: InternedString
    let filterNotName: InternedString
    let mapNotNullName: InternedString
    let filterNotNullName: InternedString
    let requireNoNullsName: InternedString
    let filterToName: InternedString
    let filterNotToName: InternedString
    let mapToName: InternedString
    let flatMapToName: InternedString
    let mapNotNullToName: InternedString
    let mapIndexedToName: InternedString
    let mapIndexedNotNullToName: InternedString
    let flatMapIndexedToName: InternedString
    let filterIsInstanceToName: InternedString
    let filterIndexedToName: InternedString
    let filterNotNullToName: InternedString
    let forEachName: InternedString
    let flatMapName: InternedString
    let flatMapIndexedName: InternedString
    let anyName: InternedString
    let noneName: InternedString
    let allName: InternedString
    // Additional higher-order collection member names (STDLIB-005)
    let foldName: InternedString
    let foldRightName: InternedString
    let reduceName: InternedString
    let reduceRightName: InternedString
    let reduceOrNullName: InternedString
    let scanName: InternedString
    let runningFoldName: InternedString
    let runningReduceName: InternedString
    let scanReduceName: InternedString
    let groupByName: InternedString
    let sortedByName: InternedString
    let findName: InternedString
    let findLastName: InternedString
    let associateByName: InternedString
    let associateWithName: InternedString
    let associateName: InternedString
    let associateToName: InternedString
    let associateByToName: InternedString
    let associateWithToName: InternedString
    let groupByToName: InternedString
    let mapValuesName: InternedString
    let mapValuesToName: InternedString
    let mapKeysName: InternedString
    let mapKeysToName: InternedString
    let filterKeysName: InternedString
    let filterValuesName: InternedString
    let zipName: InternedString
    let zipWithNextName: InternedString
    let unzipName: InternedString
    let withIndexName: InternedString
    let forEachIndexedName: InternedString
    let onEachName: InternedString
    let onEachIndexedName: InternedString
    let mapIndexedName: InternedString
    let mapIndexedNotNullName: InternedString
    let foldIndexedName: InternedString
    let foldRightIndexedName: InternedString
    let reduceRightIndexedName: InternedString
    let reduceRightIndexedOrNullName: InternedString
    let reduceRightOrNullName: InternedString
    let reduceIndexedName: InternedString
    let filterIndexedName: InternedString
    let reduceIndexedOrNullName: InternedString
    let runningFoldIndexedName: InternedString
    let runningReduceIndexedName: InternedString
    let scanIndexedName: InternedString
    let sumOfName: InternedString
    let sumByName: InternedString
    let sumByDoubleName: InternedString
    let maxName: InternedString
    let maxOrNullName: InternedString
    let minOrNullName: InternedString
    let maxByName: InternedString
    let minName: InternedString
    let maxByOrNullName: InternedString
    let minByOrNullName: InternedString
    let minByName: InternedString
    let maxOfOrNullName: InternedString
    let minOfOrNullName: InternedString
    let maxOfName: InternedString
    let minOfName: InternedString
    let maxWithName: InternedString
    let maxWithOrNullName: InternedString
    let minWithName: InternedString
    let minWithOrNullName: InternedString
    let maxOfWithName: InternedString
    let maxOfWithOrNullName: InternedString
    let minOfWithName: InternedString
    let minOfWithOrNullName: InternedString
    let dropName: InternedString
    let reversedName: InternedString
    let asReversedName: InternedString
    let sortedName: InternedString
    let averageName: InternedString
    let distinctName: InternedString
    let distinctByName: InternedString
    let shuffledName: InternedString
    let flattenName: InternedString
    let indexOfName: InternedString
    let lastIndexOfName: InternedString
    let indexOfFirstName: InternedString
    let indexOfLastName: InternedString
    let chunkedName: InternedString
    let windowedName: InternedString
    let sortedDescendingName: InternedString
    let sortedByDescendingName: InternedString
    let sortedWithName: InternedString
    let partitionName: InternedString
    let takeWhileName: InternedString
    let dropWhileName: InternedString
    let takeLastWhileName: InternedString
    let dropLastWhileName: InternedString
    let firstOrNullName: InternedString
    let lastOrNullName: InternedString
    // FQN arrays for stdlib collection factory functions (STDLIB-410)
    let emptyListFQName: [InternedString]
    let emptyArrayFQName: [InternedString]
    let emptySetFQName: [InternedString]
    let emptyMapFQName: [InternedString]
    let listOfFQName: [InternedString]
    let setOfFQName: [InternedString]
    let setOfNotNullFQName: [InternedString]
    let mapOfFQName: [InternedString]
    let mutableListOfFQName: [InternedString]
    let arrayListOfFQName: [InternedString]
    let mutableSetOfFQName: [InternedString]
    let linkedSetOfFQName: [InternedString]
    let hashSetOfFQName: [InternedString]
    let mutableMapOfFQName: [InternedString]
    let hashMapOfFQName: [InternedString]
    let linkedMapOfFQName: [InternedString]
    let listOfNotNullFQName: [InternedString]
    let kotlinName: InternedString
    let initName: InternedString
    // Pair / `to` infix (FUNC-002)
    let toName: InternedString
    let pairName: InternedString
    let kkPairNewName: InternedString
    let kkPairFirstName: InternedString
    let kkPairSecondName: InternedString
    // Triple (STDLIB-120)
    let tripleName: InternedString
    let kkTripleNewName: InternedString

    init(interner: StringInterner) {
        sumName = interner.intern("sum")
        sizeName = interner.intern("size")
        getName = interner.intern("get")
        containsName = interner.intern("contains")
        containsAllName = interner.intern("containsAll")
        containsKeyName = interner.intern("containsKey")
        containsValueName = interner.intern("containsValue")
        isEmptyName = interner.intern("isEmpty")
        countName = interner.intern("count")
        addName = interner.intern("add")
        removeName = interner.intern("remove")
        firstName = interner.intern("first")
        lastName = interner.intern("last")
        startName = interner.intern("start")
        endInclusiveName = interner.intern("endInclusive")
        endExclusiveName = interner.intern("endExclusive")
        stepName = interner.intern("step")
        iteratorName = interner.intern("iterator")
        mapName = interner.intern("map")
        filterName = interner.intern("filter")
        filterNotName = interner.intern("filterNot")
        mapNotNullName = interner.intern("mapNotNull")
        filterNotNullName = interner.intern("filterNotNull")
        requireNoNullsName = interner.intern("requireNoNulls")
        filterToName = interner.intern("filterTo")
        filterNotToName = interner.intern("filterNotTo")
        mapToName = interner.intern("mapTo")
        flatMapToName = interner.intern("flatMapTo")
        mapNotNullToName = interner.intern("mapNotNullTo")
        mapIndexedToName = interner.intern("mapIndexedTo")
        mapIndexedNotNullToName = interner.intern("mapIndexedNotNullTo")
        flatMapIndexedToName = interner.intern("flatMapIndexedTo")
        filterIsInstanceToName = interner.intern("filterIsInstanceTo")
        filterIndexedToName = interner.intern("filterIndexedTo")
        filterNotNullToName = interner.intern("filterNotNullTo")
        forEachName = interner.intern("forEach")
        flatMapName = interner.intern("flatMap")
        flatMapIndexedName = interner.intern("flatMapIndexed")
        anyName = interner.intern("any")
        noneName = interner.intern("none")
        allName = interner.intern("all")
        foldName = interner.intern("fold")
        foldRightName = interner.intern("foldRight")
        reduceName = interner.intern("reduce")
        reduceRightName = interner.intern("reduceRight")
        reduceOrNullName = interner.intern("reduceOrNull")
        scanName = interner.intern("scan")
        runningFoldName = interner.intern("runningFold")
        runningReduceName = interner.intern("runningReduce")
        scanReduceName = interner.intern("scanReduce")
        groupByName = interner.intern("groupBy")
        sortedByName = interner.intern("sortedBy")
        findName = interner.intern("find")
        findLastName = interner.intern("findLast")
        associateByName = interner.intern("associateBy")
        associateWithName = interner.intern("associateWith")
        associateName = interner.intern("associate")
        associateToName = interner.intern("associateTo")
        associateByToName = interner.intern("associateByTo")
        associateWithToName = interner.intern("associateWithTo")
        groupByToName = interner.intern("groupByTo")
        mapValuesName = interner.intern("mapValues")
        mapValuesToName = interner.intern("mapValuesTo")
        mapKeysName = interner.intern("mapKeys")
        mapKeysToName = interner.intern("mapKeysTo")
        filterKeysName = interner.intern("filterKeys")
        filterValuesName = interner.intern("filterValues")
        zipName = interner.intern("zip")
        zipWithNextName = interner.intern("zipWithNext")
        unzipName = interner.intern("unzip")
        withIndexName = interner.intern("withIndex")
        forEachIndexedName = interner.intern("forEachIndexed")
        onEachName = interner.intern("onEach")
        onEachIndexedName = interner.intern("onEachIndexed")
        mapIndexedName = interner.intern("mapIndexed")
        mapIndexedNotNullName = interner.intern("mapIndexedNotNull")
        foldIndexedName = interner.intern("foldIndexed")
        foldRightIndexedName = interner.intern("foldRightIndexed")
        reduceRightIndexedName = interner.intern("reduceRightIndexed")
        reduceRightIndexedOrNullName = interner.intern("reduceRightIndexedOrNull")
        reduceRightOrNullName = interner.intern("reduceRightOrNull")
        reduceIndexedName = interner.intern("reduceIndexed")
        filterIndexedName = interner.intern("filterIndexed")
        reduceIndexedOrNullName = interner.intern("reduceIndexedOrNull")
        runningFoldIndexedName = interner.intern("runningFoldIndexed")
        runningReduceIndexedName = interner.intern("runningReduceIndexed")
        scanIndexedName = interner.intern("scanIndexed")
        sumOfName = interner.intern("sumOf")
        sumByName = interner.intern("sumBy")
        sumByDoubleName = interner.intern("sumByDouble")
        maxName = interner.intern("max")
        maxOrNullName = interner.intern("maxOrNull")
        minOrNullName = interner.intern("minOrNull")
        maxByName = interner.intern("maxBy")
        minName = interner.intern("min")
        maxByOrNullName = interner.intern("maxByOrNull")
        minByOrNullName = interner.intern("minByOrNull")
        minByName = interner.intern("minBy")
        maxOfOrNullName = interner.intern("maxOfOrNull")
        minOfOrNullName = interner.intern("minOfOrNull")
        maxOfName = interner.intern("maxOf")
        minOfName = interner.intern("minOf")
        maxWithName = interner.intern("maxWith")
        maxWithOrNullName = interner.intern("maxWithOrNull")
        minWithName = interner.intern("minWith")
        minWithOrNullName = interner.intern("minWithOrNull")
        maxOfWithName = interner.intern("maxOfWith")
        maxOfWithOrNullName = interner.intern("maxOfWithOrNull")
        minOfWithName = interner.intern("minOfWith")
        minOfWithOrNullName = interner.intern("minOfWithOrNull")
        dropName = interner.intern("drop")
        reversedName = interner.intern("reversed")
        asReversedName = interner.intern("asReversed")
        sortedName = interner.intern("sorted")
        averageName = interner.intern("average")
        distinctName = interner.intern("distinct")
        distinctByName = interner.intern("distinctBy")
        shuffledName = interner.intern("shuffled")
        flattenName = interner.intern("flatten")
        indexOfName = interner.intern("indexOf")
        lastIndexOfName = interner.intern("lastIndexOf")
        indexOfFirstName = interner.intern("indexOfFirst")
        indexOfLastName = interner.intern("indexOfLast")
        chunkedName = interner.intern("chunked")
        windowedName = interner.intern("windowed")
        sortedDescendingName = interner.intern("sortedDescending")
        sortedByDescendingName = interner.intern("sortedByDescending")
        sortedWithName = interner.intern("sortedWith")
        partitionName = interner.intern("partition")
        takeWhileName = interner.intern("takeWhile")
        dropWhileName = interner.intern("dropWhile")
        takeLastWhileName = interner.intern("takeLastWhile")
        dropLastWhileName = interner.intern("dropLastWhile")
        firstOrNullName = interner.intern("firstOrNull")
        lastOrNullName = interner.intern("lastOrNull")
        let kotlinCollectionsPkg = [interner.intern("kotlin"), interner.intern("collections")]
        emptyListFQName = kotlinCollectionsPkg + [interner.intern("emptyList")]
        emptyArrayFQName = [interner.intern("kotlin")] + [interner.intern("emptyArray")]
        emptySetFQName = kotlinCollectionsPkg + [interner.intern("emptySet")]
        emptyMapFQName = kotlinCollectionsPkg + [interner.intern("emptyMap")]
        listOfFQName = kotlinCollectionsPkg + [interner.intern("listOf")]
        setOfFQName = kotlinCollectionsPkg + [interner.intern("setOf")]
        setOfNotNullFQName = kotlinCollectionsPkg + [interner.intern("setOfNotNull")]
        mapOfFQName = kotlinCollectionsPkg + [interner.intern("mapOf")]
        mutableListOfFQName = kotlinCollectionsPkg + [interner.intern("mutableListOf")]
        arrayListOfFQName = kotlinCollectionsPkg + [interner.intern("arrayListOf")]
        mutableSetOfFQName = kotlinCollectionsPkg + [interner.intern("mutableSetOf")]
        linkedSetOfFQName = kotlinCollectionsPkg + [interner.intern("linkedSetOf")]
        hashSetOfFQName = kotlinCollectionsPkg + [interner.intern("hashSetOf")]
        mutableMapOfFQName = kotlinCollectionsPkg + [interner.intern("mutableMapOf")]
        hashMapOfFQName = kotlinCollectionsPkg + [interner.intern("hashMapOf")]
        linkedMapOfFQName = kotlinCollectionsPkg + [interner.intern("linkedMapOf")]
        listOfNotNullFQName = kotlinCollectionsPkg + [interner.intern("listOfNotNull")]
        kotlinName = interner.intern("kotlin")
        initName = interner.intern("<init>")
        toName = interner.intern("to")
        pairName = interner.intern("Pair")
        kkPairNewName = interner.intern("__kk_pair_new")
        kkPairFirstName = interner.intern("__kk_pair_first")
        kkPairSecondName = interner.intern("__kk_pair_second")
        tripleName = interner.intern("Triple")
        kkTripleNewName = interner.intern("__kk_triple_new")
    }
}
