
struct InlineExpansion {
    let instructions: [KIRInstruction]
    let returnedExpr: KIRExprID?
    /// True when the expansion contains non-local returns that exit the caller.
    let hasNonLocalReturn: Bool
    /// True when the expansion contains normal return terminators (returnValue/returnUnit)
    /// that need to be converted to exit-label jumps in the NLR path.
    let hasNormalReturn: Bool
}

final class InlineLoweringPass: LoweringPass {
    static let name = "InlineLowering"
    /// Counter for generating unique merge labels in inline/lambda body expansions.
    /// Initialized per-function by scanning existing labels to avoid collisions
    /// with labels already present in the caller (or generated by other passes
    /// such as TailrecLoweringPass which shares the 9000 base).
    private var inlineLabelCounter: Int32 = 9000

    private struct InlineTypeSubstitution {
        let substitution: [TypeVarID: TypeID]
        let typeVarBySymbol: [SymbolID: TypeVarID]
    }

    func shouldRun(module: KIRModule, ctx: KIRContext) -> Bool {
        module.ensureFeaturesScanned()
        if module.features.contains(.hasInlineFunction) { return true }
        if let imported = ctx.sema?.importedInlineFunctions, !imported.isEmpty {
            return true
        }
        return false
    }

    func run(module: KIRModule, ctx: KIRContext) throws {
        let unitType = ctx.sema?.types.unitType
        var inlineFunctionsBySymbol = Dictionary(uniqueKeysWithValues: module.arena.declarations.compactMap { decl -> (SymbolID, KIRFunction)? in
            guard case let .function(function) = decl, function.isInline else {
                return nil
            }
            return (function.symbol, function)
        })
        if let imported = ctx.sema?.importedInlineFunctions {
            for (symbol, function) in imported where inlineFunctionsBySymbol[symbol] == nil {
                inlineFunctionsBySymbol[symbol] = function
            }
        }
        let inlineFunctionsByName = Dictionary(grouping: inlineFunctionsBySymbol.values, by: \.name)

        // Build a lookup of all KIR functions by symbol so that lambda bodies
        // can be resolved during inline expansion.
        var allFunctionsBySymbol: [SymbolID: KIRFunction] = [:]
        for decl in module.arena.declarations {
            if case let .function(function) = decl {
                allFunctionsBySymbol[function.symbol] = function
            }
        }

        module.arena.transformFunctions { [self] function in
            inlineTransform(
                function: function,
                inlineFunctionsBySymbol: inlineFunctionsBySymbol,
                inlineFunctionsByName: inlineFunctionsByName,
                allFunctionsBySymbol: allFunctionsBySymbol,
                module: module,
                ctx: ctx,
                unitType: unitType
            )
        }
        module.recordLowering(Self.name)
    }

    /// Compute the next available label ID by scanning all label references in the body.
    /// Returns `maxLabelID + 1`, ensuring no collisions with existing labels.
    /// Labels are allocated dynamically as `maxExistingLabel + 1` (not at a fixed offset).
    private func nextAvailableLabel(in body: [KIRInstruction]) -> Int32 {
        var maxLabel: Int32 = -1
        for instruction in body {
            switch instruction {
            case let .label(id):
                maxLabel = max(maxLabel, id)
            case let .jump(target):
                maxLabel = max(maxLabel, target)
            case let .jumpIfEqual(_, _, target):
                maxLabel = max(maxLabel, target)
            case let .jumpIfNotNull(_, target):
                maxLabel = max(maxLabel, target)
            default:
                break
            }
        }
        return maxLabel + 1
    }

    /// Remap all label IDs (in `.label`, `.jump`, `.jumpIfEqual`, `.jumpIfNotNull`)
    /// in the given instructions so they start at `baseLabel`, preventing collisions
    /// with the caller's existing labels.
    private func remapLabels(
        in instructions: [KIRInstruction],
        baseLabel: Int32
    ) -> (remapped: [KIRInstruction], nextLabel: Int32) {
        // Collect all label IDs used in the expansion.
        var labelIDs = Set<Int32>()
        for inst in instructions {
            switch inst {
            case let .label(id):
                labelIDs.insert(id)
            case let .jump(target):
                labelIDs.insert(target)
            case let .jumpIfEqual(_, _, target):
                labelIDs.insert(target)
            case let .jumpIfNotNull(_, target):
                labelIDs.insert(target)
            default:
                break
            }
        }

        // If there are no labels, no remapping needed.
        guard !labelIDs.isEmpty else {
            return (instructions, baseLabel)
        }

        // Build a mapping from old label -> new label.
        var mapping: [Int32: Int32] = [:]
        var nextLabel = baseLabel
        for id in labelIDs.sorted() {
            mapping[id] = nextLabel
            nextLabel += 1
        }

        // Apply the mapping.
        let remapped = instructions.map { inst -> KIRInstruction in
            switch inst {
            case let .label(id):
                return .label(mapping[id] ?? id)
            case let .jump(target):
                return .jump(mapping[target] ?? target)
            case let .jumpIfEqual(lhs, rhs, target):
                return .jumpIfEqual(lhs: lhs, rhs: rhs, target: mapping[target] ?? target)
            case let .jumpIfNotNull(value, target):
                return .jumpIfNotNull(value: value, target: mapping[target] ?? target)
            default:
                return inst
            }
        }
        return (remapped, nextLabel)
    }

    /// Redirects throw-producing instructions inside an inline/lambda expansion
    /// that are not already routed to a local exception slot (`thrownResult == nil`
    /// on a `canThrow` call, or a bare `.rethrow`) so they no longer rely on the
    /// callee's own function-level auto-propagation (codegen's fallback for
    /// unrouted throws: store into the *current* function's own out-parameter and
    /// return early). Once inlined, "the current function" is the caller, so an
    /// unrouted throw would silently escape the caller instead of reaching its
    /// enclosing try.
    ///
    /// This matters because `appendThrowAwareInstructions` runs on the caller's
    /// try body *before* inlining, when the call to the (later-inlined) function
    /// is still a single opaque `.call`. If that call site was itself protected
    /// by an enclosing try (`callerThrownResult != nil`), any unprotected throw
    /// newly spliced into the caller by inlining must be redirected here so it
    /// still reaches the caller's catch dispatch -- the pre-existing instructions
    /// immediately following this splice point in the caller body.
    ///
    /// Instructions already routed to a local slot (the callee's own try/catch,
    /// or an already-wrapped finally-guard region) are left untouched.
    private func rerouteUnprotectedThrows(
        in instructions: [KIRInstruction],
        callerThrownResult: KIRExprID?,
        nextExitLabel: inout Int32
    ) -> (instructions: [KIRInstruction], trailingLabel: Int32?) {
        guard let callerThrownResult else {
            return (instructions, nil)
        }
        let throwLabel = nextExitLabel
        nextExitLabel += 1
        var result: [KIRInstruction] = []
        result.reserveCapacity(instructions.count)
        var finallyGuardDepth = 0
        for instruction in instructions {
            if case .beginFinallyGuard = instruction {
                finallyGuardDepth += 1
                result.append(instruction)
                continue
            }
            if case .endFinallyGuard = instruction {
                finallyGuardDepth -= 1
                result.append(instruction)
                continue
            }
            if finallyGuardDepth > 0 {
                result.append(instruction)
                continue
            }
            switch instruction {
            case let .call(symbol, callee, arguments, callResult, canThrow, thrownResult, isSuperCall, qualifiedSuperType)
                where canThrow && thrownResult == nil:
                result.append(.call(
                    symbol: symbol,
                    callee: callee,
                    arguments: arguments,
                    result: callResult,
                    canThrow: true,
                    thrownResult: callerThrownResult,
                    isSuperCall: isSuperCall,
                    qualifiedSuperType: qualifiedSuperType
                ))
                result.append(.jumpIfNotNull(value: callerThrownResult, target: throwLabel))
            case let .virtualCall(symbol, callee, receiver, arguments, callResult, canThrow, thrownResult, dispatch)
                where canThrow && thrownResult == nil:
                result.append(.virtualCall(
                    symbol: symbol,
                    callee: callee,
                    receiver: receiver,
                    arguments: arguments,
                    result: callResult,
                    canThrow: true,
                    thrownResult: callerThrownResult,
                    dispatch: dispatch
                ))
                result.append(.jumpIfNotNull(value: callerThrownResult, target: throwLabel))
            case let .rethrow(value):
                result.append(.copy(from: value, to: callerThrownResult))
                result.append(.jump(throwLabel))
            default:
                result.append(instruction)
            }
        }
        return (result, throwLabel)
    }

    private func inlineTransform(
        function: KIRFunction,
        inlineFunctionsBySymbol: [SymbolID: KIRFunction],
        inlineFunctionsByName: [InternedString: [KIRFunction]],
        allFunctionsBySymbol: [SymbolID: KIRFunction],
        module: KIRModule,
        ctx: KIRContext,
        unitType: TypeID?
    ) -> KIRFunction {
        // Scan the function's existing labels so that the inline label counter
        // starts above any label already present in the caller body. This avoids
        // collisions with labels generated by other passes (e.g. TailrecLoweringPass,
        // ControlFlowLowerer) that may share the same numeric range.
        let maxExistingLabel = function.body.compactMap { instruction -> Int32? in
            if case let .label(id) = instruction { return id }
            return nil
        }.max() ?? (9000 - 1)
        inlineLabelCounter = max(9000, maxExistingLabel + 1)

        var updated = function
        var loweredBody: [KIRInstruction] = []
        loweredBody.reserveCapacity(function.body.count)
        var aliases: [KIRExprID: KIRExprID] = [:]

        // Dynamically allocate labels above any existing label in the caller.
        // Labels are allocated as maxExistingLabel + 1 (not at a fixed offset).
        var nextExitLabel = nextAvailableLabel(in: function.body)

        for originalInstruction in function.body {
            let instruction = rewriteInstruction(originalInstruction, aliases: aliases)
            if let defined = definedResult(in: instruction) {
                aliases.removeValue(forKey: defined)
            }

            guard case let .call(symbol, callee, arguments, result, _, callerThrownResult, _, _) = instruction else {
                loweredBody.append(instruction)
                continue
            }

            let resolvedArguments = arguments.map { resolveAlias(of: $0, aliases: aliases) }
            if ["kk_function_invoke", "kk_function_invoke_0", "kk_function_invoke_2", "kk_function_invoke_3", "kk_suspend_function_invoke", "kk_suspend_function_invoke_0"].contains(ctx.interner.resolve(callee)),
               let callableExpr = resolvedArguments.first,
               let lambdaFunction = resolveLambdaFunction(
                   argExpr: callableExpr,
                   arena: module.arena,
                   allFunctionsBySymbol: allFunctionsBySymbol,
                   callerBody: function.body
               )
            {
                let captureArgs = (module.arena.lambdaCaptureArgsBySymbol[lambdaFunction.symbol] ?? [])
                    .map { resolveAlias(of: $0, aliases: aliases) }
                let fullArgs = captureArgs + Array(resolvedArguments.dropFirst())
                if let lambdaExpansion = expandLambdaBody(
                    lambdaFunction: lambdaFunction,
                    arguments: fullArgs,
                    module: module,
                    allFunctionsBySymbol: allFunctionsBySymbol,
                    ctx: ctx
                ) {
                    let (reroutedInstructions, trailingThrowLabel) = rerouteUnprotectedThrows(
                        in: lambdaExpansion.instructions,
                        callerThrownResult: callerThrownResult,
                        nextExitLabel: &nextExitLabel
                    )
                    loweredBody.append(contentsOf: reroutedInstructions)
                    if let trailingThrowLabel {
                        loweredBody.append(.label(trailingThrowLabel))
                    }
                    if let result {
                        if let lambdaReturn = lambdaExpansion.returnedExpr {
                            aliases[result] = resolveAlias(of: lambdaReturn, aliases: aliases)
                        } else if let unitType = unitType {
                            let unitExpr = module.arena.appendExpr(.unit, type: unitType)
                            aliases[result] = unitExpr
                        } else {
                            let unitExpr = module.arena.appendExpr(.unit, type: nil)
                            aliases[result] = unitExpr
                        }
                    }
                    continue
                }
            }

            let inlineTarget: KIRFunction? = if let symbol, let target = inlineFunctionsBySymbol[symbol] {
                target
            } else if let byName = inlineFunctionsByName[callee], byName.count == 1 {
                byName[0]
            } else {
                nil
            }

            guard let inlineTarget, inlineTarget.symbol != function.symbol else {
                loweredBody.append(instruction)
                continue
            }
            let expansion = expandInlineCall(
                inlineTarget: inlineTarget,
                arguments: arguments,
                allFunctionsBySymbol: allFunctionsBySymbol,
                module: module,
                ctx: ctx,
                callerBody: function.body
            )
            guard let expansion else {
                loweredBody.append(instruction)
                continue
            }

            // Remap labels in the expansion into the caller's label namespace
            // to prevent collisions between caller labels and inlined callee labels.
            let (remappedInstructions, nextLabelAfterRemap) = remapLabels(
                in: expansion.instructions,
                baseLabel: nextExitLabel
            )
            nextExitLabel = nextLabelAfterRemap

            // Redirect any throw inside the expansion that isn't already routed to
            // a local exception slot, so it reaches the caller's enclosing try
            // (see `rerouteUnprotectedThrows`) instead of silently escaping the
            // caller via codegen's unrouted-throw auto-propagation.
            let (reroutedInstructions, trailingThrowLabel) = rerouteUnprotectedThrows(
                in: remappedInstructions,
                callerThrownResult: callerThrownResult,
                nextExitLabel: &nextExitLabel
            )

            if expansion.hasNonLocalReturn {
                // The expansion contains non-local returns from lambdas.
                // Rewrite each nonLocalReturn into a real return from the caller.
                // If there is a potential fallthrough path (i.e., the expansion has
                // any normal return terminator), emit an exit label and jump to it
                // so normal control flow continues past the expansion site.

                let hasFallthroughPath = expansion.hasNormalReturn
                let exitLabel: Int32?
                if hasFallthroughPath {
                    exitLabel = nextExitLabel
                    nextExitLabel += 1
                } else {
                    exitLabel = nil
                }

                // Track whether we just emitted a terminator so we can skip
                // unreachable instructions until the next label.
                var afterTerminator = false

                for expandedInstruction in reroutedInstructions {
                    // Skip unreachable instructions after a terminator until
                    // the next label starts a new block.
                    if afterTerminator {
                        if case .label = expandedInstruction {
                            afterTerminator = false
                            loweredBody.append(expandedInstruction)
                        }
                        continue
                    }

                    switch expandedInstruction {
                    case let .nonLocalReturn(value):
                        // Convert to a real return from the caller.
                        if let value {
                            loweredBody.append(.returnValue(resolveAlias(of: value, aliases: aliases)))
                        } else {
                            loweredBody.append(.returnUnit)
                        }
                        afterTerminator = true
                    case .label:
                        // A label starts a new block, so we are no longer after a terminator.
                        loweredBody.append(expandedInstruction)
                    case .returnValue, .returnUnit:
                        // The inline body's own return: jump to exit label instead,
                        // so normal control flow continues in the caller.
                        if let exitLabel {
                            loweredBody.append(.jump(exitLabel))
                        }
                        afterTerminator = true
                    case .returnIfEqual:
                        // returnIfEqual is a conditional normal return from the inline body.
                        // In the NLR path, convert it to a conditional jump to the exit label
                        // to avoid prematurely returning from the caller.
                        if let exitLabel, case let .returnIfEqual(lhs, rhs) = expandedInstruction {
                            loweredBody.append(.jumpIfEqual(lhs: lhs, rhs: rhs, target: exitLabel))
                        }
                        // returnIfEqual is conditional, so it does NOT set afterTerminator.
                    default:
                        loweredBody.append(expandedInstruction)
                    }
                }

                // Only emit the exit label when there is a fallthrough path
                // (avoids unreachable labeled blocks when the expansion always
                // executes nonLocalReturn).
                if let exitLabel {
                    loweredBody.append(.label(exitLabel))
                }
            } else {
                // No non-local returns -- strip returnValue/returnUnit from the
                // expansion (they are only needed for the NLR path exit-label
                // mechanism) and use the original simple expansion path.
                // Labels have already been remapped above; nextExitLabel is up to date.
                let filtered = reroutedInstructions.filter { inst in
                    switch inst {
                    case .returnValue, .returnUnit:
                        return false
                    default:
                        return true
                    }
                }
                loweredBody.append(contentsOf: filtered)
            }

            // If any throw inside the expansion was redirected to the caller's
            // exception slot, land here so the pre-existing caller instructions
            // that follow (from the original call site's throw-aware wrapping)
            // can pick it up and dispatch to the enclosing try's catch/finally.
            if let trailingThrowLabel {
                loweredBody.append(.label(trailingThrowLabel))
            }

            // Alias the call result to the expansion's returned expression (shared
            // for both non-local-return and normal paths).
            if let result {
                if let returnedExpr = expansion.returnedExpr {
                    aliases[result] = resolveAlias(of: returnedExpr, aliases: aliases)
                } else {
                    let unitExpr = module.arena.appendExpr(.unit, type: unitType)
                    aliases[result] = unitExpr
                }
            }
        }

        updated.replaceBody(loweredBody)
        if updated.body.isEmpty {
            updated.replaceBody([.returnUnit])
        }
        return updated
    }

    private func expandInlineCall(
        inlineTarget: KIRFunction,
        arguments: [KIRExprID],
        allFunctionsBySymbol: [SymbolID: KIRFunction],
        module: KIRModule,
        ctx: KIRContext,
        callerBody: [KIRInstruction]
    ) -> InlineExpansion? {
        guard arguments.count == inlineTarget.params.count else {
            return nil
        }

        let parameterValues = Dictionary(uniqueKeysWithValues: zip(inlineTarget.params.map(\.symbol), arguments))

        let typeParamTokenValues = buildTypeParamTokenValues(
            inlineTarget: inlineTarget,
            parameterValues: parameterValues,
            ctx: ctx
        )
        let inlineTypeSubstitution = buildInlineTypeSubstitution(
            inlineTarget: inlineTarget,
            arguments: arguments,
            module: module,
            ctx: ctx
        )
        let substitutedInlineReturnType = substituteInlineType(
            inlineTarget.returnType,
            using: inlineTypeSubstitution,
            ctx: ctx
        )

        // Build a set of parameter symbols that have function types so we can
        // detect calls to lambda parameters inside the inline body.
        let lambdaParamSymbols: Set<SymbolID> = {
            guard let sema = ctx.sema else { return [] }
            var result: Set<SymbolID> = []
            for param in inlineTarget.params {
                if case .functionType = sema.types.kind(of: param.type) {
                    result.insert(param.symbol)
                }
            }
            return result
        }()

        let lambdaParamByCalleeName: [InternedString: SymbolID] = {
            guard let sema = ctx.sema else { return [:] }
            var result: [InternedString: SymbolID] = [:]
            for param in inlineTarget.params {
                if case .functionType = sema.types.kind(of: param.type),
                   let symbolInfo = sema.symbols.symbol(param.symbol) {
                    result[symbolInfo.name] = param.symbol
                }
            }
            return result
        }()

        var localExprMap: [KIRExprID: KIRExprID] = [:]
        var unitResultAliasExprs: Set<KIRExprID> = []
        var lowered: [KIRInstruction] = []
        lowered.reserveCapacity(inlineTarget.body.count)
        var returnedExpr: KIRExprID?
        var hasNonLocalReturn = false
        var hasNormalReturn = false
        let inlineReturnCount = inlineTarget.body.reduce(0) { count, inst in
            switch inst {
            case .returnUnit, .returnValue: return count + 1
            default: return count
            }
        }
        let needsInlineMergeLabel = inlineReturnCount > 1
        let inlineExitLabel: Int32
        var inlineMergeResult: KIRExprID?
        if needsInlineMergeLabel {
            inlineExitLabel = inlineLabelCounter
            inlineLabelCounter += 1
            let hasValueReturn = inlineTarget.body.contains {
                if case .returnValue = $0 { return true }
                return false
            }
            if hasValueReturn {
                inlineMergeResult = module.arena.appendTemporary(type: substitutedInlineReturnType)
            }
        } else {
            inlineExitLabel = -1
        }

        // Build a label remapping so that each inline expansion gets unique
        // label IDs. This prevents collisions when the same function is
        // inlined multiple times or when the inlined labels conflict with
        // labels already present in the caller.
        var labelRemap: [Int32: Int32] = [:]
        for instruction in inlineTarget.body {
            if case let .label(id) = instruction {
                let freshLabel = inlineLabelCounter
                inlineLabelCounter += 1
                labelRemap[id] = freshLabel
            }
        }

        for instruction in inlineTarget.body {
            switch instruction {
            case .beginBlock, .endBlock:
                continue

            case .nop:
                lowered.append(.nop)

            case let .label(id):
                lowered.append(.label(labelRemap[id] ?? id))

            case let .jump(target):
                lowered.append(.jump(labelRemap[target] ?? target))

            case let .jumpIfEqual(lhs, rhs, target):
                lowered.append(
                    .jumpIfEqual(
                        lhs: resolveAlias(of: lhs, aliases: localExprMap),
                        rhs: resolveAlias(of: rhs, aliases: localExprMap),
                        target: labelRemap[target] ?? target
                    )
                )

            case .returnUnit:
                hasNormalReturn = true
                if needsInlineMergeLabel {
                    if inlineMergeResult == nil {
                        returnedExpr = nil
                    }
                    lowered.append(.jump(inlineExitLabel))
                } else {
                    returnedExpr = nil
                    // Preserve in lowered instructions so inlineTransform can
                    // convert it to an exit-label jump in the NLR path.
                    lowered.append(.returnUnit)
                }

            case let .returnValue(value):
                hasNormalReturn = true
                let resolved = resolveAlias(of: value, aliases: localExprMap)
                if needsInlineMergeLabel, let dest = inlineMergeResult {
                    lowered.append(.copy(from: resolved, to: dest))
                    lowered.append(.jump(inlineExitLabel))
                    returnedExpr = dest
                } else {
                    returnedExpr = resolved
                    // Preserve in lowered instructions so inlineTransform can
                    // convert it to an exit-label jump in the NLR path.
                    lowered.append(.returnValue(resolved))
                }

            case let .nonLocalReturn(value):
                // Non-local return from a lambda inside this inline function.
                // Preserve it so the caller's inlineTransform can convert it
                // to a real return from the enclosing function.
                hasNonLocalReturn = true
                if let value {
                    lowered.append(.nonLocalReturn(resolveAlias(of: value, aliases: localExprMap)))
                } else {
                    lowered.append(.nonLocalReturn(nil))
                }

            case let .constValue(result, value):
                if case let .symbolRef(symbol) = value,
                   let mapped = parameterValues[symbol] ?? typeParamTokenValues[symbol]
                {
                    localExprMap[result] = mapped
                    continue
                }
                if case let .symbolRef(symbol) = value,
                   let captureArgs = module.arena.lambdaCaptureArgsBySymbol[symbol],
                   !captureArgs.isEmpty
                {
                    let resolvedCaptureArgs = captureArgs.map { resolveAlias(of: $0, aliases: localExprMap) }
                    module.arena.registerLambdaCaptureArgs(symbol, captureArgs: resolvedCaptureArgs)
                }
                let loweredResult = cloneExpr(result, in: module.arena, typeSubstitution: inlineTypeSubstitution, ctx: ctx)
                localExprMap[result] = loweredResult
                lowered.append(.constValue(result: loweredResult, value: value))

            case let .binary(op, lhs, rhs, result):
                let loweredResult = cloneExpr(result, in: module.arena, typeSubstitution: inlineTypeSubstitution, ctx: ctx)
                localExprMap[result] = loweredResult
                lowered.append(
                    .binary(
                        op: op,
                        lhs: resolveAlias(of: lhs, aliases: localExprMap),
                        rhs: resolveAlias(of: rhs, aliases: localExprMap),
                        result: loweredResult
                    )
                )

            case let .call(symbol, callee, args, result, canThrow, thrownResult, isSuperCall, _):
                // Attempt to inline a lambda argument passed to this inline function.
                let resolvedLambdaParamSymbol: SymbolID? = if let symbol, lambdaParamSymbols.contains(symbol) {
                    symbol
                } else if symbol == nil, let matched = lambdaParamByCalleeName[callee] {
                    matched
                } else {
                    nil
                }
                if let lambdaParamSym = resolvedLambdaParamSymbol,
                   let argExpr = parameterValues[lambdaParamSym],
                   let lambdaFunction = resolveLambdaFunction(
                       argExpr: argExpr,
                       arena: module.arena,
                       allFunctionsBySymbol: allFunctionsBySymbol,
                       callerBody: callerBody
                   )
                {
                    let resolvedArgs = args.map { resolveAlias(of: $0, aliases: localExprMap) }
                    let captureArgs = module.arena.lambdaCaptureArgsBySymbol[lambdaFunction.symbol] ?? []
                    let valueArgs: [KIRExprID]
                    if ["kk_function_invoke", "kk_function_invoke_0", "kk_function_invoke_2", "kk_function_invoke_3", "kk_suspend_function_invoke", "kk_suspend_function_invoke_0"]
                        .contains(ctx.interner.resolve(callee))
                    {
                        valueArgs = Array(resolvedArgs.dropFirst())
                    } else {
                        valueArgs = resolvedArgs
                    }
                    let fullArgs = captureArgs + valueArgs
                    if let lambdaExpansion = expandLambdaBody(
                        lambdaFunction: lambdaFunction,
                        arguments: fullArgs,
                        module: module,
                        allFunctionsBySymbol: allFunctionsBySymbol,
                        ctx: ctx
                    ) {
                        lowered.append(contentsOf: lambdaExpansion.instructions)
                        if let result {
                            if let lambdaReturn = lambdaExpansion.returnedExpr {
                                localExprMap[result] = lambdaReturn
                            } else {
                                let unitExpr = module.arena.appendExpr(.unit, type: nil)
                                lowered.append(.constValue(result: unitExpr, value: .unit))
                                localExprMap[result] = unitExpr
                                unitResultAliasExprs.insert(unitExpr)
                            }
                        }
                        break
                    }
                }

                // A previously inlined function may return a direct lambda symbol.
                // If that symbol still carries capture arguments in the callee's
                // local alias map, inline its body here as well so returned
                // function values preserve their captures.
                let resolvedArgs = args.map { resolveAlias(of: $0, aliases: localExprMap) }
                if ["kk_function_invoke", "kk_function_invoke_0", "kk_function_invoke_2", "kk_function_invoke_3", "kk_suspend_function_invoke", "kk_suspend_function_invoke_0"].contains(ctx.interner.resolve(callee)),
                   let callableExpr = resolvedArgs.first,
                   let lambdaFunction = resolveLambdaFunction(
                       argExpr: callableExpr,
                       arena: module.arena,
                       allFunctionsBySymbol: allFunctionsBySymbol,
                       callerBody: callerBody
                   )
                {
                    let captureArgs = (module.arena.lambdaCaptureArgsBySymbol[lambdaFunction.symbol] ?? [])
                        .map { resolveAlias(of: $0, aliases: localExprMap) }
                    let fullArgs = captureArgs + Array(resolvedArgs.dropFirst())
                    if let lambdaExpansion = expandLambdaBody(
                        lambdaFunction: lambdaFunction,
                        arguments: fullArgs,
                        module: module,
                        allFunctionsBySymbol: allFunctionsBySymbol,
                        ctx: ctx
                    ) {
                        lowered.append(contentsOf: lambdaExpansion.instructions)
                        if let result {
                            if let lambdaReturn = lambdaExpansion.returnedExpr {
                                localExprMap[result] = lambdaReturn
                            } else {
                                let unitExpr = module.arena.appendExpr(.unit, type: nil)
                                lowered.append(.constValue(result: unitExpr, value: .unit))
                                localExprMap[result] = unitExpr
                                unitResultAliasExprs.insert(unitExpr)
                            }
                        }
                        break
                    }
                }

                let loweredResult = result.map { expr -> KIRExprID in
                    let cloned = cloneExpr(expr, in: module.arena, typeSubstitution: inlineTypeSubstitution, ctx: ctx)
                    localExprMap[expr] = cloned
                    return cloned
                }
                let loweredThrownResult = thrownResult.map { expr -> KIRExprID in
                    cloneOrReuseExpr(expr, localExprMap: &localExprMap, module: module, typeSubstitution: inlineTypeSubstitution, ctx: ctx)
                }
                lowered.append(
                    .call(
                        symbol: symbol,
                        callee: callee,
                        arguments: args.map { resolveAlias(of: $0, aliases: localExprMap) },
                        result: loweredResult,
                        canThrow: canThrow,
                        thrownResult: loweredThrownResult,
                        isSuperCall: isSuperCall
                    )
                )

            case let .virtualCall(symbol, callee, receiver, args, result, canThrow, thrownResult, dispatch):
                let loweredResult = result.map { expr -> KIRExprID in
                    let cloned = cloneExpr(expr, in: module.arena, typeSubstitution: inlineTypeSubstitution, ctx: ctx)
                    localExprMap[expr] = cloned
                    return cloned
                }
                let loweredThrownResult = thrownResult.map { expr -> KIRExprID in
                    cloneOrReuseExpr(expr, localExprMap: &localExprMap, module: module, typeSubstitution: inlineTypeSubstitution, ctx: ctx)
                }
                lowered.append(
                    .virtualCall(
                        symbol: symbol,
                        callee: callee,
                        receiver: resolveAlias(of: receiver, aliases: localExprMap),
                        arguments: args.map { resolveAlias(of: $0, aliases: localExprMap) },
                        result: loweredResult,
                        canThrow: canThrow,
                        thrownResult: loweredThrownResult,
                        dispatch: dispatch
                    )
                )

            case let .returnIfEqual(lhs, rhs):
                lowered.append(
                    .returnIfEqual(
                        lhs: resolveAlias(of: lhs, aliases: localExprMap),
                        rhs: resolveAlias(of: rhs, aliases: localExprMap)
                    )
                )

            case let .jumpIfNotNull(value, target):
                lowered.append(
                    .jumpIfNotNull(
                        value: resolveAlias(of: value, aliases: localExprMap),
                        target: labelRemap[target] ?? target
                    )
                )

            case let .copy(from, to):
                let resolvedFrom = resolveAlias(of: from, aliases: localExprMap)
                var resolvedTo = resolveAlias(of: to, aliases: localExprMap)
                if let fromType = module.arena.exprType(resolvedFrom),
                   shouldRetypeInlineCopyTarget(
                       currentType: module.arena.exprType(resolvedTo),
                       fromType: fromType,
                       inlineReturnType: substitutedInlineReturnType,
                       isUnitPlaceholder: unitResultAliasExprs.contains(resolvedTo),
                       ctx: ctx
                   )
                {
                    let replacement = module.arena.appendExpr(
                        module.arena.expr(resolvedTo) ?? .temporary(Int32(module.arena.expressions.count)),
                        type: fromType
                    )
                    let aliasKeysToUpdate = localExprMap.compactMap { key, value in
                        value == resolvedTo ? key : nil
                    }
                    for key in aliasKeysToUpdate {
                        localExprMap[key] = replacement
                    }
                    localExprMap[to] = replacement
                    unitResultAliasExprs.remove(resolvedTo)
                    resolvedTo = replacement
                }
                lowered.append(
                    .copy(
                        from: resolvedFrom,
                        to: resolvedTo
                    )
                )

            case let .storeGlobal(value, symbol):
                lowered.append(
                    .storeGlobal(
                        value: resolveAlias(of: value, aliases: localExprMap),
                        symbol: symbol
                    )
                )

            case let .loadGlobal(result, symbol):
                let loweredResult = cloneExpr(result, in: module.arena, typeSubstitution: inlineTypeSubstitution, ctx: ctx)
                localExprMap[result] = loweredResult
                lowered.append(.loadGlobal(result: loweredResult, symbol: symbol))

            case let .rethrow(value):
                lowered.append(
                    .rethrow(value: resolveAlias(of: value, aliases: localExprMap))
                )

            case let .unary(op, operand, result):
                let loweredResult = cloneExpr(result, in: module.arena, typeSubstitution: inlineTypeSubstitution, ctx: ctx)
                localExprMap[result] = loweredResult
                lowered.append(
                    .unary(
                        op: op,
                        operand: resolveAlias(of: operand, aliases: localExprMap),
                        result: loweredResult
                    )
                )

            case let .nullAssert(operand, result):
                let loweredResult = cloneExpr(result, in: module.arena, typeSubstitution: inlineTypeSubstitution, ctx: ctx)
                localExprMap[result] = loweredResult
                lowered.append(
                    .nullAssert(
                        operand: resolveAlias(of: operand, aliases: localExprMap),
                        result: loweredResult
                    )
                )

            case .beginFinallyGuard:
                lowered.append(.beginFinallyGuard)

            case .endFinallyGuard:
                lowered.append(.endFinallyGuard)
            }
        }

        if needsInlineMergeLabel {
            lowered.append(.label(inlineExitLabel))
        }

        return InlineExpansion(
            instructions: lowered,
            returnedExpr: returnedExpr,
            hasNonLocalReturn: hasNonLocalReturn,
            hasNormalReturn: hasNormalReturn
        )
    }

    // MARK: - Lambda Inlining

    /// Resolve the lambda function for an argument expression. The argument
    /// expression may be a direct `symbolRef` pointing to a lambda KIR function,
    /// or it may be a temporary that was defined via a `constValue` instruction
    /// carrying a `symbolRef` payload. Both patterns are resolved here so that
    /// lambda inlining works regardless of how the call argument was materialized.
    private func resolveLambdaFunction(
        argExpr: KIRExprID,
        arena: KIRArena,
        allFunctionsBySymbol: [SymbolID: KIRFunction],
        callerBody: [KIRInstruction]
    ) -> KIRFunction? {
        // Direct symbolRef on the expression itself (most common path).
        if case let .symbolRef(lambdaSymbol)? = arena.expr(argExpr) {
            if let fn = allFunctionsBySymbol[lambdaSymbol] {
                return fn
            }
        }
        // Fall back: scan the caller body for a constValue that defines this
        // expression with a symbolRef value. This handles cases where the
        // argument is a temporary assigned via `.constValue(result: argExpr,
        // value: .symbolRef(symbol))`.
        for instruction in callerBody {
            if case let .constValue(result, .symbolRef(symbol)) = instruction,
               result == argExpr,
               let fn = allFunctionsBySymbol[symbol]
            {
                return fn
            }
        }
        return nil
    }

    /// Expand a lambda function body inline, substituting parameters with the
    /// provided call arguments. This is analogous to `expandInlineCall` but
    /// operates on non-inline lambda functions that are passed as arguments to
    /// inline functions.
    ///
    /// Returns `nil` when the expansion cannot proceed (e.g. argument/parameter
    /// count mismatch), signalling the caller to fall back to a regular call.
    private func expandLambdaBody(
        lambdaFunction: KIRFunction,
        arguments: [KIRExprID],
        module: KIRModule,
        allFunctionsBySymbol: [SymbolID: KIRFunction],
        ctx: KIRContext
    ) -> InlineExpansion? {
        // Map lambda parameters to arguments. If the argument count does not
        // match the parameter count, skip capture parameters at the front and
        // map only the trailing value parameters.
        var lambdaParamValues: [SymbolID: KIRExprID] = [:]
        let paramCount = lambdaFunction.params.count
        if arguments.count == paramCount {
            for (param, arg) in zip(lambdaFunction.params, arguments) {
                lambdaParamValues[param.symbol] = arg
            }
        } else if arguments.count < paramCount {
            // The call supplies only value arguments; the leading parameters
            // are captures that were already bound at the call site.
            let offset = paramCount - arguments.count
            for i in 0 ..< arguments.count {
                lambdaParamValues[lambdaFunction.params[offset + i].symbol] = arguments[i]
            }
        } else {
            // More arguments than parameters.  This can happen when a
            // receiver-lambda (e.g. `StringBuilder.() -> Unit`) is invoked
            // with the receiver prepended as the first argument.  Map only
            // the trailing parameters and ignore the leading receiver args.
            let offset = arguments.count - paramCount
            for i in 0 ..< paramCount {
                lambdaParamValues[lambdaFunction.params[i].symbol] = arguments[offset + i]
            }
        }

        var localExprMap: [KIRExprID: KIRExprID] = [:]
        var lowered: [KIRInstruction] = []
        lowered.reserveCapacity(lambdaFunction.body.count)
        var returnedExpr: KIRExprID?

        // Count return instructions to decide whether we need a merge label.
        // Lambda bodies with control flow (if/else branches) can contain
        // multiple return instructions; breaking at the first one would
        // truncate the remaining branches.
        let returnCount = lambdaFunction.body.reduce(0) { count, inst in
            switch inst {
            case .returnUnit, .returnValue: return count + 1
            default: return count
            }
        }
        let needsMergeLabel = returnCount > 1
        let exitLabel: Int32
        var mergeResult: KIRExprID?
        if needsMergeLabel {
            exitLabel = inlineLabelCounter
            inlineLabelCounter += 1
            // For value-returning lambdas, allocate a merge expression to
            // hold the returned value from whichever branch executes.
            let hasValueReturn = lambdaFunction.body.contains {
                if case .returnValue = $0 { return true }
                return false
            }
            if hasValueReturn {
                // Allocate a fresh merge temporary for the returned value.
                // Uses the lambda's declared return type so later passes see
                // a properly typed merge expression.
                let returnType = lambdaFunction.returnType
                let mergeID = module.arena.appendTemporary(type: returnType
                )
                mergeResult = mergeID
            }
        } else {
            exitLabel = -1
        }

        // Build a label remapping so that each expansion gets unique label IDs.
        // This prevents collisions when the same lambda is inlined multiple times
        // or when the lambda's labels conflict with labels already in the caller.
        var labelRemap: [Int32: Int32] = [:]
        for instruction in lambdaFunction.body {
            if case let .label(id) = instruction {
                let freshLabel = inlineLabelCounter
                inlineLabelCounter += 1
                labelRemap[id] = freshLabel
            }
        }

        for instruction in lambdaFunction.body {
            switch instruction {
            case .beginBlock, .endBlock:
                continue

            case .nop:
                lowered.append(.nop)

            case let .label(id):
                lowered.append(.label(labelRemap[id] ?? id))

            case let .jump(target):
                lowered.append(.jump(labelRemap[target] ?? target))

            case let .jumpIfEqual(lhs, rhs, target):
                lowered.append(
                    .jumpIfEqual(
                        lhs: resolveAlias(of: lhs, aliases: localExprMap),
                        rhs: resolveAlias(of: rhs, aliases: localExprMap),
                        target: labelRemap[target] ?? target
                    )
                )

            case .returnUnit:
                if needsMergeLabel {
                    if mergeResult == nil {
                        returnedExpr = nil
                    }
                    lowered.append(.jump(exitLabel))
                } else {
                    returnedExpr = nil
                }

            case let .returnValue(value):
                let resolved = resolveAlias(of: value, aliases: localExprMap)
                if needsMergeLabel, let dest = mergeResult {
                    lowered.append(.copy(from: resolved, to: dest))
                    lowered.append(.jump(exitLabel))
                    returnedExpr = dest
                } else {
                    returnedExpr = resolved
                }

            case let .constValue(result, value):
                if case let .symbolRef(symbol) = value,
                   let mapped = lambdaParamValues[symbol]
                {
                    localExprMap[result] = mapped
                    continue
                }
                let loweredResult = cloneExpr(result, in: module.arena)
                localExprMap[result] = loweredResult
                lowered.append(.constValue(result: loweredResult, value: value))

            case let .binary(op, lhs, rhs, result):
                let loweredResult = cloneExpr(result, in: module.arena)
                localExprMap[result] = loweredResult
                lowered.append(
                    .binary(
                        op: op,
                        lhs: resolveAlias(of: lhs, aliases: localExprMap),
                        rhs: resolveAlias(of: rhs, aliases: localExprMap),
                        result: loweredResult
                    )
                )

            case let .call(symbol, callee, args, result, canThrow, thrownResult, isSuperCall, _):
                let resolvedArgs = args.map { resolveAlias(of: $0, aliases: localExprMap) }
                if ["kk_function_invoke", "kk_function_invoke_0", "kk_function_invoke_2", "kk_function_invoke_3", "kk_suspend_function_invoke", "kk_suspend_function_invoke_0"].contains(ctx.interner.resolve(callee)),
                   let callableExpr = resolvedArgs.first,
                   let nestedLambdaFunction = resolveLambdaFunction(
                       argExpr: callableExpr,
                       arena: module.arena,
                       allFunctionsBySymbol: allFunctionsBySymbol,
                       callerBody: lambdaFunction.body
                   )
                {
                    let captureArgs = (module.arena.lambdaCaptureArgsBySymbol[nestedLambdaFunction.symbol] ?? [])
                        .map { resolveAlias(of: $0, aliases: localExprMap) }
                    let fullArgs = captureArgs + Array(resolvedArgs.dropFirst())
                    if let lambdaExpansion = expandLambdaBody(
                        lambdaFunction: nestedLambdaFunction,
                        arguments: fullArgs,
                        module: module,
                        allFunctionsBySymbol: allFunctionsBySymbol,
                        ctx: ctx
                    ) {
                        lowered.append(contentsOf: lambdaExpansion.instructions)
                        if let result {
                            if let lambdaReturn = lambdaExpansion.returnedExpr {
                                localExprMap[result] = lambdaReturn
                            } else {
                                let unitExpr = module.arena.appendExpr(.unit, type: nil)
                                lowered.append(.constValue(result: unitExpr, value: .unit))
                                localExprMap[result] = unitExpr
                            }
                        }
                        break
                    }
                }
                let loweredResult = result.map { expr -> KIRExprID in
                    let cloned = cloneExpr(expr, in: module.arena)
                    localExprMap[expr] = cloned
                    return cloned
                }
                let loweredThrownResult = thrownResult.map { expr -> KIRExprID in
                    cloneOrReuseExpr(expr, localExprMap: &localExprMap, module: module)
                }
                lowered.append(
                    .call(
                        symbol: symbol,
                        callee: callee,
                        arguments: resolvedArgs,
                        result: loweredResult,
                        canThrow: canThrow,
                        thrownResult: loweredThrownResult,
                        isSuperCall: isSuperCall
                    )
                )

            case let .virtualCall(symbol, callee, receiver, args, result, canThrow, thrownResult, dispatch):
                let loweredResult = result.map { expr -> KIRExprID in
                    let cloned = cloneExpr(expr, in: module.arena)
                    localExprMap[expr] = cloned
                    return cloned
                }
                let loweredThrownResult = thrownResult.map { expr -> KIRExprID in
                    cloneOrReuseExpr(expr, localExprMap: &localExprMap, module: module)
                }
                lowered.append(
                    .virtualCall(
                        symbol: symbol,
                        callee: callee,
                        receiver: resolveAlias(of: receiver, aliases: localExprMap),
                        arguments: args.map { resolveAlias(of: $0, aliases: localExprMap) },
                        result: loweredResult,
                        canThrow: canThrow,
                        thrownResult: loweredThrownResult,
                        dispatch: dispatch
                    )
                )

            case let .returnIfEqual(lhs, rhs):
                lowered.append(
                    .returnIfEqual(
                        lhs: resolveAlias(of: lhs, aliases: localExprMap),
                        rhs: resolveAlias(of: rhs, aliases: localExprMap)
                    )
                )

            case let .jumpIfNotNull(value, target):
                lowered.append(
                    .jumpIfNotNull(
                        value: resolveAlias(of: value, aliases: localExprMap),
                        target: labelRemap[target] ?? target
                    )
                )

            case let .copy(from, to):
                lowered.append(
                    .copy(
                        from: resolveAlias(of: from, aliases: localExprMap),
                        to: resolveAlias(of: to, aliases: localExprMap)
                    )
                )

            case let .storeGlobal(value, symbol):
                lowered.append(
                    .storeGlobal(
                        value: resolveAlias(of: value, aliases: localExprMap),
                        symbol: symbol
                    )
                )

            case let .loadGlobal(result, symbol):
                let loweredResult = cloneExpr(result, in: module.arena)
                localExprMap[result] = loweredResult
                lowered.append(.loadGlobal(result: loweredResult, symbol: symbol))

            case let .rethrow(value):
                lowered.append(
                    .rethrow(value: resolveAlias(of: value, aliases: localExprMap))
                )

            case let .unary(op, operand, result):
                let loweredResult = cloneExpr(result, in: module.arena)
                localExprMap[result] = loweredResult
                lowered.append(
                    .unary(
                        op: op,
                        operand: resolveAlias(of: operand, aliases: localExprMap),
                        result: loweredResult
                    )
                )

            case let .nullAssert(operand, result):
                let loweredResult = cloneExpr(result, in: module.arena)
                localExprMap[result] = loweredResult
                lowered.append(
                    .nullAssert(
                        operand: resolveAlias(of: operand, aliases: localExprMap),
                        result: loweredResult
                    )
                )

            case let .nonLocalReturn(value):
                // Non-local return from a nested lambda. Preserve it so the
                // caller's inlineTransform can convert it to a real return.
                if let value {
                    lowered.append(.nonLocalReturn(resolveAlias(of: value, aliases: localExprMap)))
                } else {
                    lowered.append(.nonLocalReturn(nil))
                }

            case .beginFinallyGuard:
                lowered.append(.beginFinallyGuard)

            case .endFinallyGuard:
                lowered.append(.endFinallyGuard)
            }
        }

        // Emit merge label so all branches converge after the inlined body.
        if needsMergeLabel {
            lowered.append(.label(exitLabel))
        }

        return InlineExpansion(
            instructions: lowered,
            returnedExpr: returnedExpr,
            hasNonLocalReturn: false,
            hasNormalReturn: false
        )
    }

    private func buildTypeParamTokenValues(
        inlineTarget: KIRFunction,
        parameterValues: [SymbolID: KIRExprID],
        ctx: KIRContext
    ) -> [SymbolID: KIRExprID] {
        guard let sema = ctx.sema,
              let sig = sema.symbols.functionSignature(for: inlineTarget.symbol),
              !sig.reifiedTypeParameterIndices.isEmpty
        else {
            return [:]
        }
        var result: [SymbolID: KIRExprID] = [:]
        for index in sig.reifiedTypeParameterIndices.sorted() {
            guard index < sig.typeParameterSymbols.count else { continue }
            let typeParamSymbol = sig.typeParameterSymbols[index]
            let tokenSymbol = SyntheticSymbolScheme.reifiedTypeTokenSymbol(for: typeParamSymbol)
            if let tokenArg = parameterValues[tokenSymbol] {
                result[typeParamSymbol] = tokenArg
            }
        }
        return result
    }

    private func rewriteInstruction(_ instruction: KIRInstruction, aliases: [KIRExprID: KIRExprID]) -> KIRInstruction {
        switch instruction {
        case let .binary(op, lhs, rhs, result):
            .binary(
                op: op,
                lhs: resolveAlias(of: lhs, aliases: aliases),
                rhs: resolveAlias(of: rhs, aliases: aliases),
                result: result
            )

        case let .call(symbol, callee, arguments, result, canThrow, thrownResult, isSuperCall, qualifiedSuperType):
            .call(
                symbol: symbol,
                callee: callee,
                arguments: arguments.map { resolveAlias(of: $0, aliases: aliases) },
                result: result,
                canThrow: canThrow,
                thrownResult: thrownResult,
                isSuperCall: isSuperCall,
                qualifiedSuperType: qualifiedSuperType
            )

        case let .virtualCall(symbol, callee, receiver, arguments, result, canThrow, thrownResult, dispatch):
            .virtualCall(
                symbol: symbol,
                callee: callee,
                receiver: resolveAlias(of: receiver, aliases: aliases),
                arguments: arguments.map { resolveAlias(of: $0, aliases: aliases) },
                result: result,
                canThrow: canThrow,
                thrownResult: thrownResult,
                dispatch: dispatch
            )

        case let .returnValue(value):
            .returnValue(resolveAlias(of: value, aliases: aliases))

        case let .nonLocalReturn(value):
            .nonLocalReturn(value.map { resolveAlias(of: $0, aliases: aliases) })

        case let .returnIfEqual(lhs, rhs):
            .returnIfEqual(
                lhs: resolveAlias(of: lhs, aliases: aliases),
                rhs: resolveAlias(of: rhs, aliases: aliases)
            )

        case let .jumpIfEqual(lhs, rhs, target):
            .jumpIfEqual(
                lhs: resolveAlias(of: lhs, aliases: aliases),
                rhs: resolveAlias(of: rhs, aliases: aliases),
                target: target
            )

        case let .jumpIfNotNull(value, target):
            .jumpIfNotNull(
                value: resolveAlias(of: value, aliases: aliases),
                target: target
            )

        case let .copy(from, to):
            .copy(
                from: resolveAlias(of: from, aliases: aliases),
                to: resolveAlias(of: to, aliases: aliases)
            )

        case let .rethrow(value):
            .rethrow(value: resolveAlias(of: value, aliases: aliases))

        case let .unary(op, operand, result):
            .unary(
                op: op,
                operand: resolveAlias(of: operand, aliases: aliases),
                result: result
            )

        case let .nullAssert(operand, result):
            .nullAssert(
                operand: resolveAlias(of: operand, aliases: aliases),
                result: result
            )

        case let .storeGlobal(value, symbol):
            .storeGlobal(
                value: resolveAlias(of: value, aliases: aliases),
                symbol: symbol
            )

        case .loadGlobal:
            instruction

        default:
            instruction
        }
    }

    private func definedResult(in instruction: KIRInstruction) -> KIRExprID? {
        switch instruction {
        case let .constValue(result, _):
            result
        case let .binary(_, _, _, result):
            result
        case let .call(_, _, _, result, _, _, _, _):
            result
        case let .virtualCall(_, _, _, _, result, _, _, _):
            result
        case let .unary(_, _, result):
            result
        case let .nullAssert(_, result):
            result
        case let .loadGlobal(result, _):
            result
        default:
            nil
        }
    }

    private func resolveAlias(of expr: KIRExprID, aliases: [KIRExprID: KIRExprID]) -> KIRExprID {
        var current = expr
        var visited: Set<KIRExprID> = []
        while let next = aliases[current], visited.insert(current).inserted {
            if next == current {
                break
            }
            current = next
        }
        return current
    }

    /// Clones `source` into a fresh caller-scoped expression the first time it is
    /// encountered within a single inline expansion, and returns that same clone
    /// for every later occurrence of `source`. Used only for a call's
    /// `thrownResult`, because that is the sole field where the callee's own KIR
    /// intentionally reuses one physical expression -- a try/catch's shared
    /// exception slot -- as the `thrownResult` of every protected call inside the
    /// same try body (see ControlFlowLowerer.appendThrowAwareInstructions, which
    /// rewrites each protected call's `thrownResult` to the same pre-allocated
    /// `exceptionSlot`, while leaving `result` untouched). Cloning that slot
    /// independently on each occurrence would fragment one physical register into
    /// several disconnected ones, losing track of writes made through earlier
    /// clones.
    ///
    /// `result` is deliberately NOT routed through this helper: it is always
    /// cloned unconditionally (matching pre-existing behavior), because a call's
    /// `result` is a freshly allocated, unique KIRExprID under the standard
    /// ExprLowerer/CallLowerer/ControlFlowLowerer pipeline that produces every
    /// inline-function and lambda body this pass expands -- the only other KIR
    /// producers that intentionally share a `result` id across multiple calls
    /// (e.g. the synthesized data-class `toString()` StringBuilder accumulator,
    /// interface-delegation forwarding methods) always mark their function
    /// `isInline: false` and are never lambda closures, so they are unreachable
    /// from both `expandInlineCall` (gated on `isInline`) and `expandLambdaBody`
    /// (reachable only through `resolveLambdaFunction`, which only resolves
    /// genuine lambda closures).
    private func cloneOrReuseExpr(
        _ source: KIRExprID,
        localExprMap: inout [KIRExprID: KIRExprID],
        module: KIRModule,
        typeSubstitution: InlineTypeSubstitution?,
        ctx: KIRContext
    ) -> KIRExprID {
        if let existing = localExprMap[source] {
            return existing
        }
        let cloned = cloneExpr(source, in: module.arena, typeSubstitution: typeSubstitution, ctx: ctx)
        localExprMap[source] = cloned
        return cloned
    }

    /// Lambda-body variant of `cloneOrReuseExpr(_:localExprMap:module:typeSubstitution:ctx:)`
    /// (lambda expansion has no inline type substitution to apply).
    private func cloneOrReuseExpr(
        _ source: KIRExprID,
        localExprMap: inout [KIRExprID: KIRExprID],
        module: KIRModule
    ) -> KIRExprID {
        if let existing = localExprMap[source] {
            return existing
        }
        let cloned = cloneExpr(source, in: module.arena)
        localExprMap[source] = cloned
        return cloned
    }

    private func buildInlineTypeSubstitution(
        inlineTarget: KIRFunction,
        arguments: [KIRExprID],
        module: KIRModule,
        ctx: KIRContext
    ) -> InlineTypeSubstitution? {
        guard let sema = ctx.sema,
              let signature = sema.symbols.functionSignature(for: inlineTarget.symbol),
              !signature.typeParameterSymbols.isEmpty
        else {
            return nil
        }

        let typeVarBySymbol = sema.types.makeTypeVarBySymbol(signature.typeParameterSymbols)
        var substitution: [TypeVarID: TypeID] = [:]
        for (parameter, argument) in zip(inlineTarget.params, arguments) {
            guard let argumentType = module.arena.exprType(argument) else {
                continue
            }
            collectInlineTypeSubstitution(
                expected: parameter.type,
                actual: argumentType,
                sema: sema,
                typeVarBySymbol: typeVarBySymbol,
                substitution: &substitution
            )
        }
        guard !substitution.isEmpty else {
            return nil
        }
        return InlineTypeSubstitution(substitution: substitution, typeVarBySymbol: typeVarBySymbol)
    }

    private func collectInlineTypeSubstitution(
        expected: TypeID,
        actual: TypeID,
        sema: SemaModule,
        typeVarBySymbol: [SymbolID: TypeVarID],
        substitution: inout [TypeVarID: TypeID]
    ) {
        switch sema.types.kind(of: expected) {
        case let .typeParam(typeParam):
            guard let typeVar = typeVarBySymbol[typeParam.symbol],
                  substitution[typeVar] == nil
            else {
                return
            }
            substitution[typeVar] = actual

        case let .classType(expectedClass):
            guard let actualClass = resolveClassType(actual, sema: sema),
                  expectedClass.classSymbol == actualClass.classSymbol
            else {
                return
            }
            for (expectedArg, actualArg) in zip(expectedClass.args, actualClass.args) {
                guard let expectedInner = inlineTypeArgPayload(expectedArg),
                      let actualInner = inlineTypeArgPayload(actualArg)
                else {
                    continue
                }
                collectInlineTypeSubstitution(
                    expected: expectedInner,
                    actual: actualInner,
                    sema: sema,
                    typeVarBySymbol: typeVarBySymbol,
                    substitution: &substitution
                )
            }

        case let .functionType(expectedFunction):
            guard case let .functionType(actualFunction) = sema.types.kind(of: sema.types.makeNonNullable(actual)) else {
                return
            }
            if let expectedReceiver = expectedFunction.receiver,
               let actualReceiver = actualFunction.receiver
            {
                collectInlineTypeSubstitution(
                    expected: expectedReceiver,
                    actual: actualReceiver,
                    sema: sema,
                    typeVarBySymbol: typeVarBySymbol,
                    substitution: &substitution
                )
            }
            for (expectedParam, actualParam) in zip(expectedFunction.params, actualFunction.params) {
                collectInlineTypeSubstitution(
                    expected: expectedParam,
                    actual: actualParam,
                    sema: sema,
                    typeVarBySymbol: typeVarBySymbol,
                    substitution: &substitution
                )
            }
            collectInlineTypeSubstitution(
                expected: expectedFunction.returnType,
                actual: actualFunction.returnType,
                sema: sema,
                typeVarBySymbol: typeVarBySymbol,
                substitution: &substitution
            )

        case let .kClassType(expectedKClass):
            guard case let .kClassType(actualKClass) = sema.types.kind(of: sema.types.makeNonNullable(actual)) else {
                return
            }
            collectInlineTypeSubstitution(
                expected: expectedKClass.argument,
                actual: actualKClass.argument,
                sema: sema,
                typeVarBySymbol: typeVarBySymbol,
                substitution: &substitution
            )

        default:
            return
        }
    }

    private func inlineTypeArgPayload(_ arg: TypeArg) -> TypeID? {
        switch arg {
        case let .invariant(type), let .out(type), let .in(type):
            return type
        case .star:
            return nil
        }
    }

    private func substituteInlineType(
        _ type: TypeID?,
        using inlineTypeSubstitution: InlineTypeSubstitution?,
        ctx: KIRContext
    ) -> TypeID? {
        guard let type,
              let inlineTypeSubstitution,
              let sema = ctx.sema
        else {
            return type
        }
        return sema.types.substituteTypeParameters(
            in: type,
            substitution: inlineTypeSubstitution.substitution,
            typeVarBySymbol: inlineTypeSubstitution.typeVarBySymbol
        )
    }

    private func isInlineUnitType(_ type: TypeID, ctx: KIRContext) -> Bool {
        guard let sema = ctx.sema else {
            return false
        }
        if type == sema.types.unitType {
            return true
        }
        if case .unit = sema.types.kind(of: type) {
            return true
        }
        return false
    }

    private func shouldRetypeInlineCopyTarget(
        currentType: TypeID?,
        fromType: TypeID,
        inlineReturnType: TypeID?,
        isUnitPlaceholder: Bool,
        ctx: KIRContext
    ) -> Bool {
        if isUnitPlaceholder {
            return !isInlineUnitType(fromType, ctx: ctx)
        }
        guard let inlineReturnType,
              fromType == inlineReturnType,
              currentType != fromType
        else {
            return false
        }
        if let currentType {
            return isInlineUnitType(currentType, ctx: ctx) || currentType != inlineReturnType
        }
        return true
    }

    private func cloneExpr(
        _ source: KIRExprID,
        in arena: KIRArena,
        typeSubstitution: InlineTypeSubstitution?,
        ctx: KIRContext
    ) -> KIRExprID {
        let fallback = KIRExprKind.temporary(Int32(arena.expressions.count))
        return arena.appendExpr(
            arena.expr(source) ?? fallback,
            type: substituteInlineType(arena.exprType(source), using: typeSubstitution, ctx: ctx)
        )
    }

    private func cloneExpr(_ source: KIRExprID, in arena: KIRArena) -> KIRExprID {
        let type = arena.exprType(source)
        guard let expr = arena.expr(source) else {
            return arena.appendTemporary(type: type)
        }
        return arena.appendExpr(expr, type: type)
    }
}
