import Foundation

struct InlineExpansion {
    let instructions: [KIRInstruction]
    let returnedExpr: KIRExprID?
    /// True when the expansion contains non-local returns that exit the caller.
    let hasNonLocalReturn: Bool
    /// True when the expansion contains normal return terminators (returnValue/returnUnit)
    /// that need to be converted to exit-label jumps in the NLR path.
    let hasNormalReturn: Bool
}

final class InlineLoweringPass: LoweringPass {
    static let name = "InlineLowering"
    /// Counter for generating unique merge labels in inline/lambda body expansions.
    /// Initialized per-function by scanning existing labels to avoid collisions
    /// with labels already present in the caller (or generated by other passes
    /// such as TailrecLoweringPass which shares the 9000 base).
    private var inlineLabelCounter: Int32 = 9000

    func shouldRun(module: KIRModule, ctx: KIRContext) -> Bool {
        for decl in module.arena.declarations {
            if case let .function(function) = decl, function.isInline {
                return true
            }
        }
        if let imported = ctx.sema?.importedInlineFunctions, !imported.isEmpty {
            return true
        }
        return false
    }

    func run(module: KIRModule, ctx: KIRContext) throws {
        let unitType = ctx.sema?.types.unitType
        var inlineFunctionsBySymbol = Dictionary(uniqueKeysWithValues: module.arena.declarations.compactMap { decl -> (SymbolID, KIRFunction)? in
            guard case let .function(function) = decl, function.isInline else {
                return nil
            }
            return (function.symbol, function)
        })
        if let imported = ctx.sema?.importedInlineFunctions {
            for (symbol, function) in imported where inlineFunctionsBySymbol[symbol] == nil {
                inlineFunctionsBySymbol[symbol] = function
            }
        }
        let inlineFunctionsByName = Dictionary(grouping: inlineFunctionsBySymbol.values, by: \.name)

        // Build a lookup of all KIR functions by symbol so that lambda bodies
        // can be resolved during inline expansion.
        var allFunctionsBySymbol: [SymbolID: KIRFunction] = [:]
        for decl in module.arena.declarations {
            if case let .function(function) = decl {
                allFunctionsBySymbol[function.symbol] = function
            }
        }

        module.arena.transformFunctions { [self] function in
            inlineTransform(
                function: function,
                inlineFunctionsBySymbol: inlineFunctionsBySymbol,
                inlineFunctionsByName: inlineFunctionsByName,
                allFunctionsBySymbol: allFunctionsBySymbol,
                module: module,
                ctx: ctx,
                unitType: unitType
            )
        }
        module.recordLowering(Self.name)
    }

    /// Compute the next available label ID by scanning all label references in the body.
    /// Returns `maxLabelID + 1`, ensuring no collisions with existing labels.
    /// Labels are allocated dynamically as `maxExistingLabel + 1` (not at a fixed offset).
    private func nextAvailableLabel(in body: [KIRInstruction]) -> Int32 {
        var maxLabel: Int32 = -1
        for instruction in body {
            switch instruction {
            case let .label(id):
                maxLabel = max(maxLabel, id)
            case let .jump(target):
                maxLabel = max(maxLabel, target)
            case let .jumpIfEqual(_, _, target):
                maxLabel = max(maxLabel, target)
            case let .jumpIfNotNull(_, target):
                maxLabel = max(maxLabel, target)
            default:
                break
            }
        }
        return maxLabel + 1
    }

    /// Remap all label IDs (in `.label`, `.jump`, `.jumpIfEqual`, `.jumpIfNotNull`)
    /// in the given instructions so they start at `baseLabel`, preventing collisions
    /// with the caller's existing labels.
    private func remapLabels(
        in instructions: [KIRInstruction],
        baseLabel: Int32
    ) -> (remapped: [KIRInstruction], nextLabel: Int32) {
        // Collect all label IDs used in the expansion.
        var labelIDs = Set<Int32>()
        for inst in instructions {
            switch inst {
            case let .label(id):
                labelIDs.insert(id)
            case let .jump(target):
                labelIDs.insert(target)
            case let .jumpIfEqual(_, _, target):
                labelIDs.insert(target)
            case let .jumpIfNotNull(_, target):
                labelIDs.insert(target)
            default:
                break
            }
        }

        // If there are no labels, no remapping needed.
        guard !labelIDs.isEmpty else {
            return (instructions, baseLabel)
        }

        // Build a mapping from old label -> new label.
        var mapping: [Int32: Int32] = [:]
        var nextLabel = baseLabel
        for id in labelIDs.sorted() {
            mapping[id] = nextLabel
            nextLabel += 1
        }

        // Apply the mapping.
        let remapped = instructions.map { inst -> KIRInstruction in
            switch inst {
            case let .label(id):
                return .label(mapping[id] ?? id)
            case let .jump(target):
                return .jump(mapping[target] ?? target)
            case let .jumpIfEqual(lhs, rhs, target):
                return .jumpIfEqual(lhs: lhs, rhs: rhs, target: mapping[target] ?? target)
            case let .jumpIfNotNull(value, target):
                return .jumpIfNotNull(value: value, target: mapping[target] ?? target)
            default:
                return inst
            }
        }
        return (remapped, nextLabel)
    }

    private func inlineTransform(
        function: KIRFunction,
        inlineFunctionsBySymbol: [SymbolID: KIRFunction],
        inlineFunctionsByName: [InternedString: [KIRFunction]],
        allFunctionsBySymbol: [SymbolID: KIRFunction],
        module: KIRModule,
        ctx: KIRContext,
        unitType: TypeID?
    ) -> KIRFunction {
        // Scan the function's existing labels so that the inline label counter
        // starts above any label already present in the caller body. This avoids
        // collisions with labels generated by other passes (e.g. TailrecLoweringPass,
        // ControlFlowLowerer) that may share the same numeric range.
        let maxExistingLabel = function.body.compactMap { instruction -> Int32? in
            if case let .label(id) = instruction { return id }
            return nil
        }.max() ?? (9000 - 1)
        inlineLabelCounter = max(9000, maxExistingLabel + 1)

        var updated = function
        var loweredBody: [KIRInstruction] = []
        loweredBody.reserveCapacity(function.body.count)
        var aliases: [KIRExprID: KIRExprID] = [:]

        // Dynamically allocate labels above any existing label in the caller.
        // Labels are allocated as maxExistingLabel + 1 (not at a fixed offset).
        var nextExitLabel = nextAvailableLabel(in: function.body)

        for originalInstruction in function.body {
            let instruction = rewriteInstruction(originalInstruction, aliases: aliases)
            if let defined = definedResult(in: instruction) {
                aliases.removeValue(forKey: defined)
            }

            guard case let .call(symbol, callee, arguments, result, _, _, _) = instruction else {
                loweredBody.append(instruction)
                continue
            }

            let inlineTarget: KIRFunction? = if let symbol, let target = inlineFunctionsBySymbol[symbol] {
                target
            } else if let byName = inlineFunctionsByName[callee], byName.count == 1 {
                byName[0]
            } else {
                nil
            }

            guard let inlineTarget, inlineTarget.symbol != function.symbol else {
                loweredBody.append(instruction)
                continue
            }
            let expansion = expandInlineCall(
                inlineTarget: inlineTarget,
                arguments: arguments,
                allFunctionsBySymbol: allFunctionsBySymbol,
                module: module,
                ctx: ctx,
                callerBody: function.body
            )
            guard let expansion else {
                loweredBody.append(instruction)
                continue
            }

            // Remap labels in the expansion into the caller's label namespace
            // to prevent collisions between caller labels and inlined callee labels.
            let (remappedInstructions, nextLabelAfterRemap) = remapLabels(
                in: expansion.instructions,
                baseLabel: nextExitLabel
            )
            nextExitLabel = nextLabelAfterRemap

            if expansion.hasNonLocalReturn {
                // The expansion contains non-local returns from lambdas.
                // Rewrite each nonLocalReturn into a real return from the caller.
                // If there is a potential fallthrough path (i.e., the expansion has
                // any normal return terminator), emit an exit label and jump to it
                // so normal control flow continues past the expansion site.

                let hasFallthroughPath = expansion.hasNormalReturn
                let exitLabel: Int32?
                if hasFallthroughPath {
                    exitLabel = nextExitLabel
                    nextExitLabel += 1
                } else {
                    exitLabel = nil
                }

                // Track whether we just emitted a terminator so we can skip
                // unreachable instructions until the next label.
                var afterTerminator = false

                for expandedInstruction in remappedInstructions {
                    // Skip unreachable instructions after a terminator until
                    // the next label starts a new block.
                    if afterTerminator {
                        if case .label = expandedInstruction {
                            afterTerminator = false
                            loweredBody.append(expandedInstruction)
                        }
                        continue
                    }

                    switch expandedInstruction {
                    case let .nonLocalReturn(value):
                        // Convert to a real return from the caller.
                        if let value {
                            loweredBody.append(.returnValue(resolveAlias(of: value, aliases: aliases)))
                        } else {
                            loweredBody.append(.returnUnit)
                        }
                        afterTerminator = true
                    case .label:
                        // A label starts a new block, so we are no longer after a terminator.
                        loweredBody.append(expandedInstruction)
                    case .returnValue, .returnUnit:
                        // The inline body's own return: jump to exit label instead,
                        // so normal control flow continues in the caller.
                        if let exitLabel {
                            loweredBody.append(.jump(exitLabel))
                        }
                        afterTerminator = true
                    case .returnIfEqual:
                        // returnIfEqual is a conditional normal return from the inline body.
                        // In the NLR path, convert it to a conditional jump to the exit label
                        // to avoid prematurely returning from the caller.
                        if let exitLabel, case let .returnIfEqual(lhs, rhs) = expandedInstruction {
                            loweredBody.append(.jumpIfEqual(lhs: lhs, rhs: rhs, target: exitLabel))
                        }
                        // returnIfEqual is conditional, so it does NOT set afterTerminator.
                    default:
                        loweredBody.append(expandedInstruction)
                    }
                }

                // Only emit the exit label when there is a fallthrough path
                // (avoids unreachable labeled blocks when the expansion always
                // executes nonLocalReturn).
                if let exitLabel {
                    loweredBody.append(.label(exitLabel))
                }
            } else {
                // No non-local returns -- strip returnValue/returnUnit from the
                // expansion (they are only needed for the NLR path exit-label
                // mechanism) and use the original simple expansion path.
                // Labels have already been remapped above; nextExitLabel is up to date.
                let filtered = remappedInstructions.filter { inst in
                    switch inst {
                    case .returnValue, .returnUnit:
                        return false
                    default:
                        return true
                    }
                }
                loweredBody.append(contentsOf: filtered)
            }

            // Alias the call result to the expansion's returned expression (shared
            // for both non-local-return and normal paths).
            if let result {
                if let returnedExpr = expansion.returnedExpr {
                    aliases[result] = resolveAlias(of: returnedExpr, aliases: aliases)
                } else {
                    let unitExpr = module.arena.appendExpr(.unit, type: unitType)
                    aliases[result] = unitExpr
                }
            }
        }

        updated.replaceBody(loweredBody)
        if updated.body.isEmpty {
            updated.replaceBody([.returnUnit])
        }
        return updated
    }

    private func expandInlineCall(
        inlineTarget: KIRFunction,
        arguments: [KIRExprID],
        allFunctionsBySymbol: [SymbolID: KIRFunction],
        module: KIRModule,
        ctx: KIRContext,
        callerBody: [KIRInstruction]
    ) -> InlineExpansion? {
        guard arguments.count == inlineTarget.params.count else {
            return nil
        }

        let parameterValues = Dictionary(uniqueKeysWithValues: zip(inlineTarget.params.map(\.symbol), arguments))

        let typeParamTokenValues = buildTypeParamTokenValues(
            inlineTarget: inlineTarget,
            parameterValues: parameterValues,
            ctx: ctx
        )

        // Build a set of parameter symbols that have function types so we can
        // detect calls to lambda parameters inside the inline body.
        let lambdaParamSymbols: Set<SymbolID> = {
            guard let sema = ctx.sema else { return [] }
            var result: Set<SymbolID> = []
            for param in inlineTarget.params {
                if case .functionType = sema.types.kind(of: param.type) {
                    result.insert(param.symbol)
                }
            }
            return result
        }()

        var localExprMap: [KIRExprID: KIRExprID] = [:]
        var lowered: [KIRInstruction] = []
        lowered.reserveCapacity(inlineTarget.body.count)
        var returnedExpr: KIRExprID?
        var hasNonLocalReturn = false
        var hasNormalReturn = false

        // Build a label remapping so that each inline expansion gets unique
        // label IDs. This prevents collisions when the same function is
        // inlined multiple times or when the inlined labels conflict with
        // labels already present in the caller.
        var labelRemap: [Int32: Int32] = [:]
        for instruction in inlineTarget.body {
            if case let .label(id) = instruction {
                let freshLabel = inlineLabelCounter
                inlineLabelCounter += 1
                labelRemap[id] = freshLabel
            }
        }

        for instruction in inlineTarget.body {
            switch instruction {
            case .beginBlock, .endBlock:
                continue

            case .nop:
                lowered.append(.nop)

            case let .label(id):
                lowered.append(.label(labelRemap[id] ?? id))

            case let .jump(target):
                lowered.append(.jump(labelRemap[target] ?? target))

            case let .jumpIfEqual(lhs, rhs, target):
                lowered.append(
                    .jumpIfEqual(
                        lhs: resolveAlias(of: lhs, aliases: localExprMap),
                        rhs: resolveAlias(of: rhs, aliases: localExprMap),
                        target: labelRemap[target] ?? target
                    )
                )

            case .returnUnit:
                hasNormalReturn = true
                returnedExpr = nil
                // Preserve in lowered instructions so inlineTransform can
                // convert it to an exit-label jump in the NLR path.
                lowered.append(.returnUnit)

            case let .returnValue(value):
                hasNormalReturn = true
                let resolved = resolveAlias(of: value, aliases: localExprMap)
                returnedExpr = resolved
                // Preserve in lowered instructions so inlineTransform can
                // convert it to an exit-label jump in the NLR path.
                lowered.append(.returnValue(resolved))

            case let .nonLocalReturn(value):
                // Non-local return from a lambda inside this inline function.
                // Preserve it so the caller's inlineTransform can convert it
                // to a real return from the enclosing function.
                hasNonLocalReturn = true
                if let value {
                    lowered.append(.nonLocalReturn(resolveAlias(of: value, aliases: localExprMap)))
                } else {
                    lowered.append(.nonLocalReturn(nil))
                }

            case let .constValue(result, value):
                if case let .symbolRef(symbol) = value,
                   let mapped = parameterValues[symbol] ?? typeParamTokenValues[symbol]
                {
                    localExprMap[result] = mapped
                    continue
                }
                let loweredResult = cloneExpr(result, in: module.arena)
                localExprMap[result] = loweredResult
                lowered.append(.constValue(result: loweredResult, value: value))

            case let .binary(op, lhs, rhs, result):
                let loweredResult = cloneExpr(result, in: module.arena)
                localExprMap[result] = loweredResult
                lowered.append(
                    .binary(
                        op: op,
                        lhs: resolveAlias(of: lhs, aliases: localExprMap),
                        rhs: resolveAlias(of: rhs, aliases: localExprMap),
                        result: loweredResult
                    )
                )

            case let .call(symbol, callee, args, result, canThrow, thrownResult, isSuperCall):
                // Attempt to inline a lambda argument passed to this inline function.
                // When the call target is a parameter with function type, and the
                // caller passed a known lambda function, we expand the lambda body
                // in place instead of emitting an indirect call.
                if let symbol, lambdaParamSymbols.contains(symbol),
                   canThrow == false, thrownResult == nil,
                   let argExpr = parameterValues[symbol],
                   let lambdaFunction = resolveLambdaFunction(
                       argExpr: argExpr,
                       arena: module.arena,
                       allFunctionsBySymbol: allFunctionsBySymbol,
                       callerBody: callerBody
                   ),
                   let lambdaExpansion = expandLambdaBody(
                       lambdaFunction: lambdaFunction,
                       arguments: args.map { resolveAlias(of: $0, aliases: localExprMap) },
                       module: module
                   )
                {
                    lowered.append(contentsOf: lambdaExpansion.instructions)
                    if let result {
                        if let lambdaReturn = lambdaExpansion.returnedExpr {
                            localExprMap[result] = lambdaReturn
                        } else {
                            // Unit-returning lambda: synthesize a unit constant
                            // so that downstream references to the result resolve
                            // to a valid expression instead of dangling.
                            let unitExpr = module.arena.appendExpr(.unit, type: nil)
                            lowered.append(.constValue(result: unitExpr, value: .unit))
                            localExprMap[result] = unitExpr
                        }
                    }
                    break
                }

                let loweredResult = result.map { expr -> KIRExprID in
                    let cloned = cloneExpr(expr, in: module.arena)
                    localExprMap[expr] = cloned
                    return cloned
                }
                let loweredThrownResult = thrownResult.map { expr -> KIRExprID in
                    let cloned = cloneExpr(expr, in: module.arena)
                    localExprMap[expr] = cloned
                    return cloned
                }
                lowered.append(
                    .call(
                        symbol: symbol,
                        callee: callee,
                        arguments: args.map { resolveAlias(of: $0, aliases: localExprMap) },
                        result: loweredResult,
                        canThrow: canThrow,
                        thrownResult: loweredThrownResult,
                        isSuperCall: isSuperCall
                    )
                )

            case let .virtualCall(symbol, callee, receiver, args, result, canThrow, thrownResult, dispatch):
                let loweredResult = result.map { expr -> KIRExprID in
                    let cloned = cloneExpr(expr, in: module.arena)
                    localExprMap[expr] = cloned
                    return cloned
                }
                let loweredThrownResult = thrownResult.map { expr -> KIRExprID in
                    let cloned = cloneExpr(expr, in: module.arena)
                    localExprMap[expr] = cloned
                    return cloned
                }
                lowered.append(
                    .virtualCall(
                        symbol: symbol,
                        callee: callee,
                        receiver: resolveAlias(of: receiver, aliases: localExprMap),
                        arguments: args.map { resolveAlias(of: $0, aliases: localExprMap) },
                        result: loweredResult,
                        canThrow: canThrow,
                        thrownResult: loweredThrownResult,
                        dispatch: dispatch
                    )
                )

            case let .returnIfEqual(lhs, rhs):
                lowered.append(
                    .returnIfEqual(
                        lhs: resolveAlias(of: lhs, aliases: localExprMap),
                        rhs: resolveAlias(of: rhs, aliases: localExprMap)
                    )
                )

            case let .jumpIfNotNull(value, target):
                lowered.append(
                    .jumpIfNotNull(
                        value: resolveAlias(of: value, aliases: localExprMap),
                        target: labelRemap[target] ?? target
                    )
                )

            case let .copy(from, to):
                lowered.append(
                    .copy(
                        from: resolveAlias(of: from, aliases: localExprMap),
                        to: resolveAlias(of: to, aliases: localExprMap)
                    )
                )

            case let .storeGlobal(value, symbol):
                lowered.append(
                    .storeGlobal(
                        value: resolveAlias(of: value, aliases: localExprMap),
                        symbol: symbol
                    )
                )

            case let .loadGlobal(result, symbol):
                let loweredResult = cloneExpr(result, in: module.arena)
                localExprMap[result] = loweredResult
                lowered.append(.loadGlobal(result: loweredResult, symbol: symbol))

            case let .rethrow(value):
                lowered.append(
                    .rethrow(value: resolveAlias(of: value, aliases: localExprMap))
                )

            case let .unary(op, operand, result):
                let loweredResult = cloneExpr(result, in: module.arena)
                localExprMap[result] = loweredResult
                lowered.append(
                    .unary(
                        op: op,
                        operand: resolveAlias(of: operand, aliases: localExprMap),
                        result: loweredResult
                    )
                )

            case let .nullAssert(operand, result):
                let loweredResult = cloneExpr(result, in: module.arena)
                localExprMap[result] = loweredResult
                lowered.append(
                    .nullAssert(
                        operand: resolveAlias(of: operand, aliases: localExprMap),
                        result: loweredResult
                    )
                )

            case .beginFinallyGuard:
                lowered.append(.beginFinallyGuard)

            case .endFinallyGuard:
                lowered.append(.endFinallyGuard)
            }
        }

        return InlineExpansion(
            instructions: lowered,
            returnedExpr: returnedExpr,
            hasNonLocalReturn: hasNonLocalReturn,
            hasNormalReturn: hasNormalReturn
        )
    }

    // MARK: - Lambda Inlining

    /// Resolve the lambda function for an argument expression. The argument
    /// expression may be a direct `symbolRef` pointing to a lambda KIR function,
    /// or it may be a temporary that was defined via a `constValue` instruction
    /// carrying a `symbolRef` payload. Both patterns are resolved here so that
    /// lambda inlining works regardless of how the call argument was materialized.
    private func resolveLambdaFunction(
        argExpr: KIRExprID,
        arena: KIRArena,
        allFunctionsBySymbol: [SymbolID: KIRFunction],
        callerBody: [KIRInstruction]
    ) -> KIRFunction? {
        // Direct symbolRef on the expression itself (most common path).
        if case let .symbolRef(lambdaSymbol)? = arena.expr(argExpr) {
            if let fn = allFunctionsBySymbol[lambdaSymbol] {
                return fn
            }
        }
        // Fall back: scan the caller body for a constValue that defines this
        // expression with a symbolRef value. This handles cases where the
        // argument is a temporary assigned via `.constValue(result: argExpr,
        // value: .symbolRef(symbol))`.
        for instruction in callerBody {
            if case let .constValue(result, .symbolRef(symbol)) = instruction,
               result == argExpr,
               let fn = allFunctionsBySymbol[symbol]
            {
                return fn
            }
        }
        return nil
    }

    /// Expand a lambda function body inline, substituting parameters with the
    /// provided call arguments. This is analogous to `expandInlineCall` but
    /// operates on non-inline lambda functions that are passed as arguments to
    /// inline functions.
    ///
    /// Returns `nil` when the expansion cannot proceed (e.g. argument/parameter
    /// count mismatch), signalling the caller to fall back to a regular call.
    private func expandLambdaBody(
        lambdaFunction: KIRFunction,
        arguments: [KIRExprID],
        module: KIRModule
    ) -> InlineExpansion? {
        // Map lambda parameters to arguments. If the argument count does not
        // match the parameter count, skip capture parameters at the front and
        // map only the trailing value parameters.
        var lambdaParamValues: [SymbolID: KIRExprID] = [:]
        let paramCount = lambdaFunction.params.count
        if arguments.count == paramCount {
            for (param, arg) in zip(lambdaFunction.params, arguments) {
                lambdaParamValues[param.symbol] = arg
            }
        } else if arguments.count < paramCount {
            // The call supplies only value arguments; the leading parameters
            // are captures that were already bound at the call site.
            let offset = paramCount - arguments.count
            for i in 0 ..< arguments.count {
                lambdaParamValues[lambdaFunction.params[offset + i].symbol] = arguments[i]
            }
        } else {
            // More arguments than parameters -- cannot inline; caller will
            // fall back to emitting the original call instruction.
            return nil
        }

        var localExprMap: [KIRExprID: KIRExprID] = [:]
        var lowered: [KIRInstruction] = []
        lowered.reserveCapacity(lambdaFunction.body.count)
        var returnedExpr: KIRExprID?

        // Count return instructions to decide whether we need a merge label.
        // Lambda bodies with control flow (if/else branches) can contain
        // multiple return instructions; breaking at the first one would
        // truncate the remaining branches.
        let returnCount = lambdaFunction.body.reduce(0) { count, inst in
            switch inst {
            case .returnUnit, .returnValue: return count + 1
            default: return count
            }
        }
        let needsMergeLabel = returnCount > 1
        let exitLabel: Int32
        var mergeResult: KIRExprID?
        if needsMergeLabel {
            exitLabel = inlineLabelCounter
            inlineLabelCounter += 1
            // For value-returning lambdas, allocate a merge expression to
            // hold the returned value from whichever branch executes.
            let hasValueReturn = lambdaFunction.body.contains {
                if case .returnValue = $0 { return true }
                return false
            }
            if hasValueReturn {
                // Allocate a fresh merge temporary for the returned value.
                // Uses the lambda's declared return type so later passes see
                // a properly typed merge expression.
                let returnType = lambdaFunction.returnType
                let mergeID = module.arena.appendExpr(
                    .temporary(Int32(module.arena.expressions.count)),
                    type: returnType
                )
                mergeResult = mergeID
            }
        } else {
            exitLabel = -1
        }

        // Build a label remapping so that each expansion gets unique label IDs.
        // This prevents collisions when the same lambda is inlined multiple times
        // or when the lambda's labels conflict with labels already in the caller.
        var labelRemap: [Int32: Int32] = [:]
        for instruction in lambdaFunction.body {
            if case let .label(id) = instruction {
                let freshLabel = inlineLabelCounter
                inlineLabelCounter += 1
                labelRemap[id] = freshLabel
            }
        }

        for instruction in lambdaFunction.body {
            switch instruction {
            case .beginBlock, .endBlock:
                continue

            case .nop:
                lowered.append(.nop)

            case let .label(id):
                lowered.append(.label(labelRemap[id] ?? id))

            case let .jump(target):
                lowered.append(.jump(labelRemap[target] ?? target))

            case let .jumpIfEqual(lhs, rhs, target):
                lowered.append(
                    .jumpIfEqual(
                        lhs: resolveAlias(of: lhs, aliases: localExprMap),
                        rhs: resolveAlias(of: rhs, aliases: localExprMap),
                        target: labelRemap[target] ?? target
                    )
                )

            case .returnUnit:
                if needsMergeLabel {
                    returnedExpr = nil
                    lowered.append(.jump(exitLabel))
                } else {
                    returnedExpr = nil
                }

            case let .returnValue(value):
                let resolved = resolveAlias(of: value, aliases: localExprMap)
                if needsMergeLabel, let dest = mergeResult {
                    lowered.append(.copy(from: resolved, to: dest))
                    lowered.append(.jump(exitLabel))
                    returnedExpr = dest
                } else {
                    returnedExpr = resolved
                }

            case let .constValue(result, value):
                if case let .symbolRef(symbol) = value,
                   let mapped = lambdaParamValues[symbol]
                {
                    localExprMap[result] = mapped
                    continue
                }
                let loweredResult = cloneExpr(result, in: module.arena)
                localExprMap[result] = loweredResult
                lowered.append(.constValue(result: loweredResult, value: value))

            case let .binary(op, lhs, rhs, result):
                let loweredResult = cloneExpr(result, in: module.arena)
                localExprMap[result] = loweredResult
                lowered.append(
                    .binary(
                        op: op,
                        lhs: resolveAlias(of: lhs, aliases: localExprMap),
                        rhs: resolveAlias(of: rhs, aliases: localExprMap),
                        result: loweredResult
                    )
                )

            case let .call(symbol, callee, args, result, canThrow, thrownResult, isSuperCall):
                let loweredResult = result.map { expr -> KIRExprID in
                    let cloned = cloneExpr(expr, in: module.arena)
                    localExprMap[expr] = cloned
                    return cloned
                }
                let loweredThrownResult = thrownResult.map { expr -> KIRExprID in
                    let cloned = cloneExpr(expr, in: module.arena)
                    localExprMap[expr] = cloned
                    return cloned
                }
                lowered.append(
                    .call(
                        symbol: symbol,
                        callee: callee,
                        arguments: args.map { resolveAlias(of: $0, aliases: localExprMap) },
                        result: loweredResult,
                        canThrow: canThrow,
                        thrownResult: loweredThrownResult,
                        isSuperCall: isSuperCall
                    )
                )

            case let .virtualCall(symbol, callee, receiver, args, result, canThrow, thrownResult, dispatch):
                let loweredResult = result.map { expr -> KIRExprID in
                    let cloned = cloneExpr(expr, in: module.arena)
                    localExprMap[expr] = cloned
                    return cloned
                }
                let loweredThrownResult = thrownResult.map { expr -> KIRExprID in
                    let cloned = cloneExpr(expr, in: module.arena)
                    localExprMap[expr] = cloned
                    return cloned
                }
                lowered.append(
                    .virtualCall(
                        symbol: symbol,
                        callee: callee,
                        receiver: resolveAlias(of: receiver, aliases: localExprMap),
                        arguments: args.map { resolveAlias(of: $0, aliases: localExprMap) },
                        result: loweredResult,
                        canThrow: canThrow,
                        thrownResult: loweredThrownResult,
                        dispatch: dispatch
                    )
                )

            case let .returnIfEqual(lhs, rhs):
                lowered.append(
                    .returnIfEqual(
                        lhs: resolveAlias(of: lhs, aliases: localExprMap),
                        rhs: resolveAlias(of: rhs, aliases: localExprMap)
                    )
                )

            case let .jumpIfNotNull(value, target):
                lowered.append(
                    .jumpIfNotNull(
                        value: resolveAlias(of: value, aliases: localExprMap),
                        target: labelRemap[target] ?? target
                    )
                )

            case let .copy(from, to):
                lowered.append(
                    .copy(
                        from: resolveAlias(of: from, aliases: localExprMap),
                        to: resolveAlias(of: to, aliases: localExprMap)
                    )
                )

            case let .storeGlobal(value, symbol):
                lowered.append(
                    .storeGlobal(
                        value: resolveAlias(of: value, aliases: localExprMap),
                        symbol: symbol
                    )
                )

            case let .loadGlobal(result, symbol):
                let loweredResult = cloneExpr(result, in: module.arena)
                localExprMap[result] = loweredResult
                lowered.append(.loadGlobal(result: loweredResult, symbol: symbol))

            case let .rethrow(value):
                lowered.append(
                    .rethrow(value: resolveAlias(of: value, aliases: localExprMap))
                )

            case let .unary(op, operand, result):
                let loweredResult = cloneExpr(result, in: module.arena)
                localExprMap[result] = loweredResult
                lowered.append(
                    .unary(
                        op: op,
                        operand: resolveAlias(of: operand, aliases: localExprMap),
                        result: loweredResult
                    )
                )

            case let .nullAssert(operand, result):
                let loweredResult = cloneExpr(result, in: module.arena)
                localExprMap[result] = loweredResult
                lowered.append(
                    .nullAssert(
                        operand: resolveAlias(of: operand, aliases: localExprMap),
                        result: loweredResult
                    )
                )

            case let .nonLocalReturn(value):
                // Non-local return from a nested lambda. Preserve it so the
                // caller's inlineTransform can convert it to a real return.
                if let value {
                    lowered.append(.nonLocalReturn(resolveAlias(of: value, aliases: localExprMap)))
                } else {
                    lowered.append(.nonLocalReturn(nil))
                }

            case .beginFinallyGuard:
                lowered.append(.beginFinallyGuard)

            case .endFinallyGuard:
                lowered.append(.endFinallyGuard)
            }
        }

        // Emit merge label so all branches converge after the inlined body.
        if needsMergeLabel {
            lowered.append(.label(exitLabel))
        }

        return InlineExpansion(
            instructions: lowered,
            returnedExpr: returnedExpr,
            hasNonLocalReturn: false,
            hasNormalReturn: false
        )
    }

    private func buildTypeParamTokenValues(
        inlineTarget: KIRFunction,
        parameterValues: [SymbolID: KIRExprID],
        ctx: KIRContext
    ) -> [SymbolID: KIRExprID] {
        guard let sema = ctx.sema,
              let sig = sema.symbols.functionSignature(for: inlineTarget.symbol),
              !sig.reifiedTypeParameterIndices.isEmpty
        else {
            return [:]
        }
        var result: [SymbolID: KIRExprID] = [:]
        for index in sig.reifiedTypeParameterIndices.sorted() {
            guard index < sig.typeParameterSymbols.count else { continue }
            let typeParamSymbol = sig.typeParameterSymbols[index]
            let tokenSymbol = SyntheticSymbolScheme.reifiedTypeTokenSymbol(for: typeParamSymbol)
            if let tokenArg = parameterValues[tokenSymbol] {
                result[typeParamSymbol] = tokenArg
            }
        }
        return result
    }

    private func rewriteInstruction(_ instruction: KIRInstruction, aliases: [KIRExprID: KIRExprID]) -> KIRInstruction {
        switch instruction {
        case let .binary(op, lhs, rhs, result):
            .binary(
                op: op,
                lhs: resolveAlias(of: lhs, aliases: aliases),
                rhs: resolveAlias(of: rhs, aliases: aliases),
                result: result
            )

        case let .call(symbol, callee, arguments, result, canThrow, thrownResult, isSuperCall):
            .call(
                symbol: symbol,
                callee: callee,
                arguments: arguments.map { resolveAlias(of: $0, aliases: aliases) },
                result: result,
                canThrow: canThrow,
                thrownResult: thrownResult,
                isSuperCall: isSuperCall
            )

        case let .virtualCall(symbol, callee, receiver, arguments, result, canThrow, thrownResult, dispatch):
            .virtualCall(
                symbol: symbol,
                callee: callee,
                receiver: resolveAlias(of: receiver, aliases: aliases),
                arguments: arguments.map { resolveAlias(of: $0, aliases: aliases) },
                result: result,
                canThrow: canThrow,
                thrownResult: thrownResult,
                dispatch: dispatch
            )

        case let .returnValue(value):
            .returnValue(resolveAlias(of: value, aliases: aliases))

        case let .nonLocalReturn(value):
            .nonLocalReturn(value.map { resolveAlias(of: $0, aliases: aliases) })

        case let .returnIfEqual(lhs, rhs):
            .returnIfEqual(
                lhs: resolveAlias(of: lhs, aliases: aliases),
                rhs: resolveAlias(of: rhs, aliases: aliases)
            )

        case let .jumpIfEqual(lhs, rhs, target):
            .jumpIfEqual(
                lhs: resolveAlias(of: lhs, aliases: aliases),
                rhs: resolveAlias(of: rhs, aliases: aliases),
                target: target
            )

        case let .jumpIfNotNull(value, target):
            .jumpIfNotNull(
                value: resolveAlias(of: value, aliases: aliases),
                target: target
            )

        case let .copy(from, to):
            .copy(
                from: resolveAlias(of: from, aliases: aliases),
                to: resolveAlias(of: to, aliases: aliases)
            )

        case let .rethrow(value):
            .rethrow(value: resolveAlias(of: value, aliases: aliases))

        case let .unary(op, operand, result):
            .unary(
                op: op,
                operand: resolveAlias(of: operand, aliases: aliases),
                result: result
            )

        case let .nullAssert(operand, result):
            .nullAssert(
                operand: resolveAlias(of: operand, aliases: aliases),
                result: result
            )

        case let .storeGlobal(value, symbol):
            .storeGlobal(
                value: resolveAlias(of: value, aliases: aliases),
                symbol: symbol
            )

        case .loadGlobal:
            instruction

        default:
            instruction
        }
    }

    private func definedResult(in instruction: KIRInstruction) -> KIRExprID? {
        switch instruction {
        case let .constValue(result, _):
            result
        case let .binary(_, _, _, result):
            result
        case let .call(_, _, _, result, _, _, _):
            result
        case let .virtualCall(_, _, _, _, result, _, _, _):
            result
        case let .unary(_, _, result):
            result
        case let .nullAssert(_, result):
            result
        case let .loadGlobal(result, _):
            result
        default:
            nil
        }
    }

    private func resolveAlias(of expr: KIRExprID, aliases: [KIRExprID: KIRExprID]) -> KIRExprID {
        var current = expr
        var visited: Set<KIRExprID> = []
        while let next = aliases[current], visited.insert(current).inserted {
            if next == current {
                break
            }
            current = next
        }
        return current
    }

    private func cloneExpr(_ source: KIRExprID, in arena: KIRArena) -> KIRExprID {
        let fallback = KIRExprKind.temporary(Int32(arena.expressions.count))
        return arena.appendExpr(
            arena.expr(source) ?? fallback,
            type: arena.exprType(source)
        )
    }
}
