#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
MANIFEST="${ARCH025_MANIFEST:-$ROOT_DIR/Tests/ARCH-025/manifest.tsv}"
LEDGER="$ROOT_DIR/Tests/ARCH-025/ledger.tsv"
KSWIFTC="${KSWIFTC:-$ROOT_DIR/.build/debug/kswiftc}"
WRITE_LEDGER=0

usage() {
  cat <<USAGE
Usage: $(basename "$0") [--write-ledger] [--kswiftc <path>]

Run the local ARCH-025 fixture subset serially.

Options:
  --write-ledger       Replace Tests/ARCH-025/ledger.tsv with deterministic results.
  --kswiftc <path>    Use a specific kswiftc executable.
  -h, --help          Show this help.

The runner intentionally does not run in CI and does not invoke kotlinc.
USAGE
}

if command -v shasum >/dev/null 2>&1; then
  HASH_CMD=(shasum -a 256)
else
  HASH_CMD=(sha256sum)
fi

hash_file() {
  local out
  out="$("${HASH_CMD[@]}" "$1")"
  printf '%s\n' "${out%% *}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --write-ledger)
      WRITE_LEDGER=1
      ;;
    --kswiftc)
      shift
      [[ $# -gt 0 ]] || { echo "--kswiftc requires a path" >&2; exit 1; }
      KSWIFTC="$1"
      ;;
    --kswiftc=*)
      KSWIFTC="${1#*=}"
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
  shift
done

[[ -f "$MANIFEST" ]] || { echo "Manifest not found: $MANIFEST" >&2; exit 1; }

if [[ -x "$KSWIFTC" ]]; then
  kswiftc_executable=1
else
  kswiftc_executable=0
fi

TEMP_ROOT="$(mktemp -d "${TMPDIR:-/tmp}/arch025-run.XXXXXX")"
trap 'rm -rf "$TEMP_ROOT"' EXIT

ledger_body="$TEMP_ROOT/ledger_body.tsv"
printf '%s\n' \
  '# ARCH-025 ledger; generated by Scripts/run_arch025_testdata.sh.' \
  '# Upstream revision: 679366a83f99851b42f64795f10ed803ff011c73 (v2.3.10)' \
  $'id\tkind\tfixture\texpected\tstatus\tcompile_exit\trun_exit\tdetail\tsha256' \
  >"$ledger_body"
total=0
pass_count=0
fail_count=0
unsupported_count=0

while IFS=$'\t' read -r record_id kind _ fixture_path expected availability sha256 rationale; do
  [[ -z "$record_id" || "${record_id#\#}" != "$record_id" ]] && continue
  total=$((total + 1))
  fixture="$ROOT_DIR/$fixture_path"
  compile_exit="-"
  run_exit="-"
  if [[ ! -f "$fixture" ]]; then
    status="fail"
    detail="missing_fixture"
  elif [[ "$(hash_file "$fixture")" != "$sha256" ]]; then
    status="fail"
    detail="fixture_hash_mismatch"
  elif [[ "$availability" == "unsupported" ]]; then
    status="unsupported"
    detail="unsupported:$rationale"
  else
    case_dir="$TEMP_ROOT/$record_id"
    mkdir -p "$case_dir"
    input_file="$case_dir/input.kt"
    output_file="$case_dir/program"
    stdout_file="$case_dir/stdout.txt"
    stderr_file="$case_dir/stderr.txt"
    status=""

    if [[ "$kind" == "diagnostics" ]]; then
      # Remove JetBrains diagnostic markup only in the temporary input.
      sed -E 's/<![^>]*>//g' "$fixture" >"$input_file"
    elif [[ "$kind" == "codegen" ]]; then
      # Kotlin compiler box tests expose box() instead of a process entry point.
      {
        cat "$fixture"
        printf '\nfun main() { print(box()) }\n'
      } >"$input_file"
    else
      status="fail"
      detail="unknown_kind"
    fi

    if [[ "$status" != "fail" ]]; then
      if [[ $kswiftc_executable -eq 1 ]]; then
        if "$KSWIFTC" "$input_file" -o "$output_file" >"$stdout_file" 2>"$stderr_file"; then
          compile_exit=0
        else
          compile_exit=$?
        fi
      else
        compile_exit=127
        printf 'kswiftc not executable: %s\n' "$KSWIFTC" >"$stderr_file"
      fi

      if [[ "$expected" == "reject" ]]; then
        if [[ "$compile_exit" -ne 0 ]]; then
          status="pass"
          detail="expected_rejection"
        else
          status="fail"
          detail="unexpected_acceptance"
        fi
      elif [[ "$expected" == box:* ]]; then
        expected_output="${expected#box:}"
        if [[ "$compile_exit" -ne 0 ]]; then
          status="fail"
          detail="compile_exit_${compile_exit}"
        elif "$output_file" >"$stdout_file" 2>"$stderr_file"; then
          run_exit=0
          actual_output="$(tr -d '\r' <"$stdout_file")"
          if [[ "$actual_output" == "$expected_output" ]]; then
            status="pass"
            detail="box_output_${expected_output}"
          else
            status="fail"
            detail="box_output_mismatch"
          fi
        else
          run_exit=$?
          status="fail"
          detail="run_exit_${run_exit}"
        fi
      else
        status="fail"
        detail="unknown_expectation"
      fi
    fi
  fi

  case "$status" in
    pass)
      pass_count=$((pass_count + 1))
      ;;
    fail)
      fail_count=$((fail_count + 1))
      ;;
    unsupported)
      unsupported_count=$((unsupported_count + 1))
      ;;
  esac

  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
    "$record_id" "$kind" "$fixture_path" "$expected" "$status" "$compile_exit" "$run_exit" "$detail" "$sha256" >>"$ledger_body"
  printf '%s\t%s\t%s\n' "$status" "$record_id" "$detail"
done < "$MANIFEST"

if [[ $WRITE_LEDGER -eq 1 ]]; then
  mv "$ledger_body" "$LEDGER"
  echo "Wrote $LEDGER"
else
  cat "$ledger_body"
fi

printf 'summary total=%s pass=%s fail=%s unsupported=%s\n' "$total" "$pass_count" "$fail_count" "$unsupported_count"
if [[ $fail_count -ne 0 ]]; then
  exit 1
fi
