fun main() {
    println("  hello  ".trim())
    println("1,2,3".split(","))
    println("42".toInt())

    println("banana".replace("na", "NA"))
    println(if ("Kotlin".startsWith("Ko")) "true" else "false")
    println(if ("Kotlin".endsWith("in")) "true" else "false")
    println(if ("Kotlin".contains("otl")) "true" else "false")

    println(" 3.14 ".toDouble())
    println("%s:%d".format("age", 7))
    println("%.2f".format(3.5))
    println("progress=100%%".format())
    println("hello".substring(1))
    println("hello".substring(1, 3))
    println("Hello".lowercase())
    println("Hello".uppercase())
    println("123".toIntOrNull())
    println("abc".toIntOrNull())
    println(" 3.14 ".toDoubleOrNull())
    println("abc".toDoubleOrNull())
    println("abcabc".indexOf("bc"))
    println("abcabc".lastIndexOf("bc"))
    println("abc".reversed())
    println("abc".toList())
    println("abc".toCharArray()[0])
    println("abcde".take(3))
    println("abcde".drop(2))
    println("abcde".takeLast(2))
    println("abcde".dropLast(2))
    println("42".padStart(5, '0'))
    println("42".padEnd(5, '0'))
    println("ab".repeat(3))
}
